"""
African banks registry – central banks, commercial banks and regional development banks.

Coverage:
- All 54 African Union member states (central banks) with contact information
- Priority commercial banks for 22 countries with contact details
- Major pan-African and regional development banks
"""

from typing import Dict, List, Optional
from .models import CentralBank, CommercialBank, RegionalBank, BankingSystemInfo, BankContact

# ---------------------------------------------------------------------------
# CENTRAL BANKS – 54 African countries
# ---------------------------------------------------------------------------

CENTRAL_BANKS: Dict[str, CentralBank] = {
    # ── NORTH AFRICA ────────────────────────────────────────────────────────
    "MA": CentralBank(
        country_code="MA", country_name="Maroc",
        name="Bank Al-Maghrib", abbreviation="BAM",
        website="https://www.bkam.ma", swift_code="BKAMMAMR",
        forex_regulation="strict", currency_code="MAD", currency_name="Dirham marocain",
        established_year=1959, banking_act="Loi bancaire n° 103-12 (2014)",
        address="277, Avenue Mohammed V, Rabat 10000, Maroc",
        phone="+212 537 70 26 26",
        email="communication@bkam.ma",
        contact=BankContact(
            address="277, Avenue Mohammed V, Rabat 10000, Maroc",
            phone="+212 537 70 26 26", email="communication@bkam.ma",
            website="https://www.bkam.ma", department="Direction des Relations Extérieures",
        ),
    ),
    "DZ": CentralBank(
        country_code="DZ", country_name="Algérie",
        name="Banque d'Algérie", abbreviation="BA",
        website="https://www.bank-of-algeria.dz", swift_code="BADALYDZ",
        forex_regulation="strict", currency_code="DZD", currency_name="Dinar algérien",
        established_year=1962, banking_act="Loi n° 90-10 relative à la monnaie et au crédit",
        address="38, Avenue Franklin Roosevelt, Alger 16000, Algérie",
        phone="+213 21 23 40 40",
        email="info@bank-of-algeria.dz",
        contact=BankContact(
            address="38, Avenue Franklin Roosevelt, Alger 16000, Algérie",
            phone="+213 21 23 40 40", email="info@bank-of-algeria.dz",
            website="https://www.bank-of-algeria.dz", department="Direction des Relations Internationales",
        ),
    ),
    "TN": CentralBank(
        country_code="TN", country_name="Tunisie",
        name="Banque Centrale de Tunisie", abbreviation="BCT",
        website="https://www.bct.gov.tn", swift_code="BCTUTNTT",
        forex_regulation="moderate", currency_code="TND", currency_name="Dinar tunisien",
        established_year=1958, banking_act="Loi n° 2016-48 relative aux banques et aux établissements financiers",
        address="25, Rue Hédi Nouira, BP 777, Tunis 1080, Tunisie",
        phone="+216 71 340 588",
        email="dri@bct.gov.tn",
        contact=BankContact(
            address="25, Rue Hédi Nouira, BP 777, Tunis 1080, Tunisie",
            phone="+216 71 340 588", email="dri@bct.gov.tn",
            website="https://www.bct.gov.tn", department="Direction des Relations Internationales",
        ),
    ),
    "EG": CentralBank(
        country_code="EG", country_name="Égypte",
        name="Central Bank of Egypt", abbreviation="CBE",
        website="https://www.cbe.org.eg", swift_code="CBEGEGCX",
        forex_regulation="moderate", currency_code="EGP", currency_name="Livre égyptienne",
        established_year=1961, banking_act="Banking Law No. 194 of 2020",
        address="31, Qasr El Nil Street, Cairo 11511, Egypt",
        phone="+202 27701770",
        email="info@cbe.org.eg",
        contact=BankContact(
            address="31, Qasr El Nil Street, Cairo 11511, Egypt",
            phone="+202 27701770", email="info@cbe.org.eg",
            website="https://www.cbe.org.eg", department="International Relations Department",
        ),
    ),
    "LY": CentralBank(
        country_code="LY", country_name="Libye",
        name="Central Bank of Libya", abbreviation="CBL",
        website="https://cbl.gov.ly", swift_code=None,
        forex_regulation="strict", currency_code="LYD", currency_name="Dinar libyen",
        established_year=1956,
        address="Ibn Ashour Street, Tripoli, Libya",
        phone="+218 21 4440151",
        email="info@cbl.gov.ly",
        contact=BankContact(
            address="Ibn Ashour Street, Tripoli, Libya",
            phone="+218 21 4440151", email="info@cbl.gov.ly",
            website="https://cbl.gov.ly",
        ),
    ),
    "SD": CentralBank(
        country_code="SD", country_name="Soudan",
        name="Central Bank of Sudan", abbreviation="CBS",
        website="https://www.cbos.gov.sd", swift_code=None,
        forex_regulation="strict", currency_code="SDG", currency_name="Livre soudanaise",
        established_year=1960,
        address="P.O. Box 313, Al Neel Avenue, Khartoum, Sudan",
        phone="+249 183 774927",
        email="info@cbos.gov.sd",
        contact=BankContact(
            address="Al Neel Avenue, Khartoum, Sudan",
            phone="+249 183 774927", email="info@cbos.gov.sd",
            website="https://www.cbos.gov.sd",
        ),
    ),

    # ── WEST AFRICA ─────────────────────────────────────────────────────────
    "NG": CentralBank(
        country_code="NG", country_name="Nigeria",
        name="Central Bank of Nigeria", abbreviation="CBN",
        website="https://www.cbn.gov.ng", swift_code="CENBNGLX",
        forex_regulation="strict", currency_code="NGN", currency_name="Naira nigérian",
        established_year=1959, banking_act="Banks and Other Financial Institutions Act 2020",
        address="33, Tafawa Balewa Way, Central Business District, Abuja 900001, Nigeria",
        phone="+234 9 462 32000",
        email="info@cbn.gov.ng",
        contact=BankContact(
            address="33, Tafawa Balewa Way, Abuja, Nigeria",
            phone="+234 9 462 32000", email="info@cbn.gov.ng",
            website="https://www.cbn.gov.ng", department="Trade and Exchange Department",
        ),
    ),
    "GH": CentralBank(
        country_code="GH", country_name="Ghana",
        name="Bank of Ghana", abbreviation="BoG",
        website="https://www.bog.gov.gh", swift_code="BGHAGHAL",
        forex_regulation="moderate", currency_code="GHS", currency_name="Cedi ghanéen",
        established_year=1957, banking_act="Banks and Specialised Deposit-Taking Institutions Act 2016",
        address="Thorpe Road, Accra, Ghana",
        phone="+233 30 266 6902",
        email="bogfsd@bog.gov.gh",
        contact=BankContact(
            address="Thorpe Road, Accra, Ghana",
            phone="+233 30 266 6902", email="bogfsd@bog.gov.gh",
            website="https://www.bog.gov.gh", department="Financial Stability Department",
        ),
    ),
    "CI": CentralBank(
        country_code="CI", country_name="Côte d'Ivoire",
        name="Banque Centrale des États de l'Afrique de l'Ouest", abbreviation="BCEAO",
        website="https://www.bceao.int", swift_code="BCEACIAB",
        forex_regulation="moderate", currency_code="XOF", currency_name="Franc CFA BCEAO",
        established_year=1962, banking_act="Loi uniforme BCEAO relative à l'activité bancaire",
        address="Avenue Abdoulaye Fadiga, BP 3108, Dakar, Sénégal (Siège social)",
        phone="+221 33 839 05 00",
        email="bceao@bceao.int",
        contact=BankContact(
            address="Avenue Abdoulaye Fadiga, BP 3108, Dakar, Sénégal",
            phone="+221 33 839 05 00", email="bceao@bceao.int",
            website="https://www.bceao.int",
        ),
    ),
    "SN": CentralBank(
        country_code="SN", country_name="Sénégal",
        name="Banque Centrale des États de l'Afrique de l'Ouest", abbreviation="BCEAO",
        website="https://www.bceao.int", swift_code="BCEASNDA",
        forex_regulation="moderate", currency_code="XOF", currency_name="Franc CFA BCEAO",
        established_year=1962,
        address="Avenue Abdoulaye Fadiga, BP 3108, Dakar 18524, Sénégal",
        phone="+221 33 839 05 00",
        email="bceao@bceao.int",
        contact=BankContact(
            address="Avenue Abdoulaye Fadiga, BP 3108, Dakar, Sénégal",
            phone="+221 33 839 05 00", email="bceao@bceao.int",
            website="https://www.bceao.int",
        ),
    ),
    "ML": CentralBank(
        country_code="ML", country_name="Mali",
        name="Banque Centrale des États de l'Afrique de l'Ouest", abbreviation="BCEAO",
        website="https://www.bceao.int", swift_code=None,
        forex_regulation="moderate", currency_code="XOF", currency_name="Franc CFA BCEAO",
        address="Avenue Abdoulaye Fadiga, BP 3108, Dakar, Sénégal",
        phone="+221 33 839 05 00", email="bceao@bceao.int",
        contact=BankContact(address="Avenue Abdoulaye Fadiga, BP 3108, Dakar, Sénégal", phone="+221 33 839 05 00", email="bceao@bceao.int", website="https://www.bceao.int"),
    ),
    "BF": CentralBank(
        country_code="BF", country_name="Burkina Faso",
        name="Banque Centrale des États de l'Afrique de l'Ouest", abbreviation="BCEAO",
        website="https://www.bceao.int", swift_code=None,
        forex_regulation="moderate", currency_code="XOF", currency_name="Franc CFA BCEAO",
        address="Avenue Abdoulaye Fadiga, BP 3108, Dakar, Sénégal",
        phone="+221 33 839 05 00", email="bceao@bceao.int",
        contact=BankContact(address="Avenue Abdoulaye Fadiga, Dakar, Sénégal", phone="+221 33 839 05 00", email="bceao@bceao.int", website="https://www.bceao.int"),
    ),
    "GN": CentralBank(
        country_code="GN", country_name="Guinée",
        name="Banque Centrale de la République de Guinée", abbreviation="BCRG",
        website="https://www.bcrg-guinee.org", swift_code=None,
        forex_regulation="moderate", currency_code="GNF", currency_name="Franc guinéen",
        established_year=1960,
        address="2, Avenue de la République, Conakry, Guinée",
        phone="+224 622 23 00 01",
        email="info@bcrg-guinee.org",
        contact=BankContact(address="2, Avenue de la République, Conakry, Guinée", phone="+224 622 23 00 01", email="info@bcrg-guinee.org", website="https://www.bcrg-guinee.org"),
    ),
    "NE": CentralBank(
        country_code="NE", country_name="Niger",
        name="Banque Centrale des États de l'Afrique de l'Ouest", abbreviation="BCEAO",
        website="https://www.bceao.int", swift_code=None,
        forex_regulation="moderate", currency_code="XOF", currency_name="Franc CFA BCEAO",
        address="Avenue Abdoulaye Fadiga, Dakar, Sénégal",
        phone="+221 33 839 05 00", email="bceao@bceao.int",
        contact=BankContact(address="Avenue Abdoulaye Fadiga, Dakar, Sénégal", phone="+221 33 839 05 00", email="bceao@bceao.int", website="https://www.bceao.int"),
    ),
    "BJ": CentralBank(
        country_code="BJ", country_name="Bénin",
        name="Banque Centrale des États de l'Afrique de l'Ouest", abbreviation="BCEAO",
        website="https://www.bceao.int", swift_code=None,
        forex_regulation="moderate", currency_code="XOF", currency_name="Franc CFA BCEAO",
        address="Avenue Abdoulaye Fadiga, Dakar, Sénégal",
        phone="+221 33 839 05 00", email="bceao@bceao.int",
        contact=BankContact(address="Avenue Abdoulaye Fadiga, Dakar, Sénégal", phone="+221 33 839 05 00", email="bceao@bceao.int", website="https://www.bceao.int"),
    ),
    "TG": CentralBank(
        country_code="TG", country_name="Togo",
        name="Banque Centrale des États de l'Afrique de l'Ouest", abbreviation="BCEAO",
        website="https://www.bceao.int", swift_code=None,
        forex_regulation="moderate", currency_code="XOF", currency_name="Franc CFA BCEAO",
        address="Avenue Abdoulaye Fadiga, Dakar, Sénégal",
        phone="+221 33 839 05 00", email="bceao@bceao.int",
        contact=BankContact(address="Avenue Abdoulaye Fadiga, Dakar, Sénégal", phone="+221 33 839 05 00", email="bceao@bceao.int", website="https://www.bceao.int"),
    ),
    "MR": CentralBank(
        country_code="MR", country_name="Mauritanie",
        name="Banque Centrale de Mauritanie", abbreviation="BCM",
        website="https://www.bcm.mr", swift_code=None,
        forex_regulation="moderate", currency_code="MRU", currency_name="Ouguiya mauritanien",
        established_year=1973,
        address="Avenue de l'Indépendance, BP 623, Nouakchott, Mauritanie",
        phone="+222 45 25 22 06",
        email="bcm@bcm.mr",
        contact=BankContact(address="Avenue de l'Indépendance, Nouakchott, Mauritanie", phone="+222 45 25 22 06", email="bcm@bcm.mr", website="https://www.bcm.mr"),
    ),
    "GM": CentralBank(
        country_code="GM", country_name="Gambie",
        name="Central Bank of The Gambia", abbreviation="CBG",
        website="https://www.cbg.gm", swift_code=None,
        forex_regulation="liberal", currency_code="GMD", currency_name="Dalasi gambien",
        established_year=1971,
        address="1-2 ECOWAS Avenue, Banjul, Gambia",
        phone="+220 422 1621",
        email="info@cbg.gm",
        contact=BankContact(address="1-2 ECOWAS Avenue, Banjul, Gambia", phone="+220 422 1621", email="info@cbg.gm", website="https://www.cbg.gm"),
    ),
    "SL": CentralBank(
        country_code="SL", country_name="Sierra Leone",
        name="Bank of Sierra Leone", abbreviation="BSL",
        website="https://www.bsl.gov.sl", swift_code=None,
        forex_regulation="moderate", currency_code="SLL", currency_name="Leone sierra-léonais",
        established_year=1964,
        address="Siaka Stevens Street, Freetown, Sierra Leone",
        phone="+232 22 226501",
        email="info@bsl.gov.sl",
        contact=BankContact(address="Siaka Stevens Street, Freetown, Sierra Leone", phone="+232 22 226501", email="info@bsl.gov.sl", website="https://www.bsl.gov.sl"),
    ),
    "LR": CentralBank(
        country_code="LR", country_name="Liberia",
        name="Central Bank of Liberia", abbreviation="CBL",
        website="https://www.cbl.org.lr", swift_code=None,
        forex_regulation="liberal", currency_code="LRD", currency_name="Dollar libérien",
        established_year=1999,
        address="Corner of Warren & Carey Streets, Monrovia, Liberia",
        phone="+231 77 540 0001",
        email="info@cbl.org.lr",
        contact=BankContact(address="Warren & Carey Streets, Monrovia, Liberia", phone="+231 77 540 0001", email="info@cbl.org.lr", website="https://www.cbl.org.lr"),
    ),
    "GW": CentralBank(
        country_code="GW", country_name="Guinée-Bissau",
        name="Banque Centrale des États de l'Afrique de l'Ouest", abbreviation="BCEAO",
        website="https://www.bceao.int", swift_code=None,
        forex_regulation="moderate", currency_code="XOF", currency_name="Franc CFA BCEAO",
        address="Avenue Abdoulaye Fadiga, Dakar, Sénégal",
        phone="+221 33 839 05 00", email="bceao@bceao.int",
        contact=BankContact(address="Avenue Abdoulaye Fadiga, Dakar, Sénégal", phone="+221 33 839 05 00", email="bceao@bceao.int", website="https://www.bceao.int"),
    ),
    "CV": CentralBank(
        country_code="CV", country_name="Cap-Vert",
        name="Banco de Cabo Verde", abbreviation="BCV",
        website="https://www.bcv.cv", swift_code=None,
        forex_regulation="moderate", currency_code="CVE", currency_name="Escudo cap-verdien",
        established_year=1975,
        address="Avenida Amílcar Cabral, CP 101, Praia, Cap-Vert",
        phone="+238 260 72 00",
        email="bcv@bcv.cv",
        contact=BankContact(address="Avenida Amílcar Cabral, Praia, Cap-Vert", phone="+238 260 72 00", email="bcv@bcv.cv", website="https://www.bcv.cv"),
    ),

    # ── CENTRAL AFRICA ───────────────────────────────────────────────────────
    "CM": CentralBank(
        country_code="CM", country_name="Cameroun",
        name="Banque des États de l'Afrique Centrale", abbreviation="BEAC",
        website="https://www.beac.int", swift_code="BEACCMYA",
        forex_regulation="moderate", currency_code="XAF", currency_name="Franc CFA BEAC",
        established_year=1972, banking_act="Loi bancaire CEMAC",
        address="736, Avenue Monseigneur Vogt, BP 1917, Yaoundé, Cameroun",
        phone="+237 222 23 40 30",
        email="beac@beac.int",
        contact=BankContact(
            address="736, Avenue Monseigneur Vogt, Yaoundé, Cameroun",
            phone="+237 222 23 40 30", email="beac@beac.int",
            website="https://www.beac.int",
        ),
    ),
    "CD": CentralBank(
        country_code="CD", country_name="RD Congo",
        name="Banque Centrale du Congo", abbreviation="BCC",
        website="https://www.bcc.cd", swift_code=None,
        forex_regulation="strict", currency_code="CDF", currency_name="Franc congolais",
        established_year=1961,
        address="Boulevard Colonel Tshatshi, Kinshasa, RDC",
        phone="+243 998 603 000",
        email="info@bcc.cd",
        contact=BankContact(address="Boulevard Colonel Tshatshi, Kinshasa, RDC", phone="+243 998 603 000", email="info@bcc.cd", website="https://www.bcc.cd"),
    ),
    "CG": CentralBank(
        country_code="CG", country_name="Congo",
        name="Banque des États de l'Afrique Centrale", abbreviation="BEAC",
        website="https://www.beac.int", swift_code=None,
        forex_regulation="moderate", currency_code="XAF", currency_name="Franc CFA BEAC",
        address="736, Avenue Monseigneur Vogt, Yaoundé, Cameroun",
        phone="+237 222 23 40 30", email="beac@beac.int",
        contact=BankContact(address="Avenue Monseigneur Vogt, Yaoundé, Cameroun", phone="+237 222 23 40 30", email="beac@beac.int", website="https://www.beac.int"),
    ),
    "GA": CentralBank(
        country_code="GA", country_name="Gabon",
        name="Banque des États de l'Afrique Centrale", abbreviation="BEAC",
        website="https://www.beac.int", swift_code=None,
        forex_regulation="moderate", currency_code="XAF", currency_name="Franc CFA BEAC",
        address="736, Avenue Monseigneur Vogt, Yaoundé, Cameroun",
        phone="+237 222 23 40 30", email="beac@beac.int",
        contact=BankContact(address="Avenue Monseigneur Vogt, Yaoundé, Cameroun", phone="+237 222 23 40 30", email="beac@beac.int", website="https://www.beac.int"),
    ),
    "CF": CentralBank(
        country_code="CF", country_name="République centrafricaine",
        name="Banque des États de l'Afrique Centrale", abbreviation="BEAC",
        website="https://www.beac.int", swift_code=None,
        forex_regulation="moderate", currency_code="XAF", currency_name="Franc CFA BEAC",
        address="736, Avenue Monseigneur Vogt, Yaoundé, Cameroun",
        phone="+237 222 23 40 30", email="beac@beac.int",
        contact=BankContact(address="Avenue Monseigneur Vogt, Yaoundé, Cameroun", phone="+237 222 23 40 30", email="beac@beac.int", website="https://www.beac.int"),
    ),
    "TD": CentralBank(
        country_code="TD", country_name="Tchad",
        name="Banque des États de l'Afrique Centrale", abbreviation="BEAC",
        website="https://www.beac.int", swift_code=None,
        forex_regulation="moderate", currency_code="XAF", currency_name="Franc CFA BEAC",
        address="736, Avenue Monseigneur Vogt, Yaoundé, Cameroun",
        phone="+237 222 23 40 30", email="beac@beac.int",
        contact=BankContact(address="Avenue Monseigneur Vogt, Yaoundé, Cameroun", phone="+237 222 23 40 30", email="beac@beac.int", website="https://www.beac.int"),
    ),
    "GQ": CentralBank(
        country_code="GQ", country_name="Guinée équatoriale",
        name="Banque des États de l'Afrique Centrale", abbreviation="BEAC",
        website="https://www.beac.int", swift_code=None,
        forex_regulation="moderate", currency_code="XAF", currency_name="Franc CFA BEAC",
        address="736, Avenue Monseigneur Vogt, Yaoundé, Cameroun",
        phone="+237 222 23 40 30", email="beac@beac.int",
        contact=BankContact(address="Avenue Monseigneur Vogt, Yaoundé, Cameroun", phone="+237 222 23 40 30", email="beac@beac.int", website="https://www.beac.int"),
    ),
    "ST": CentralBank(
        country_code="ST", country_name="Sao Tomé-et-Príncipe",
        name="Banco Central de São Tomé e Príncipe", abbreviation="BCSTP",
        website="https://www.bcstp.st", swift_code=None,
        forex_regulation="moderate", currency_code="STN", currency_name="Dobra de Sao Tomé",
        established_year=1975,
        address="Praça da Independência, São Tomé, Sao Tomé-et-Príncipe",
        phone="+239 222 1397",
        email="info@bcstp.st",
        contact=BankContact(address="Praça da Independência, São Tomé", phone="+239 222 1397", email="info@bcstp.st", website="https://www.bcstp.st"),
    ),

    # ── EAST AFRICA ──────────────────────────────────────────────────────────
    "KE": CentralBank(
        country_code="KE", country_name="Kenya",
        name="Central Bank of Kenya", abbreviation="CBK",
        website="https://www.centralbank.go.ke", swift_code="CBKEKENA",
        forex_regulation="liberal", currency_code="KES", currency_name="Shilling kényan",
        established_year=1966, banking_act="Banking Act Cap 488",
        address="Haile Selassie Avenue, P.O. Box 60000, Nairobi 00200, Kenya",
        phone="+254 20 286 1000",
        email="info@centralbank.go.ke",
        contact=BankContact(
            address="Haile Selassie Avenue, Nairobi 00200, Kenya",
            phone="+254 20 286 1000", email="info@centralbank.go.ke",
            website="https://www.centralbank.go.ke", department="Banking Supervision Department",
        ),
    ),
    "ET": CentralBank(
        country_code="ET", country_name="Éthiopie",
        name="National Bank of Ethiopia", abbreviation="NBE",
        website="https://www.nbe.gov.et", swift_code=None,
        forex_regulation="strict", currency_code="ETB", currency_name="Birr éthiopien",
        established_year=1963, banking_act="Banking Business Proclamation No. 1159/2019",
        address="Gambia Street, P.O. Box 5550, Addis Ababa, Ethiopia",
        phone="+251 11 517 4000",
        email="info@nbe.gov.et",
        contact=BankContact(
            address="Gambia Street, Addis Ababa, Ethiopia",
            phone="+251 11 517 4000", email="info@nbe.gov.et",
            website="https://www.nbe.gov.et", department="Foreign Exchange Supervision",
        ),
    ),
    "TZ": CentralBank(
        country_code="TZ", country_name="Tanzanie",
        name="Bank of Tanzania", abbreviation="BoT",
        website="https://www.bot.go.tz", swift_code="BOTATZTZ",
        forex_regulation="moderate", currency_code="TZS", currency_name="Shilling tanzanien",
        established_year=1966, banking_act="Bank of Tanzania Act 2006",
        address="2, Mirambo Street, P.O. Box 2939, Dar es Salaam, Tanzania",
        phone="+255 22 223 3328",
        email="info@bot.go.tz",
        contact=BankContact(
            address="2, Mirambo Street, Dar es Salaam, Tanzania",
            phone="+255 22 223 3328", email="info@bot.go.tz",
            website="https://www.bot.go.tz",
        ),
    ),
    "UG": CentralBank(
        country_code="UG", country_name="Ouganda",
        name="Bank of Uganda", abbreviation="BoU",
        website="https://www.bou.or.ug", swift_code=None,
        forex_regulation="liberal", currency_code="UGX", currency_name="Shilling ougandais",
        established_year=1966, banking_act="Financial Institutions Act 2016",
        address="37-43, Kampala Road, P.O. Box 7120, Kampala, Uganda",
        phone="+256 41 4258441",
        email="info@bou.or.ug",
        contact=BankContact(address="37-43, Kampala Road, Kampala, Uganda", phone="+256 41 4258441", email="info@bou.or.ug", website="https://www.bou.or.ug"),
    ),
    "RW": CentralBank(
        country_code="RW", country_name="Rwanda",
        name="National Bank of Rwanda", abbreviation="BNR",
        website="https://www.bnr.rw", swift_code=None,
        forex_regulation="liberal", currency_code="RWF", currency_name="Franc rwandais",
        established_year=1964, banking_act="Banking Law N°55/2007",
        address="KN 6 Avenue, P.O. Box 531, Kigali, Rwanda",
        phone="+250 252 598301",
        email="info@bnr.rw",
        contact=BankContact(address="KN 6 Avenue, Kigali, Rwanda", phone="+250 252 598301", email="info@bnr.rw", website="https://www.bnr.rw"),
    ),
    "BI": CentralBank(
        country_code="BI", country_name="Burundi",
        name="Banque de la République du Burundi", abbreviation="BRB",
        website="https://www.brb.bi", swift_code=None,
        forex_regulation="moderate", currency_code="BIF", currency_name="Franc burundais",
        established_year=1964,
        address="Boulevard de la Liberté, BP 705, Bujumbura, Burundi",
        phone="+257 22 22 53 55",
        email="info@brb.bi",
        contact=BankContact(address="Boulevard de la Liberté, Bujumbura, Burundi", phone="+257 22 22 53 55", email="info@brb.bi", website="https://www.brb.bi"),
    ),
    "SO": CentralBank(
        country_code="SO", country_name="Somalie",
        name="Central Bank of Somalia", abbreviation="CBS",
        website="https://www.centralbank.gov.so", swift_code=None,
        forex_regulation="liberal", currency_code="SOS", currency_name="Shilling somalien",
        address="Via Roma, Mogadishu, Somalia",
        phone="+252 61 544 2222",
        email="info@centralbank.gov.so",
        contact=BankContact(address="Via Roma, Mogadishu, Somalia", phone="+252 61 544 2222", email="info@centralbank.gov.so", website="https://www.centralbank.gov.so"),
    ),
    "DJ": CentralBank(
        country_code="DJ", country_name="Djibouti",
        name="Banque Centrale de Djibouti", abbreviation="BCD",
        website="https://www.banque-centrale.dj", swift_code=None,
        forex_regulation="liberal", currency_code="DJF", currency_name="Franc djiboutien",
        established_year=1977,
        address="Place Lagarde, BP 2118, Djibouti",
        phone="+253 21 35 27 51",
        email="bcd@banque-centrale.dj",
        contact=BankContact(address="Place Lagarde, Djibouti", phone="+253 21 35 27 51", email="bcd@banque-centrale.dj", website="https://www.banque-centrale.dj"),
    ),
    "ER": CentralBank(
        country_code="ER", country_name="Érythrée",
        name="Bank of Eritrea", abbreviation="BoE",
        website=None, swift_code=None,
        forex_regulation="strict", currency_code="ERN", currency_name="Nakfa érythréen",
        address="Harnet Avenue, Asmara, Eritrea",
        phone="+291 1 123036",
        email=None,
        contact=BankContact(address="Harnet Avenue, Asmara, Eritrea", phone="+291 1 123036"),
    ),
    "SS": CentralBank(
        country_code="SS", country_name="Soudan du Sud",
        name="Bank of South Sudan", abbreviation="BSS",
        website="https://www.bankofsouthsudan.org", swift_code=None,
        forex_regulation="strict", currency_code="SSP", currency_name="Livre sud-soudanaise",
        established_year=2011,
        address="Dr. John Garang Avenue, P.O. Box 1809, Juba, South Sudan",
        phone="+211 92 261 3261",
        email="info@bankofsouthsudan.org",
        contact=BankContact(address="Dr. John Garang Avenue, Juba, South Sudan", phone="+211 92 261 3261", email="info@bankofsouthsudan.org", website="https://www.bankofsouthsudan.org"),
    ),

    # ── SOUTHERN AFRICA ──────────────────────────────────────────────────────
    "ZA": CentralBank(
        country_code="ZA", country_name="Afrique du Sud",
        name="South African Reserve Bank", abbreviation="SARB",
        website="https://www.resbank.co.za", swift_code="RESOZAJJ",
        forex_regulation="moderate", currency_code="ZAR", currency_name="Rand sud-africain",
        established_year=1921, banking_act="Banks Act No. 94 of 1990",
        address="370, Church Street, P.O. Box 427, Pretoria 0001, South Africa",
        phone="+27 12 313 3911",
        email="info@resbank.co.za",
        contact=BankContact(
            address="370, Church Street, Pretoria 0001, South Africa",
            phone="+27 12 313 3911", email="info@resbank.co.za",
            website="https://www.resbank.co.za", department="Prudential Authority",
        ),
    ),
    "AO": CentralBank(
        country_code="AO", country_name="Angola",
        name="Banco Nacional de Angola", abbreviation="BNA",
        website="https://www.bna.ao", swift_code=None,
        forex_regulation="strict", currency_code="AOA", currency_name="Kwanza angolais",
        established_year=1976, banking_act="Lei das Instituições Financeiras n°12/15",
        address="Avenida 4 de Fevereiro n°151, CP 1243, Luanda, Angola",
        phone="+244 222 679200",
        email="info@bna.ao",
        contact=BankContact(
            address="Avenida 4 de Fevereiro n°151, Luanda, Angola",
            phone="+244 222 679200", email="info@bna.ao",
            website="https://www.bna.ao", department="Departamento de Supervisão Cambial",
        ),
    ),
    "ZM": CentralBank(
        country_code="ZM", country_name="Zambie",
        name="Bank of Zambia", abbreviation="BoZ",
        website="https://www.boz.zm", swift_code=None,
        forex_regulation="moderate", currency_code="ZMW", currency_name="Kwacha zambien",
        established_year=1964, banking_act="Banking and Financial Services Act 2017",
        address="Bank Square, Cairo Road, P.O. Box 30080, Lusaka, Zambia",
        phone="+260 211 399300",
        email="info@boz.zm",
        contact=BankContact(address="Bank Square, Cairo Road, Lusaka, Zambia", phone="+260 211 399300", email="info@boz.zm", website="https://www.boz.zm"),
    ),
    "ZW": CentralBank(
        country_code="ZW", country_name="Zimbabwe",
        name="Reserve Bank of Zimbabwe", abbreviation="RBZ",
        website="https://www.rbz.co.zw", swift_code=None,
        forex_regulation="strict", currency_code="ZWL", currency_name="Dollar zimbabwéen",
        established_year=1956, banking_act="Reserve Bank of Zimbabwe Act [Chapter 22:15]",
        address="80, Samora Machel Avenue, Harare, Zimbabwe",
        phone="+263 4 703000",
        email="info@rbz.co.zw",
        contact=BankContact(address="80, Samora Machel Avenue, Harare, Zimbabwe", phone="+263 4 703000", email="info@rbz.co.zw", website="https://www.rbz.co.zw"),
    ),
    "MZ": CentralBank(
        country_code="MZ", country_name="Mozambique",
        name="Banco de Moçambique", abbreviation="BM",
        website="https://www.bancomoc.mz", swift_code=None,
        forex_regulation="moderate", currency_code="MZN", currency_name="Metical mozambicain",
        established_year=1975,
        address="Avenida 25 de Setembro, 1695, CP 423, Maputo, Mozambique",
        phone="+258 21 428151",
        email="info@bancomoc.mz",
        contact=BankContact(address="Avenida 25 de Setembro, Maputo, Mozambique", phone="+258 21 428151", email="info@bancomoc.mz", website="https://www.bancomoc.mz"),
    ),
    "MW": CentralBank(
        country_code="MW", country_name="Malawi",
        name="Reserve Bank of Malawi", abbreviation="RBM",
        website="https://www.rbm.mw", swift_code=None,
        forex_regulation="moderate", currency_code="MWK", currency_name="Kwacha malawien",
        established_year=1965,
        address="Convention Drive, P.O. Box 30063, Lilongwe 3, Malawi",
        phone="+265 1 770 600",
        email="info@rbm.mw",
        contact=BankContact(address="Convention Drive, Lilongwe, Malawi", phone="+265 1 770 600", email="info@rbm.mw", website="https://www.rbm.mw"),
    ),
    "BW": CentralBank(
        country_code="BW", country_name="Botswana",
        name="Bank of Botswana", abbreviation="BoB",
        website="https://www.bankofbotswana.bw", swift_code=None,
        forex_regulation="liberal", currency_code="BWP", currency_name="Pula botswanien",
        established_year=1975,
        address="Plot 54358, Khama Crescent, Private Bag 154, Gaborone, Botswana",
        phone="+267 360 6000",
        email="info@bankofbotswana.bw",
        contact=BankContact(address="Khama Crescent, Gaborone, Botswana", phone="+267 360 6000", email="info@bankofbotswana.bw", website="https://www.bankofbotswana.bw"),
    ),
    "NA": CentralBank(
        country_code="NA", country_name="Namibie",
        name="Bank of Namibia", abbreviation="BoN",
        website="https://www.bon.com.na", swift_code=None,
        forex_regulation="moderate", currency_code="NAD", currency_name="Dollar namibien",
        established_year=1990,
        address="71, Robert Mugabe Avenue, P.O. Box 2882, Windhoek, Namibia",
        phone="+264 61 283 5111",
        email="info@bon.com.na",
        contact=BankContact(address="71, Robert Mugabe Avenue, Windhoek, Namibia", phone="+264 61 283 5111", email="info@bon.com.na", website="https://www.bon.com.na"),
    ),
    "LS": CentralBank(
        country_code="LS", country_name="Lesotho",
        name="Central Bank of Lesotho", abbreviation="CBL",
        website="https://www.centralbank.org.ls", swift_code=None,
        forex_regulation="moderate", currency_code="LSL", currency_name="Loti lésothien",
        established_year=1978,
        address="Corner Airport and Moshoeshoe Roads, P.O. Box 1184, Maseru 100, Lesotho",
        phone="+266 22 314281",
        email="info@centralbank.org.ls",
        contact=BankContact(address="Airport and Moshoeshoe Roads, Maseru, Lesotho", phone="+266 22 314281", email="info@centralbank.org.ls", website="https://www.centralbank.org.ls"),
    ),
    "SZ": CentralBank(
        country_code="SZ", country_name="Eswatini",
        name="Central Bank of Eswatini", abbreviation="CBE",
        website="https://www.centralbank.org.sz", swift_code=None,
        forex_regulation="moderate", currency_code="SZL", currency_name="Lilangeni swazi",
        established_year=1974,
        address="Warner Street, P.O. Box 546, Mbabane H100, Eswatini",
        phone="+268 2408 2000",
        email="info@centralbank.org.sz",
        contact=BankContact(address="Warner Street, Mbabane, Eswatini", phone="+268 2408 2000", email="info@centralbank.org.sz", website="https://www.centralbank.org.sz"),
    ),
    "MG": CentralBank(
        country_code="MG", country_name="Madagascar",
        name="Banque Centrale de Madagascar", abbreviation="BCM",
        website="https://www.banky-foiben-i-madagasikara.mg", swift_code=None,
        forex_regulation="moderate", currency_code="MGA", currency_name="Ariary malgache",
        established_year=1973,
        address="Rue de la Révolution Socialiste, BP 550, Antananarivo 101, Madagascar",
        phone="+261 20 22 294 19",
        email="info@banky-foiben-i-madagasikara.mg",
        contact=BankContact(address="Rue de la Révolution Socialiste, Antananarivo, Madagascar", phone="+261 20 22 294 19", email="info@banky-foiben-i-madagasikara.mg", website="https://www.banky-foiben-i-madagasikara.mg"),
    ),
    "MU": CentralBank(
        country_code="MU", country_name="Maurice",
        name="Bank of Mauritius", abbreviation="BoM",
        website="https://www.bom.mu", swift_code=None,
        forex_regulation="liberal", currency_code="MUR", currency_name="Roupie mauricienne",
        established_year=1967, banking_act="Banking Act 2004",
        address="Sir William Newton Street, Port Louis, Mauritius",
        phone="+230 202 3800",
        email="info@bom.mu",
        contact=BankContact(
            address="Sir William Newton Street, Port Louis, Mauritius",
            phone="+230 202 3800", email="info@bom.mu",
            website="https://www.bom.mu",
        ),
    ),
    "SC": CentralBank(
        country_code="SC", country_name="Seychelles",
        name="Central Bank of Seychelles", abbreviation="CBS",
        website="https://www.cbs.sc", swift_code=None,
        forex_regulation="liberal", currency_code="SCR", currency_name="Roupie seychelloise",
        established_year=1983,
        address="Independence Avenue, P.O. Box 701, Victoria, Seychelles",
        phone="+248 428 2000",
        email="info@cbs.sc",
        contact=BankContact(address="Independence Avenue, Victoria, Seychelles", phone="+248 428 2000", email="info@cbs.sc", website="https://www.cbs.sc"),
    ),
    "KM": CentralBank(
        country_code="KM", country_name="Comores",
        name="Banque Centrale des Comores", abbreviation="BCC",
        website="https://www.banque-comores.km", swift_code=None,
        forex_regulation="moderate", currency_code="KMF", currency_name="Franc comorien",
        established_year=1981,
        address="Place de France, BP 405, Moroni, Comores",
        phone="+269 773 1002",
        email="info@banque-comores.km",
        contact=BankContact(address="Place de France, Moroni, Comores", phone="+269 773 1002", email="info@banque-comores.km", website="https://www.banque-comores.km"),
    ),
}

# ---------------------------------------------------------------------------
# COMMERCIAL BANKS – Phase-1 & extended coverage (22 countries)
# ---------------------------------------------------------------------------

COMMERCIAL_BANKS: Dict[str, List[CommercialBank]] = {
    "MA": [
        CommercialBank(
            name="Attijariwafa Bank", abbreviation="AWB", country_code="MA",
            swift_code="BCMAMAMC", trade_finance=True,
            correspondent_banks=["BNP_PARIBAS", "SOCIETE_GENERALE", "CREDIT_AGRICOLE"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex", "trade_loans"],
            website="https://www.attijariwafabank.com",
            address="2, Boulevard Moulay Youssef, Casablanca 20000, Maroc",
            phone="+212 522 29 88 88",
            email="corporatebanking@attijariwafabank.com",
            license_type="Banque universelle",
            contact=BankContact(address="2, Bd Moulay Youssef, Casablanca", phone="+212 522 29 88 88", email="corporatebanking@attijariwafabank.com", website="https://www.attijariwafabank.com", department="Trade Finance & Entreprises"),
        ),
        CommercialBank(
            name="Banque Centrale Populaire", abbreviation="BCP", country_code="MA",
            swift_code="BCPPMAMR", trade_finance=True,
            correspondent_banks=["CREDIT_MUTUEL", "NATIXIS"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.gbp.ma",
            address="101, Boulevard Mohammed Zerktouni, Casablanca, Maroc",
            phone="+212 522 20 25 00",
            email="corporate@gbp.ma",
            license_type="Banque universelle",
            contact=BankContact(address="101, Bd Mohammed Zerktouni, Casablanca", phone="+212 522 20 25 00", email="corporate@gbp.ma", website="https://www.gbp.ma", department="Banque des Entreprises"),
        ),
        CommercialBank(
            name="BMCE Bank of Africa", abbreviation="BMCE", country_code="MA",
            swift_code="BCMOMAMR", trade_finance=True,
            correspondent_banks=["COMMERZBANK", "STANDARD_CHARTERED"],
            services=["LC", "bank_guarantee", "forex", "trade_loans", "supply_chain_finance"],
            website="https://www.bankofafrica.ma",
            address="140, Avenue Hassan II, Casablanca 20000, Maroc",
            phone="+212 522 49 80 00",
            email="tradeservices@bankofafrica.ma",
            license_type="Banque universelle",
            contact=BankContact(address="140, Avenue Hassan II, Casablanca", phone="+212 522 49 80 00", email="tradeservices@bankofafrica.ma", website="https://www.bankofafrica.ma", department="Trade Services"),
        ),
        CommercialBank(
            name="Société Générale Maroc", abbreviation="SGM", country_code="MA",
            swift_code="SGMBMAMC", trade_finance=True,
            correspondent_banks=["SOCIETE_GENERALE"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.societegenerale.ma",
            address="55, Boulevard Abdelmoumen, Casablanca 20100, Maroc",
            phone="+212 522 43 88 88",
            email="pme@societegenerale.ma",
            license_type="Filiale internationale",
            contact=BankContact(address="55, Bd Abdelmoumen, Casablanca", phone="+212 522 43 88 88", email="pme@societegenerale.ma", website="https://www.societegenerale.ma"),
        ),
    ],
    "DZ": [
        CommercialBank(
            name="Banque Extérieure d'Algérie", abbreviation="BEA", country_code="DZ",
            swift_code="BEAADZAL", trade_finance=True,
            correspondent_banks=["BNP_PARIBAS", "SOCIETE_GENERALE"],
            services=["LC", "bank_guarantee", "forex", "trade_loans"],
            website="https://www.bea.dz",
            address="11, Boulevard Colonel Amirouche, Alger 16000, Algérie",
            phone="+213 21 71 42 40",
            email="commerce.exterieur@bea.dz",
            license_type="Banque publique spécialisée",
            contact=BankContact(address="11, Bd Colonel Amirouche, Alger", phone="+213 21 71 42 40", email="commerce.exterieur@bea.dz", website="https://www.bea.dz", department="Direction du Commerce Extérieur"),
        ),
        CommercialBank(
            name="Banque Nationale d'Algérie", abbreviation="BNA", country_code="DZ",
            swift_code="BNAADZAL", trade_finance=True,
            correspondent_banks=["CREDIT_AGRICOLE"],
            services=["LC", "documentary_collection", "bank_guarantee"],
            website="https://www.bna.dz",
            address="8, Boulevard Ernesto Che Guevara, Alger, Algérie",
            phone="+213 21 71 10 18",
            email="dri@bna.dz",
            license_type="Banque publique",
            contact=BankContact(address="8, Bd Ernesto Che Guevara, Alger", phone="+213 21 71 10 18", email="dri@bna.dz", website="https://www.bna.dz"),
        ),
        CommercialBank(
            name="Crédit Populaire d'Algérie", abbreviation="CPA", country_code="DZ",
            swift_code=None, trade_finance=True,
            correspondent_banks=["NATIXIS"],
            services=["LC", "bank_guarantee", "forex"],
            website="https://www.cpa-bank.dz",
            address="2, Boulevard Colonel Amirouche, Alger, Algérie",
            phone="+213 21 74 47 38",
            email="cpa@cpa-bank.dz",
            license_type="Banque publique",
            contact=BankContact(address="2, Bd Colonel Amirouche, Alger", phone="+213 21 74 47 38", email="cpa@cpa-bank.dz", website="https://www.cpa-bank.dz"),
        ),
    ],
    "TN": [
        CommercialBank(
            name="Banque Internationale Arabe de Tunisie", abbreviation="BIAT",
            country_code="TN", swift_code="BIATTNTT", trade_finance=True,
            correspondent_banks=["SOCIETE_GENERALE", "BNP_PARIBAS"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.biat.com.tn",
            address="70-72, Avenue Habib Bourguiba, Tunis 1000, Tunisie",
            phone="+216 71 340 733",
            email="corporate@biat.com.tn",
            license_type="Banque universelle",
            contact=BankContact(address="70-72, Avenue Habib Bourguiba, Tunis", phone="+216 71 340 733", email="corporate@biat.com.tn", website="https://www.biat.com.tn", department="Banque des Entreprises"),
        ),
        CommercialBank(
            name="Société Tunisienne de Banque", abbreviation="STB",
            country_code="TN", swift_code="STBKTNTT", trade_finance=True,
            correspondent_banks=["BNP_PARIBAS"],
            services=["LC", "documentary_collection", "bank_guarantee"],
            website="https://www.stb.com.tn",
            address="Rue Hédi Nouira, Tunis, Tunisie",
            phone="+216 71 340 477",
            email="stb@stb.com.tn",
            license_type="Banque publique",
            contact=BankContact(address="Rue Hédi Nouira, Tunis", phone="+216 71 340 477", email="stb@stb.com.tn", website="https://www.stb.com.tn"),
        ),
    ],
    "EG": [
        CommercialBank(
            name="National Bank of Egypt", abbreviation="NBE", country_code="EG",
            swift_code="NBEGEGCX", trade_finance=True,
            correspondent_banks=["CITIBANK", "JP_MORGAN", "COMMERZBANK"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex", "export_finance"],
            website="https://www.nbe.com.eg",
            address="1187, Corniche El Nil, Cairo 11511, Egypt",
            phone="+202 25746001",
            email="trade.services@nbe.com.eg",
            license_type="Banque publique",
            contact=BankContact(address="1187, Corniche El Nil, Cairo", phone="+202 25746001", email="trade.services@nbe.com.eg", website="https://www.nbe.com.eg", department="Trade Finance Division"),
        ),
        CommercialBank(
            name="Banque Misr", abbreviation="BM", country_code="EG",
            swift_code="BMISEGCX", trade_finance=True,
            correspondent_banks=["BNP_PARIBAS", "SOCIETE_GENERALE"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.banquemisr.com",
            address="151, Mohammed Farid Street, Cairo, Egypt",
            phone="+202 23928892",
            email="corporate@banquemisr.com",
            license_type="Banque publique",
            contact=BankContact(address="151, Mohammed Farid Street, Cairo", phone="+202 23928892", email="corporate@banquemisr.com", website="https://www.banquemisr.com"),
        ),
        CommercialBank(
            name="Commercial International Bank", abbreviation="CIB", country_code="EG",
            swift_code="CIBEEGCX", trade_finance=True,
            correspondent_banks=["STANDARD_CHARTERED", "CITIBANK"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex", "trade_loans"],
            website="https://www.cibeg.com",
            address="Nile Tower, 21-23 Charles de Gaulle Street, Giza, Egypt",
            phone="+202 38381000",
            email="trade@cibeg.com",
            license_type="Banque privée",
            contact=BankContact(address="Nile Tower, Charles de Gaulle Street, Giza", phone="+202 38381000", email="trade@cibeg.com", website="https://www.cibeg.com", department="Trade Finance"),
        ),
    ],
    "NG": [
        CommercialBank(
            name="Zenith Bank", abbreviation="ZENITH", country_code="NG",
            swift_code="ZEIBNGLA", trade_finance=True,
            correspondent_banks=["CITIBANK", "STANDARD_CHARTERED", "JP_MORGAN"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex", "export_finance"],
            website="https://www.zenithbank.com",
            address="Plot 84, Ajose Adeogun Street, Victoria Island, Lagos 101241, Nigeria",
            phone="+234 1 278 7000",
            email="tradeservices@zenithbank.com",
            license_type="Banque universelle",
            contact=BankContact(address="Plot 84, Ajose Adeogun Street, Victoria Island, Lagos", phone="+234 1 278 7000", email="tradeservices@zenithbank.com", website="https://www.zenithbank.com", department="Trade Finance"),
        ),
        CommercialBank(
            name="United Bank for Africa", abbreviation="UBA", country_code="NG",
            swift_code="UNAFNGLA", trade_finance=True,
            correspondent_banks=["CITIBANK", "BNP_PARIBAS"],
            services=["LC", "bank_guarantee", "forex", "trade_loans"],
            website="https://www.ubagroup.com",
            address="57, Marina, Lagos Island, Lagos, Nigeria",
            phone="+234 1 280 8822",
            email="trade@ubagroup.com",
            license_type="Banque universelle",
            contact=BankContact(address="57, Marina, Lagos Island, Lagos", phone="+234 1 280 8822", email="trade@ubagroup.com", website="https://www.ubagroup.com", department="Global Trade Finance"),
        ),
        CommercialBank(
            name="Guaranty Trust Bank", abbreviation="GTBank", country_code="NG",
            swift_code="GTBINGLA", trade_finance=True,
            correspondent_banks=["STANDARD_CHARTERED", "COMMERZBANK"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.gtbank.com",
            address="635, Akin Adesola Street, Victoria Island, Lagos, Nigeria",
            phone="+234 1 448 0000",
            email="trade@gtbank.com",
            license_type="Banque universelle",
            contact=BankContact(address="635, Akin Adesola Street, Victoria Island, Lagos", phone="+234 1 448 0000", email="trade@gtbank.com", website="https://www.gtbank.com"),
        ),
        CommercialBank(
            name="First Bank of Nigeria", abbreviation="FBN", country_code="NG",
            swift_code="FBNINGLA", trade_finance=True,
            correspondent_banks=["CITIBANK", "BARCLAYS"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex", "export_finance"],
            website="https://www.firstbanknigeria.com",
            address="35, Samuel Asabia House, Marina, Lagos, Nigeria",
            phone="+234 1 9050000",
            email="tradeservices@firstbanknigeria.com",
            license_type="Banque universelle",
            contact=BankContact(address="35, Samuel Asabia House, Marina, Lagos", phone="+234 1 9050000", email="tradeservices@firstbanknigeria.com", website="https://www.firstbanknigeria.com"),
        ),
    ],
    "GH": [
        CommercialBank(
            name="Ghana Commercial Bank", abbreviation="GCB", country_code="GH",
            swift_code="GHCBGHAC", trade_finance=True,
            correspondent_banks=["CITIBANK", "STANDARD_CHARTERED"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.gcbbank.com.gh",
            address="Thorpe Road, P.O. Box 134, Accra, Ghana",
            phone="+233 30 265 5401",
            email="trade@gcbbank.com.gh",
            license_type="Banque publique",
            contact=BankContact(address="Thorpe Road, Accra, Ghana", phone="+233 30 265 5401", email="trade@gcbbank.com.gh", website="https://www.gcbbank.com.gh"),
        ),
        CommercialBank(
            name="Ecobank Ghana", abbreviation="ECOBANK-GH", country_code="GH",
            swift_code="ECOCGHAC", trade_finance=True,
            correspondent_banks=["CITIBANK", "SOCIETE_GENERALE"],
            services=["LC", "bank_guarantee", "forex", "trade_loans"],
            website="https://ecobank.com/gh",
            address="19, Seventh Avenue, Ridge West, Accra, Ghana",
            phone="+233 30 268 1100",
            email="tradeghana@ecobank.com",
            license_type="Filiale panafricaine",
            contact=BankContact(address="19, Seventh Avenue, Ridge West, Accra", phone="+233 30 268 1100", email="tradeghana@ecobank.com", website="https://ecobank.com/gh"),
        ),
    ],
    "CI": [
        CommercialBank(
            name="Société Générale Côte d'Ivoire", abbreviation="SGCI", country_code="CI",
            swift_code="SGBFCIAB", trade_finance=True,
            correspondent_banks=["SOCIETE_GENERALE"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.societegenerale.ci",
            address="5-7, Avenue Joseph Anoma, 01 BP 1355, Abidjan 01, Côte d'Ivoire",
            phone="+225 27 20 20 12 34",
            email="trade.ci@societegenerale.ci",
            license_type="Filiale internationale",
            contact=BankContact(address="5-7, Avenue Joseph Anoma, Abidjan", phone="+225 27 20 20 12 34", email="trade.ci@societegenerale.ci", website="https://www.societegenerale.ci"),
        ),
        CommercialBank(
            name="Ecobank Côte d'Ivoire", abbreviation="ECOBANK-CI", country_code="CI",
            swift_code="ECOCCIAB", trade_finance=True,
            correspondent_banks=["CITIBANK"],
            services=["LC", "bank_guarantee", "forex"],
            website="https://ecobank.com/ci",
            address="Immeuble Alliance, Avenue Terrasson de Fougères, Abidjan, Côte d'Ivoire",
            phone="+225 27 20 31 92 00",
            email="tradeci@ecobank.com",
            license_type="Filiale panafricaine",
            contact=BankContact(address="Avenue Terrasson de Fougères, Abidjan", phone="+225 27 20 31 92 00", email="tradeci@ecobank.com", website="https://ecobank.com/ci"),
        ),
    ],
    "SN": [
        CommercialBank(
            name="Ecobank Sénégal", abbreviation="ECOBANK-SN", country_code="SN",
            swift_code="ECOCSNDA", trade_finance=True,
            correspondent_banks=["CITIBANK"],
            services=["LC", "bank_guarantee", "forex"],
            website="https://ecobank.com/sn",
            address="Place de l'Indépendance, Dakar, Sénégal",
            phone="+221 33 849 00 00",
            email="tradesn@ecobank.com",
            license_type="Filiale panafricaine",
            contact=BankContact(address="Place de l'Indépendance, Dakar", phone="+221 33 849 00 00", email="tradesn@ecobank.com", website="https://ecobank.com/sn"),
        ),
        CommercialBank(
            name="Société Générale Sénégal", abbreviation="SGS", country_code="SN",
            swift_code="SGSNSNDA", trade_finance=True,
            correspondent_banks=["SOCIETE_GENERALE"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.societegenerale.sn",
            address="19, Avenue du Président Léopold Sédar Senghor, Dakar, Sénégal",
            phone="+221 33 839 55 00",
            email="trade.sn@societegenerale.sn",
            license_type="Filiale internationale",
            contact=BankContact(address="19, Avenue du Président L.S. Senghor, Dakar", phone="+221 33 839 55 00", email="trade.sn@societegenerale.sn", website="https://www.societegenerale.sn"),
        ),
    ],
    "KE": [
        CommercialBank(
            name="Kenya Commercial Bank", abbreviation="KCB", country_code="KE",
            swift_code="KCBLKENA", trade_finance=True,
            correspondent_banks=["CITIBANK", "STANDARD_CHARTERED"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex", "trade_loans"],
            website="https://ke.kcbgroup.com",
            address="Kencom House, Moi Avenue, P.O. Box 48400, Nairobi 00100, Kenya",
            phone="+254 20 327 0000",
            email="tradeservices@kcbgroup.com",
            license_type="Banque universelle",
            contact=BankContact(address="Kencom House, Moi Avenue, Nairobi", phone="+254 20 327 0000", email="tradeservices@kcbgroup.com", website="https://ke.kcbgroup.com", department="Trade Finance"),
        ),
        CommercialBank(
            name="Equity Bank Kenya", abbreviation="EQUITY", country_code="KE",
            swift_code="EQBLKENA", trade_finance=True,
            correspondent_banks=["CITIBANK"],
            services=["LC", "bank_guarantee", "forex", "mobile_banking"],
            website="https://equitybankgroup.com",
            address="Equity Centre, Hospital Road, Upper Hill, Nairobi, Kenya",
            phone="+254 763 000 000",
            email="trade@equitybankgroup.com",
            license_type="Banque universelle",
            contact=BankContact(address="Equity Centre, Hospital Road, Nairobi", phone="+254 763 000 000", email="trade@equitybankgroup.com", website="https://equitybankgroup.com"),
        ),
        CommercialBank(
            name="Standard Chartered Kenya", abbreviation="SCB-KE", country_code="KE",
            swift_code="SCBLKENA", trade_finance=True,
            correspondent_banks=["STANDARD_CHARTERED"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex", "export_finance"],
            website="https://www.sc.com/ke",
            address="48, Westlands Road, Nairobi, Kenya",
            phone="+254 20 329 3900",
            email="ke.tradefinance@sc.com",
            license_type="Filiale internationale",
            contact=BankContact(address="48, Westlands Road, Nairobi", phone="+254 20 329 3900", email="ke.tradefinance@sc.com", website="https://www.sc.com/ke", department="Trade Finance"),
        ),
    ],
    "ET": [
        CommercialBank(
            name="Commercial Bank of Ethiopia", abbreviation="CBE", country_code="ET",
            swift_code="CBETETAA", trade_finance=True,
            correspondent_banks=["CITIBANK", "COMMERZBANK"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.combanketh.et",
            address="Gambia Street, P.O. Box 255, Addis Ababa, Ethiopia",
            phone="+251 11 551 5004",
            email="trade@combanketh.et",
            license_type="Banque publique",
            contact=BankContact(address="Gambia Street, Addis Ababa", phone="+251 11 551 5004", email="trade@combanketh.et", website="https://www.combanketh.et", department="Trade Finance & Foreign Operations"),
        ),
        CommercialBank(
            name="Dashen Bank", abbreviation="DASHEN", country_code="ET",
            swift_code=None, trade_finance=True,
            correspondent_banks=["COMMERZBANK"],
            services=["LC", "bank_guarantee", "forex"],
            website="https://www.dashenbank.com",
            address="Kazanchis, Addis Ababa, Ethiopia",
            phone="+251 11 557 0701",
            email="info@dashenbank.com",
            license_type="Banque privée",
            contact=BankContact(address="Kazanchis, Addis Ababa", phone="+251 11 557 0701", email="info@dashenbank.com", website="https://www.dashenbank.com"),
        ),
    ],
    "TZ": [
        CommercialBank(
            name="CRDB Bank", abbreviation="CRDB", country_code="TZ",
            swift_code="CORUTZTZ", trade_finance=True,
            correspondent_banks=["STANDARD_CHARTERED", "COMMERZBANK"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.crdbbank.co.tz",
            address="CRDB Bank Tower, Azikiwe Street, P.O. Box 268, Dar es Salaam, Tanzania",
            phone="+255 22 211 7441",
            email="trade@crdbbank.co.tz",
            license_type="Banque universelle",
            contact=BankContact(address="CRDB Bank Tower, Azikiwe Street, Dar es Salaam", phone="+255 22 211 7441", email="trade@crdbbank.co.tz", website="https://www.crdbbank.co.tz"),
        ),
        CommercialBank(
            name="NMB Bank Tanzania", abbreviation="NMB", country_code="TZ",
            swift_code="NMBCTZTZ", trade_finance=True,
            correspondent_banks=["CITIBANK"],
            services=["LC", "bank_guarantee", "forex"],
            website="https://www.nmbtz.com",
            address="Samora Avenue / Azikiwe Street, Dar es Salaam, Tanzania",
            phone="+255 22 219 2000",
            email="tradeservices@nmbtz.com",
            license_type="Banque privée",
            contact=BankContact(address="Samora Avenue, Dar es Salaam", phone="+255 22 219 2000", email="tradeservices@nmbtz.com", website="https://www.nmbtz.com"),
        ),
    ],
    "ZA": [
        CommercialBank(
            name="Standard Bank South Africa", abbreviation="SBSA", country_code="ZA",
            swift_code="SBZAZAJJ", trade_finance=True,
            correspondent_banks=["CITIBANK", "JP_MORGAN", "COMMERZBANK"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex", "export_finance", "supply_chain_finance"],
            website="https://www.standardbank.co.za",
            address="5, Simmonds Street, Johannesburg 2001, South Africa",
            phone="+27 11 636 9111",
            email="trade.finance@standardbank.co.za",
            license_type="Banque universelle",
            contact=BankContact(address="5, Simmonds Street, Johannesburg", phone="+27 11 636 9111", email="trade.finance@standardbank.co.za", website="https://www.standardbank.co.za", department="Global Markets – Trade Finance"),
        ),
        CommercialBank(
            name="FirstRand Bank (FNB)", abbreviation="FNB", country_code="ZA",
            swift_code="FIRNZAJJ", trade_finance=True,
            correspondent_banks=["BARCLAYS", "CITIBANK"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.fnb.co.za",
            address="4, First Place, Bank City, Johannesburg 2001, South Africa",
            phone="+27 87 575 9404",
            email="trade@fnb.co.za",
            license_type="Banque universelle",
            contact=BankContact(address="4, First Place, Bank City, Johannesburg", phone="+27 87 575 9404", email="trade@fnb.co.za", website="https://www.fnb.co.za"),
        ),
        CommercialBank(
            name="Absa Bank South Africa", abbreviation="ABSA", country_code="ZA",
            swift_code="ABSAZAJJ", trade_finance=True,
            correspondent_banks=["BARCLAYS", "STANDARD_CHARTERED"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex", "export_finance"],
            website="https://www.absa.co.za",
            address="Absa Towers, 15, Troye Street, Johannesburg 2001, South Africa",
            phone="+27 11 350 4000",
            email="trade.finance@absa.co.za",
            license_type="Banque universelle",
            contact=BankContact(address="Absa Towers, 15, Troye Street, Johannesburg", phone="+27 11 350 4000", email="trade.finance@absa.co.za", website="https://www.absa.co.za", department="Transaction Banking"),
        ),
        CommercialBank(
            name="Nedbank", abbreviation="NEDBANK", country_code="ZA",
            swift_code="NEDSZAJJ", trade_finance=True,
            correspondent_banks=["CITIBANK"],
            services=["LC", "bank_guarantee", "forex"],
            website="https://www.nedbank.co.za",
            address="135, Rivonia Road, Sandown, Sandton 2196, South Africa",
            phone="+27 11 294 4444",
            email="trade@nedbank.co.za",
            license_type="Banque universelle",
            contact=BankContact(address="135, Rivonia Road, Sandton, Johannesburg", phone="+27 11 294 4444", email="trade@nedbank.co.za", website="https://www.nedbank.co.za"),
        ),
    ],
    "AO": [
        CommercialBank(
            name="Banco Angolano de Investimentos", abbreviation="BAI", country_code="AO",
            swift_code="BAIEAOLU", trade_finance=True,
            correspondent_banks=["CITIBANK", "COMMERZBANK"],
            services=["LC", "bank_guarantee", "forex"],
            website="https://www.bancobai.ao",
            address="Rua Rainha Ginga, 83, Luanda, Angola",
            phone="+244 222 693300",
            email="trade@bancobai.ao",
            license_type="Banque privée",
            contact=BankContact(address="Rua Rainha Ginga, 83, Luanda", phone="+244 222 693300", email="trade@bancobai.ao", website="https://www.bancobai.ao"),
        ),
        CommercialBank(
            name="Banco BIC Angola", abbreviation="BIC", country_code="AO",
            swift_code=None, trade_finance=True,
            correspondent_banks=[],
            services=["LC", "forex"],
            website="https://www.bancobic.ao",
            address="Rua Marechal Broz Tito, 35, Luanda, Angola",
            phone="+244 222 633300",
            email="corporate@bancobic.ao",
            license_type="Banque privée",
            contact=BankContact(address="Rua Marechal Broz Tito, 35, Luanda", phone="+244 222 633300", email="corporate@bancobic.ao", website="https://www.bancobic.ao"),
        ),
    ],
    "ZM": [
        CommercialBank(
            name="Zambia National Commercial Bank", abbreviation="ZANACO", country_code="ZM",
            swift_code="ZANZZMLU", trade_finance=True,
            correspondent_banks=["STANDARD_CHARTERED"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.zanaco.co.zm",
            address="Cairo Road, P.O. Box 33611, Lusaka, Zambia",
            phone="+260 211 370 100",
            email="trade@zanaco.co.zm",
            license_type="Banque publique",
            contact=BankContact(address="Cairo Road, Lusaka", phone="+260 211 370 100", email="trade@zanaco.co.zm", website="https://www.zanaco.co.zm"),
        ),
        CommercialBank(
            name="Standard Chartered Zambia", abbreviation="SCB-ZM", country_code="ZM",
            swift_code="SCBLZMLU", trade_finance=True,
            correspondent_banks=["STANDARD_CHARTERED"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex", "trade_loans"],
            website="https://www.sc.com/zm",
            address="Lusaka Square, Cairo Road, Lusaka, Zambia",
            phone="+260 211 370 300",
            email="zm.tradefinance@sc.com",
            license_type="Filiale internationale",
            contact=BankContact(address="Lusaka Square, Cairo Road, Lusaka", phone="+260 211 370 300", email="zm.tradefinance@sc.com", website="https://www.sc.com/zm"),
        ),
    ],
    "RW": [
        CommercialBank(
            name="Bank of Kigali", abbreviation="BK", country_code="RW",
            swift_code="BKIGRWRW", trade_finance=True,
            correspondent_banks=["CITIBANK", "STANDARD_CHARTERED"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.bk.rw",
            address="Plot 6140, Boulevard de la Révolution, Kigali, Rwanda",
            phone="+250 788 143 000",
            email="trade@bk.rw",
            license_type="Banque universelle",
            contact=BankContact(address="Boulevard de la Révolution, Kigali", phone="+250 788 143 000", email="trade@bk.rw", website="https://www.bk.rw", department="Corporate Banking & Trade Finance"),
        ),
        CommercialBank(
            name="Equity Bank Rwanda", abbreviation="EQUITY-RW", country_code="RW",
            swift_code=None, trade_finance=True,
            correspondent_banks=["CITIBANK"],
            services=["LC", "bank_guarantee", "forex"],
            website="https://equitybankgroup.com/rw",
            address="Kigali City Tower, Kigali, Rwanda",
            phone="+250 788 177 000",
            email="trade.rw@equitybankgroup.com",
            license_type="Filiale panafricaine",
            contact=BankContact(address="Kigali City Tower, Kigali", phone="+250 788 177 000", email="trade.rw@equitybankgroup.com", website="https://equitybankgroup.com/rw"),
        ),
    ],
    "CM": [
        CommercialBank(
            name="Afriland First Bank", abbreviation="AFB", country_code="CM",
            swift_code="AFBICMCX", trade_finance=True,
            correspondent_banks=["BNP_PARIBAS", "SOCIETE_GENERALE"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.afrilandfirstbank.com",
            address="1089, Place de l'Indépendance, BP 11834, Yaoundé, Cameroun",
            phone="+237 222 23 28 22",
            email="commerce.exterieur@afrilandfirstbank.com",
            license_type="Banque universelle",
            contact=BankContact(address="Place de l'Indépendance, Yaoundé, Cameroun", phone="+237 222 23 28 22", email="commerce.exterieur@afrilandfirstbank.com", website="https://www.afrilandfirstbank.com", department="Commerce International"),
        ),
        CommercialBank(
            name="Société Générale Cameroun", abbreviation="SGC", country_code="CM",
            swift_code="SGCMCMCX", trade_finance=True,
            correspondent_banks=["SOCIETE_GENERALE"],
            services=["LC", "bank_guarantee", "forex", "trade_loans"],
            website="https://www.societegenerale.cm",
            address="BP 4042, Douala, Cameroun",
            phone="+237 233 43 04 04",
            email="trade.cm@societegenerale.cm",
            license_type="Filiale internationale",
            contact=BankContact(address="Douala, Cameroun", phone="+237 233 43 04 04", email="trade.cm@societegenerale.cm", website="https://www.societegenerale.cm"),
        ),
    ],
    "UG": [
        CommercialBank(
            name="Stanbic Bank Uganda", abbreviation="SBU", country_code="UG",
            swift_code="SBICUGKX", trade_finance=True,
            correspondent_banks=["STANDARD_CHARTERED", "CITIBANK"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex", "trade_loans"],
            website="https://www.stanbicbank.co.ug",
            address="Crested Towers, Hannington Road, Kampala, Uganda",
            phone="+256 31 722 4000",
            email="trade.ug@stanbicbank.co.ug",
            license_type="Filiale internationale",
            contact=BankContact(address="Crested Towers, Hannington Road, Kampala", phone="+256 31 722 4000", email="trade.ug@stanbicbank.co.ug", website="https://www.stanbicbank.co.ug", department="Trade Finance"),
        ),
    ],
    "MU": [
        CommercialBank(
            name="MCB Group", abbreviation="MCB", country_code="MU",
            swift_code="MCBLMUMU", trade_finance=True,
            correspondent_banks=["CITIBANK", "BNP_PARIBAS", "STANDARD_CHARTERED"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex", "trade_loans", "export_finance"],
            website="https://www.mcbgroup.com",
            address="9-15, Sir William Newton Street, Port Louis 11328, Mauritius",
            phone="+230 202 5000",
            email="trade@mcb.mu",
            license_type="Banque universelle",
            contact=BankContact(address="9-15, Sir William Newton Street, Port Louis", phone="+230 202 5000", email="trade@mcb.mu", website="https://www.mcbgroup.com", department="Global Trade Finance"),
        ),
        CommercialBank(
            name="SBM Bank Mauritius", abbreviation="SBM", country_code="MU",
            swift_code="STCBMUMU", trade_finance=True,
            correspondent_banks=["COMMERZBANK", "CITIBANK"],
            services=["LC", "documentary_collection", "bank_guarantee", "forex"],
            website="https://www.sbmgroup.mu",
            address="SBM Tower, 1, Queen Elizabeth II Avenue, Port Louis, Mauritius",
            phone="+230 202 1111",
            email="trade@sbmgroup.mu",
            license_type="Banque universelle",
            contact=BankContact(address="SBM Tower, Queen Elizabeth II Avenue, Port Louis", phone="+230 202 1111", email="trade@sbmgroup.mu", website="https://www.sbmgroup.mu"),
        ),
    ],
}

# ---------------------------------------------------------------------------
# REGIONAL / DEVELOPMENT BANKS
# ---------------------------------------------------------------------------

REGIONAL_BANKS: List[RegionalBank] = [
    RegionalBank(
        name="African Development Bank", abbreviation="AfDB",
        region="Pan-African", headquarters="Abidjan, Côte d'Ivoire",
        website="https://www.afdb.org",
        member_countries=list(CENTRAL_BANKS.keys()),
        focus_areas=["infrastructure", "agriculture", "industry", "trade_finance"],
        phone="+225 27 20 26 29 00",
        email="afdb@afdb.org",
        contact=BankContact(
            address="Avenue Joseph Anoma, 01 BP 1387, Abidjan 01, Côte d'Ivoire",
            phone="+225 27 20 26 29 00", email="afdb@afdb.org",
            website="https://www.afdb.org", department="Private Sector & Trade Finance",
        ),
    ),
    RegionalBank(
        name="Afreximbank – African Export-Import Bank", abbreviation="Afreximbank",
        region="Pan-African", headquarters="Le Caire, Égypte",
        website="https://www.afreximbank.com",
        member_countries=list(CENTRAL_BANKS.keys()),
        focus_areas=["export_finance", "trade_finance", "project_finance", "LC_confirmation"],
        phone="+20 2 24564100",
        email="info@afreximbank.com",
        contact=BankContact(
            address="72, Jumhuriya Street, P.O. Box 613, Cairo, Egypt",
            phone="+20 2 24564100", email="info@afreximbank.com",
            website="https://www.afreximbank.com", department="Trade Finance Division",
        ),
    ),
    RegionalBank(
        name="Banque Ouest Africaine de Développement", abbreviation="BOAD",
        region="West Africa (UEMOA)", headquarters="Lomé, Togo",
        website="https://www.boad.org",
        member_countries=["BJ", "BF", "CI", "GW", "ML", "NE", "SN", "TG"],
        focus_areas=["infrastructure", "agriculture", "SME_finance"],
        phone="+228 22 21 59 06",
        email="boad@boad.org",
        contact=BankContact(address="68, Avenue de la Libération, Lomé, Togo", phone="+228 22 21 59 06", email="boad@boad.org", website="https://www.boad.org"),
    ),
    RegionalBank(
        name="East African Development Bank", abbreviation="EADB",
        region="East Africa (EAC)", headquarters="Kampala, Ouganda",
        website="https://www.eadb.org",
        member_countries=["KE", "TZ", "UG", "RW", "SS"],
        focus_areas=["infrastructure", "industry", "SME_finance"],
        phone="+256 41 265 0551",
        email="eadb@eadb.org",
        contact=BankContact(address="Plot 4, Nile Avenue, Kampala, Uganda", phone="+256 41 265 0551", email="eadb@eadb.org", website="https://www.eadb.org"),
    ),
    RegionalBank(
        name="Development Bank of Southern Africa", abbreviation="DBSA",
        region="Southern Africa (SADC)", headquarters="Midrand, Afrique du Sud",
        website="https://www.dbsa.org",
        member_countries=["ZA", "BW", "LS", "NA", "SZ", "MZ", "ZM", "ZW", "MG", "MU"],
        focus_areas=["infrastructure", "energy", "water", "transport"],
        phone="+27 11 313 3911",
        email="info@dbsa.org",
        contact=BankContact(address="1258 Lever Road, Headway Hill, Midrand 1685, South Africa", phone="+27 11 313 3911", email="info@dbsa.org", website="https://www.dbsa.org"),
    ),
    RegionalBank(
        name="Banque de Développement des États de l'Afrique Centrale", abbreviation="BDEAC",
        region="Central Africa (CEMAC)", headquarters="Brazzaville, Congo",
        website="https://www.bdeac.org",
        member_countries=["CM", "CF", "TD", "CG", "GA", "GQ"],
        focus_areas=["infrastructure", "SME_finance", "agriculture"],
        phone="+242 06 528 4444",
        email="info@bdeac.org",
        contact=BankContact(address="Place du Gouvernement, Brazzaville, Congo", phone="+242 06 528 4444", email="info@bdeac.org", website="https://www.bdeac.org"),
    ),
    RegionalBank(
        name="Trade and Development Bank", abbreviation="TDB",
        region="Eastern & Southern Africa (COMESA)", headquarters="Nairobi, Kenya",
        website="https://www.tdbgroup.org",
        member_countries=["KE", "ET", "TZ", "UG", "ZM", "ZW", "MU", "EG", "SD"],
        focus_areas=["trade_finance", "project_finance", "LC_confirmation"],
        phone="+254 20 271 1718",
        email="tdb@tdbgroup.org",
        contact=BankContact(address="199, Lenana Place, Milimani, Nairobi, Kenya", phone="+254 20 271 1718", email="tdb@tdbgroup.org", website="https://www.tdbgroup.org", department="Trade Finance"),
    ),
]


# ---------------------------------------------------------------------------
# PUBLIC HELPERS
# ---------------------------------------------------------------------------

def get_central_bank(country_code: str) -> Optional[CentralBank]:
    """Return central bank data for a given ISO2 country code (case-insensitive)."""
    return CENTRAL_BANKS.get(country_code.upper())


def get_country_banks(country_code: str) -> BankingSystemInfo:
    """Return complete banking information for a country."""
    code = country_code.upper()
    cb = CENTRAL_BANKS.get(code)
    if cb is None:
        return BankingSystemInfo(
            country_code=code,
            country_name="Unknown",
            central_bank=CentralBank(
                country_code=code, country_name="Unknown",
                name="Unknown", abbreviation="N/A",
                forex_regulation="unknown",
                currency_code="N/A", currency_name="Unknown",
            ),
        )
    return BankingSystemInfo(
        country_code=code,
        country_name=cb.country_name,
        central_bank=cb,
        commercial_banks=COMMERCIAL_BANKS.get(code, []),
        regional_banks=[rb for rb in REGIONAL_BANKS if code in rb.member_countries],
    )


def get_regional_banks(region: Optional[str] = None) -> List[RegionalBank]:
    """Return regional/development banks, optionally filtered by region."""
    if region is None:
        return REGIONAL_BANKS
    region_lower = region.lower()
    return [
        rb for rb in REGIONAL_BANKS
        if region_lower in rb.region.lower()
    ]


def get_banks_register(
    search: Optional[str] = None,
    country_code: Optional[str] = None,
    bank_type: Optional[str] = None,
    trade_finance_only: bool = False,
) -> List[dict]:
    """
    Return a flat, searchable register of all banks.

    Parameters
    ----------
    search : str, optional
        Full-text search across name, abbreviation, country.
    country_code : str, optional
        Filter by ISO2 country code.
    bank_type : str, optional
        Filter by type: 'central' | 'commercial' | 'regional'.
    trade_finance_only : bool
        If True, only return banks with trade finance services.
    """
    results = []
    search_lower = search.lower() if search else None

    def _matches(text: Optional[str]) -> bool:
        if not search_lower:
            return True
        return bool(text and search_lower in text.lower())

    # Central banks
    if bank_type in (None, "central"):
        for code, cb in CENTRAL_BANKS.items():
            if country_code and code != country_code.upper():
                continue
            if not any(_matches(t) for t in [cb.name, cb.abbreviation, cb.country_name, code]):
                if search_lower:
                    continue
            results.append({
                "type": "central",
                "country_code": cb.country_code,
                "country_name": cb.country_name,
                "name": cb.name,
                "abbreviation": cb.abbreviation,
                "swift_code": cb.swift_code,
                "website": cb.website,
                "phone": cb.phone,
                "email": cb.email,
                "address": cb.address,
                "currency_code": cb.currency_code,
                "currency_name": cb.currency_name,
                "forex_regulation": cb.forex_regulation,
                "established_year": cb.established_year,
                "banking_act": cb.banking_act,
                "trade_finance": True,
                "contact": cb.contact.model_dump() if cb.contact else None,
            })

    # Commercial banks
    if bank_type in (None, "commercial"):
        for code, banks in COMMERCIAL_BANKS.items():
            if country_code and code != country_code.upper():
                continue
            for bank in banks:
                if trade_finance_only and not bank.trade_finance:
                    continue
                if not any(_matches(t) for t in [bank.name, bank.abbreviation, bank.country_code]):
                    if search_lower:
                        continue
                cb = CENTRAL_BANKS.get(code)
                results.append({
                    "type": "commercial",
                    "country_code": bank.country_code,
                    "country_name": cb.country_name if cb else code,
                    "name": bank.name,
                    "abbreviation": bank.abbreviation,
                    "swift_code": bank.swift_code,
                    "website": bank.website,
                    "phone": bank.phone,
                    "email": bank.email,
                    "address": bank.address,
                    "trade_finance": bank.trade_finance,
                    "services": bank.services,
                    "correspondent_banks": bank.correspondent_banks,
                    "license_type": bank.license_type,
                    "contact": bank.contact.model_dump() if bank.contact else None,
                })

    # Regional/development banks
    if bank_type in (None, "regional"):
        for rb in REGIONAL_BANKS:
            if country_code and country_code.upper() not in rb.member_countries:
                continue
            if not any(_matches(t) for t in [rb.name, rb.abbreviation, rb.region, rb.headquarters]):
                if search_lower:
                    continue
            results.append({
                "type": "regional",
                "country_code": None,
                "country_name": rb.region,
                "name": rb.name,
                "abbreviation": rb.abbreviation,
                "swift_code": None,
                "website": rb.website,
                "phone": rb.phone,
                "email": rb.email,
                "address": rb.contact.address if rb.contact else rb.headquarters,
                "trade_finance": "trade_finance" in rb.focus_areas or "LC_confirmation" in rb.focus_areas,
                "services": rb.focus_areas,
                "member_countries": rb.member_countries,
                "contact": rb.contact.model_dump() if rb.contact else None,
            })

    return results
