"""
Harmonized System (HS) Codes Database
======================================
Source: World Customs Organization (WCO) HS 2022
        African Union Tariff Schedule
        
Codes SH6 - Système Harmonisé à 6 chiffres
Format: XXYYZZ où XX=Chapitre, YY=Position, ZZ=Sous-position

Last updated: January 2025
"""

from typing import Dict, List, Optional

# =============================================================================
# CHAPITRES HS (2 chiffres) - SECTIONS PRINCIPALES
# =============================================================================

HS_CHAPTERS = {
    # SECTION I - ANIMAUX VIVANTS ET PRODUITS DU RÈGNE ANIMAL
    "01": {"fr": "Animaux vivants", "en": "Live animals"},
    "02": {"fr": "Viandes et abats comestibles", "en": "Meat and edible offal"},
    "03": {"fr": "Poissons, crustacés, mollusques", "en": "Fish, crustaceans, molluscs"},
    "04": {"fr": "Lait, œufs, miel, produits comestibles d'origine animale", "en": "Dairy, eggs, honey, edible animal products"},
    "05": {"fr": "Autres produits d'origine animale", "en": "Other animal products"},
    
    # SECTION II - PRODUITS DU RÈGNE VÉGÉTAL
    "06": {"fr": "Plantes vivantes et produits de la floriculture", "en": "Live plants and floriculture products"},
    "07": {"fr": "Légumes, plantes, racines et tubercules alimentaires", "en": "Vegetables, plants, roots and tubers"},
    "08": {"fr": "Fruits comestibles, écorces d'agrumes ou de melons", "en": "Edible fruits, citrus peel or melon"},
    "09": {"fr": "Café, thé, maté et épices", "en": "Coffee, tea, mate and spices"},
    "10": {"fr": "Céréales", "en": "Cereals"},
    "11": {"fr": "Produits de la minoterie, malt, amidons", "en": "Milling products, malt, starches"},
    "12": {"fr": "Graines et fruits oléagineux", "en": "Oil seeds and oleaginous fruits"},
    "13": {"fr": "Gommes, résines et autres sucs végétaux", "en": "Gums, resins and vegetable saps"},
    "14": {"fr": "Matières à tresser et autres produits végétaux", "en": "Vegetable plaiting materials"},
    
    # SECTION III - GRAISSES ET HUILES
    "15": {"fr": "Graisses et huiles animales ou végétales", "en": "Animal or vegetable fats and oils"},
    
    # SECTION IV - PRODUITS ALIMENTAIRES
    "16": {"fr": "Préparations de viandes, poissons ou crustacés", "en": "Preparations of meat, fish or crustaceans"},
    "17": {"fr": "Sucres et sucreries", "en": "Sugars and sugar confectionery"},
    "18": {"fr": "Cacao et ses préparations", "en": "Cocoa and cocoa preparations"},
    "19": {"fr": "Préparations à base de céréales, farines", "en": "Preparations of cereals, flour"},
    "20": {"fr": "Préparations de légumes, fruits, noix", "en": "Preparations of vegetables, fruits, nuts"},
    "21": {"fr": "Préparations alimentaires diverses", "en": "Miscellaneous edible preparations"},
    "22": {"fr": "Boissons, liquides alcooliques et vinaigres", "en": "Beverages, spirits and vinegar"},
    "23": {"fr": "Résidus des industries alimentaires, aliments pour animaux", "en": "Food industry residues, animal feed"},
    "24": {"fr": "Tabacs et succédanés de tabac fabriqués", "en": "Tobacco and manufactured tobacco substitutes"},
    
    # SECTION V - PRODUITS MINÉRAUX
    "25": {"fr": "Sel, soufre, terres et pierres, plâtres, chaux et ciments", "en": "Salt, sulphur, earths, stone, plasters, lime, cement"},
    "26": {"fr": "Minerais, scories et cendres", "en": "Ores, slag and ash"},
    "27": {"fr": "Combustibles minéraux, huiles minérales", "en": "Mineral fuels, mineral oils"},
    
    # SECTION VI - PRODUITS CHIMIQUES
    "28": {"fr": "Produits chimiques inorganiques", "en": "Inorganic chemicals"},
    "29": {"fr": "Produits chimiques organiques", "en": "Organic chemicals"},
    "30": {"fr": "Produits pharmaceutiques", "en": "Pharmaceutical products"},
    "31": {"fr": "Engrais", "en": "Fertilizers"},
    "32": {"fr": "Extraits tannants, matières colorantes, peintures", "en": "Tanning extracts, dyes, paints"},
    "33": {"fr": "Huiles essentielles, parfumerie, cosmétiques", "en": "Essential oils, perfumery, cosmetics"},
    "34": {"fr": "Savons, agents de surface organiques, cires", "en": "Soap, organic surfactants, waxes"},
    "35": {"fr": "Matières albuminoïdes, colles, enzymes", "en": "Albuminoidal substances, glues, enzymes"},
    "36": {"fr": "Poudres et explosifs, allumettes", "en": "Explosives, pyrotechnics, matches"},
    "37": {"fr": "Produits photographiques ou cinématographiques", "en": "Photographic or cinematographic goods"},
    "38": {"fr": "Produits divers des industries chimiques", "en": "Miscellaneous chemical products"},
    
    # SECTION VII - MATIÈRES PLASTIQUES ET CAOUTCHOUC
    "39": {"fr": "Matières plastiques et ouvrages en ces matières", "en": "Plastics and articles thereof"},
    "40": {"fr": "Caoutchouc et ouvrages en caoutchouc", "en": "Rubber and articles thereof"},
    
    # SECTION VIII - PEAUX, CUIRS, PELLETERIES
    "41": {"fr": "Peaux (autres que les pelleteries) et cuirs", "en": "Raw hides, skins and leather"},
    "42": {"fr": "Ouvrages en cuir, articles de sellerie", "en": "Articles of leather, saddlery"},
    "43": {"fr": "Pelleteries et fourrures", "en": "Furskins and artificial fur"},
    
    # SECTION IX - BOIS ET OUVRAGES EN BOIS
    "44": {"fr": "Bois, charbon de bois et ouvrages en bois", "en": "Wood, charcoal and articles of wood"},
    "45": {"fr": "Liège et ouvrages en liège", "en": "Cork and articles of cork"},
    "46": {"fr": "Ouvrages de sparterie ou de vannerie", "en": "Manufactures of straw, basketware"},
    
    # SECTION X - PÂTES DE BOIS, PAPIER
    "47": {"fr": "Pâtes de bois ou d'autres matières fibreuses", "en": "Pulp of wood or other fibrous material"},
    "48": {"fr": "Papiers et cartons", "en": "Paper and paperboard"},
    "49": {"fr": "Produits de l'édition, de la presse", "en": "Printed books, newspapers"},
    
    # SECTION XI - MATIÈRES TEXTILES
    "50": {"fr": "Soie", "en": "Silk"},
    "51": {"fr": "Laine, poils fins ou grossiers", "en": "Wool, fine or coarse animal hair"},
    "52": {"fr": "Coton", "en": "Cotton"},
    "53": {"fr": "Autres fibres textiles végétales", "en": "Other vegetable textile fibres"},
    "54": {"fr": "Filaments synthétiques ou artificiels", "en": "Man-made filaments"},
    "55": {"fr": "Fibres synthétiques ou artificielles discontinues", "en": "Man-made staple fibres"},
    "56": {"fr": "Ouates, feutres, non-tissés", "en": "Wadding, felt, nonwovens"},
    "57": {"fr": "Tapis et autres revêtements de sol en matières textiles", "en": "Carpets and other textile floor coverings"},
    "58": {"fr": "Tissus spéciaux, surfaces textiles touffetées", "en": "Special woven fabrics, tufted fabrics"},
    "59": {"fr": "Tissus imprégnés, enduits, recouverts", "en": "Impregnated, coated, covered textiles"},
    "60": {"fr": "Étoffes de bonneterie", "en": "Knitted or crocheted fabrics"},
    "61": {"fr": "Vêtements et accessoires en bonneterie", "en": "Knitted or crocheted apparel"},
    "62": {"fr": "Vêtements et accessoires autres qu'en bonneterie", "en": "Apparel not knitted or crocheted"},
    "63": {"fr": "Autres articles textiles confectionnés", "en": "Other made up textile articles"},
    
    # SECTION XII - CHAUSSURES, COIFFURES
    "64": {"fr": "Chaussures, guêtres et articles analogues", "en": "Footwear, gaiters and the like"},
    "65": {"fr": "Coiffures et parties de coiffures", "en": "Headgear and parts thereof"},
    "66": {"fr": "Parapluies, cannes, fouets", "en": "Umbrellas, walking-sticks, whips"},
    "67": {"fr": "Plumes et duvet apprêtés, fleurs artificielles", "en": "Prepared feathers, artificial flowers"},
    
    # SECTION XIII - OUVRAGES EN PIERRES, CÉRAMIQUES, VERRE
    "68": {"fr": "Ouvrages en pierres, plâtre, ciment, amiante", "en": "Articles of stone, plaster, cement, asbestos"},
    "69": {"fr": "Produits céramiques", "en": "Ceramic products"},
    "70": {"fr": "Verre et ouvrages en verre", "en": "Glass and glassware"},
    
    # SECTION XIV - PERLES, PIERRES PRÉCIEUSES, MÉTAUX PRÉCIEUX
    "71": {"fr": "Perles, pierres précieuses, métaux précieux", "en": "Pearls, precious stones, precious metals"},
    
    # SECTION XV - MÉTAUX COMMUNS
    "72": {"fr": "Fonte, fer et acier", "en": "Iron and steel"},
    "73": {"fr": "Ouvrages en fonte, fer ou acier", "en": "Articles of iron or steel"},
    "74": {"fr": "Cuivre et ouvrages en cuivre", "en": "Copper and articles thereof"},
    "75": {"fr": "Nickel et ouvrages en nickel", "en": "Nickel and articles thereof"},
    "76": {"fr": "Aluminium et ouvrages en aluminium", "en": "Aluminium and articles thereof"},
    "78": {"fr": "Plomb et ouvrages en plomb", "en": "Lead and articles thereof"},
    "79": {"fr": "Zinc et ouvrages en zinc", "en": "Zinc and articles thereof"},
    "80": {"fr": "Étain et ouvrages en étain", "en": "Tin and articles thereof"},
    "81": {"fr": "Autres métaux communs, cermets", "en": "Other base metals, cermets"},
    "82": {"fr": "Outils et outillage, coutellerie", "en": "Tools, cutlery of base metal"},
    "83": {"fr": "Ouvrages divers en métaux communs", "en": "Miscellaneous articles of base metal"},
    
    # SECTION XVI - MACHINES ET APPAREILS
    "84": {"fr": "Réacteurs nucléaires, chaudières, machines", "en": "Nuclear reactors, boilers, machinery"},
    "85": {"fr": "Machines et appareils électriques", "en": "Electrical machinery and equipment"},
    
    # SECTION XVII - MATÉRIEL DE TRANSPORT
    "86": {"fr": "Véhicules et matériel pour voies ferrées", "en": "Railway locomotives, rolling stock"},
    "87": {"fr": "Voitures automobiles, tracteurs, cycles", "en": "Vehicles other than railway"},
    "88": {"fr": "Navigation aérienne ou spatiale", "en": "Aircraft, spacecraft"},
    "89": {"fr": "Navigation maritime ou fluviale", "en": "Ships, boats"},
    
    # SECTION XVIII - INSTRUMENTS ET APPAREILS
    "90": {"fr": "Instruments et appareils d'optique, de mesure", "en": "Optical, measuring, medical instruments"},
    "91": {"fr": "Horlogerie", "en": "Clocks and watches"},
    "92": {"fr": "Instruments de musique", "en": "Musical instruments"},
    
    # SECTION XIX - ARMES ET MUNITIONS
    "93": {"fr": "Armes, munitions et leurs parties", "en": "Arms and ammunition"},
    
    # SECTION XX - MARCHANDISES ET PRODUITS DIVERS
    "94": {"fr": "Meubles, mobilier médico-chirurgical, literie", "en": "Furniture, bedding, lamps"},
    "95": {"fr": "Jouets, jeux, articles pour divertissements, sports", "en": "Toys, games, sports requisites"},
    "96": {"fr": "Ouvrages divers", "en": "Miscellaneous manufactured articles"},
    
    # SECTION XXI - OBJETS D'ART, DE COLLECTION
    "97": {"fr": "Objets d'art, de collection ou d'antiquité", "en": "Works of art, collectors' pieces, antiques"},
    "99": {"fr": "Transactions spéciales", "en": "Special transactions"}
}

# =============================================================================
# CODES SH6 DÉTAILLÉS - PRODUITS LES PLUS ÉCHANGÉS EN AFRIQUE
# =============================================================================

HS6_CODES = {
    # CHAPITRE 01 - ANIMAUX VIVANTS
    "010110": {"fr": "Chevaux reproducteurs de race pure", "en": "Pure-bred breeding horses"},
    "010121": {"fr": "Chevaux vivants (autres que reproducteurs)", "en": "Live horses (non-breeding)"},
    "010290": {"fr": "Autres bovins vivants", "en": "Other live bovine animals"},
    "010310": {"fr": "Porcins reproducteurs de race pure", "en": "Pure-bred breeding swine"},
    "010410": {"fr": "Ovins vivants", "en": "Live sheep"},
    "010420": {"fr": "Caprins vivants", "en": "Live goats"},
    "010511": {"fr": "Coqs et poules ≤185g", "en": "Fowls ≤185g"},
    "010512": {"fr": "Dindes vivantes ≤185g", "en": "Live turkeys ≤185g"},
    "010594": {"fr": "Autres volailles vivantes", "en": "Other live poultry"},
    "010611": {"fr": "Primates vivants", "en": "Live primates"},
    
    # CHAPITRE 02 - VIANDES
    "020110": {"fr": "Carcasses de bovins, fraîches ou réfrigérées", "en": "Bovine carcasses, fresh or chilled"},
    "020120": {"fr": "Autres morceaux de bovins non désossés", "en": "Other bovine cuts, bone-in"},
    "020130": {"fr": "Viande de bovins désossée, fraîche", "en": "Bovine meat, boneless, fresh"},
    "020210": {"fr": "Carcasses de bovins congelées", "en": "Bovine carcasses, frozen"},
    "020220": {"fr": "Autres morceaux de bovins congelés", "en": "Other bovine cuts, frozen"},
    "020230": {"fr": "Viande de bovins désossée, congelée", "en": "Bovine meat, boneless, frozen"},
    "020311": {"fr": "Carcasses de porcins fraîches", "en": "Swine carcasses, fresh"},
    "020312": {"fr": "Jambons et épaules de porcins", "en": "Hams and shoulders of swine"},
    "020410": {"fr": "Carcasses d'agneau fraîches", "en": "Lamb carcasses, fresh"},
    "020421": {"fr": "Autres viandes ovines fraîches", "en": "Other sheep meat, fresh"},
    "020422": {"fr": "Viandes ovines congelées", "en": "Sheep meat, frozen"},
    "020430": {"fr": "Carcasses de caprins", "en": "Goat carcasses"},
    "020500": {"fr": "Viandes chevalines", "en": "Horse meat"},
    "020610": {"fr": "Abats de bovins frais", "en": "Bovine offal, fresh"},
    "020621": {"fr": "Langues de bovins congelées", "en": "Bovine tongues, frozen"},
    "020711": {"fr": "Coqs et poules entiers frais", "en": "Whole fowls, fresh"},
    "020712": {"fr": "Coqs et poules entiers congelés", "en": "Whole fowls, frozen"},
    "020713": {"fr": "Morceaux de volailles frais", "en": "Poultry cuts, fresh"},
    "020714": {"fr": "Morceaux de volailles congelés", "en": "Poultry cuts, frozen"},
    
    # CHAPITRE 03 - POISSONS
    "030110": {"fr": "Poissons d'ornement vivants", "en": "Live ornamental fish"},
    "030191": {"fr": "Truites vivantes", "en": "Live trout"},
    "030199": {"fr": "Autres poissons vivants", "en": "Other live fish"},
    "030211": {"fr": "Truites fraîches ou réfrigérées", "en": "Trout, fresh or chilled"},
    "030212": {"fr": "Saumons du Pacifique frais", "en": "Pacific salmon, fresh"},
    "030214": {"fr": "Saumons de l'Atlantique frais", "en": "Atlantic salmon, fresh"},
    "030231": {"fr": "Thons albacores frais", "en": "Albacore tuna, fresh"},
    "030232": {"fr": "Thons à nageoires jaunes frais", "en": "Yellowfin tuna, fresh"},
    "030233": {"fr": "Listaos frais", "en": "Skipjack tuna, fresh"},
    "030234": {"fr": "Thons obèses frais", "en": "Bigeye tuna, fresh"},
    "030235": {"fr": "Thons rouges frais", "en": "Bluefin tuna, fresh"},
    "030241": {"fr": "Harengs frais", "en": "Herrings, fresh"},
    "030242": {"fr": "Anchois frais", "en": "Anchovies, fresh"},
    "030243": {"fr": "Sardines fraîches", "en": "Sardines, fresh"},
    "030244": {"fr": "Maquereaux frais", "en": "Mackerel, fresh"},
    "030251": {"fr": "Morues fraîches", "en": "Cod, fresh"},
    "030271": {"fr": "Tilapias frais", "en": "Tilapia, fresh"},
    "030272": {"fr": "Poissons-chats frais", "en": "Catfish, fresh"},
    "030281": {"fr": "Requins frais", "en": "Sharks, fresh"},
    "030311": {"fr": "Saumons du Pacifique congelés", "en": "Pacific salmon, frozen"},
    "030312": {"fr": "Autres salmonidés congelés", "en": "Other salmonidae, frozen"},
    "030314": {"fr": "Truites congelées", "en": "Trout, frozen"},
    "030323": {"fr": "Tilapias congelés", "en": "Tilapia, frozen"},
    "030324": {"fr": "Poissons-chats congelés", "en": "Catfish, frozen"},
    "030331": {"fr": "Flétans congelés", "en": "Halibut, frozen"},
    "030341": {"fr": "Thons albacores congelés", "en": "Albacore tuna, frozen"},
    "030342": {"fr": "Thons à nageoires jaunes congelés", "en": "Yellowfin tuna, frozen"},
    "030351": {"fr": "Harengs congelés", "en": "Herrings, frozen"},
    "030353": {"fr": "Sardines congelées", "en": "Sardines, frozen"},
    "030354": {"fr": "Maquereaux congelés", "en": "Mackerel, frozen"},
    "030363": {"fr": "Morues congelées", "en": "Cod, frozen"},
    "030389": {"fr": "Autres poissons congelés", "en": "Other fish, frozen"},
    "030410": {"fr": "Filets de poissons frais", "en": "Fish fillets, fresh"},
    "030420": {"fr": "Filets de poissons congelés", "en": "Fish fillets, frozen"},
    "030520": {"fr": "Foies et œufs de poissons séchés", "en": "Fish livers and roes, dried"},
    "030531": {"fr": "Filets de tilapia séchés", "en": "Dried tilapia fillets"},
    "030541": {"fr": "Saumons fumés", "en": "Smoked salmon"},
    "030542": {"fr": "Harengs fumés", "en": "Smoked herrings"},
    "030551": {"fr": "Morues séchées", "en": "Dried cod"},
    "030561": {"fr": "Harengs salés", "en": "Salted herrings"},
    "030571": {"fr": "Ailerons de requins", "en": "Shark fins"},
    "030611": {"fr": "Langoustes congelées", "en": "Frozen rock lobster"},
    "030612": {"fr": "Homards congelés", "en": "Frozen lobsters"},
    "030614": {"fr": "Crabes congelés", "en": "Frozen crabs"},
    "030616": {"fr": "Crevettes congelées", "en": "Frozen shrimps"},
    "030617": {"fr": "Autres crevettes congelées", "en": "Other frozen shrimps"},
    "030631": {"fr": "Langoustes vivantes", "en": "Live rock lobster"},
    "030632": {"fr": "Homards vivants", "en": "Live lobsters"},
    "030711": {"fr": "Huîtres vivantes", "en": "Live oysters"},
    "030721": {"fr": "Coquilles Saint-Jacques vivantes", "en": "Live scallops"},
    "030731": {"fr": "Moules vivantes", "en": "Live mussels"},
    "030741": {"fr": "Seiches vivantes", "en": "Live cuttlefish"},
    "030751": {"fr": "Poulpes vivants", "en": "Live octopus"},
    "030759": {"fr": "Poulpes congelés", "en": "Frozen octopus"},
    "030791": {"fr": "Autres mollusques vivants", "en": "Other live molluscs"},
    
    # CHAPITRE 04 - PRODUITS LAITIERS
    "040110": {"fr": "Lait non concentré ≤1% mat.grasses", "en": "Milk, not concentrated, ≤1% fat"},
    "040120": {"fr": "Lait non concentré 1-6% mat.grasses", "en": "Milk, not concentrated, 1-6% fat"},
    "040130": {"fr": "Lait non concentré >6% mat.grasses", "en": "Milk, not concentrated, >6% fat"},
    "040140": {"fr": "Lait non concentré >6% sucré", "en": "Milk, not concentrated, >6% sweetened"},
    "040210": {"fr": "Lait en poudre ≤1.5% mat.grasses", "en": "Milk powder, ≤1.5% fat"},
    "040221": {"fr": "Lait en poudre >1.5% non sucré", "en": "Milk powder, >1.5% unsweetened"},
    "040229": {"fr": "Lait en poudre >1.5% sucré", "en": "Milk powder, >1.5% sweetened"},
    "040291": {"fr": "Autres laits concentrés non sucrés", "en": "Other concentrated milk, unsweetened"},
    "040299": {"fr": "Autres laits concentrés sucrés", "en": "Other concentrated milk, sweetened"},
    "040310": {"fr": "Yaourt", "en": "Yogurt"},
    "040390": {"fr": "Autres laits fermentés", "en": "Other fermented milk"},
    "040410": {"fr": "Lactosérum", "en": "Whey"},
    "040490": {"fr": "Autres produits de lactosérum", "en": "Other whey products"},
    "040510": {"fr": "Beurre", "en": "Butter"},
    "040520": {"fr": "Pâtes à tartiner laitières", "en": "Dairy spreads"},
    "040590": {"fr": "Autres matières grasses du lait", "en": "Other fats from milk"},
    "040610": {"fr": "Fromages frais", "en": "Fresh cheese"},
    "040620": {"fr": "Fromages râpés ou en poudre", "en": "Grated or powdered cheese"},
    "040630": {"fr": "Fromages fondus", "en": "Processed cheese"},
    "040640": {"fr": "Fromages à pâte persillée", "en": "Blue-veined cheese"},
    "040690": {"fr": "Autres fromages", "en": "Other cheese"},
    "040700": {"fr": "Œufs d'oiseaux en coquilles", "en": "Birds' eggs, in shell"},
    "040811": {"fr": "Jaunes d'œufs séchés", "en": "Dried egg yolks"},
    "040819": {"fr": "Autres jaunes d'œufs", "en": "Other egg yolks"},
    "040891": {"fr": "Œufs séchés sans coquilles", "en": "Dried eggs, not in shell"},
    "040899": {"fr": "Autres œufs sans coquilles", "en": "Other eggs, not in shell"},
    "040900": {"fr": "Miel naturel", "en": "Natural honey"},
    
    # CHAPITRE 07 - LÉGUMES
    "070110": {"fr": "Pommes de terre de semence", "en": "Seed potatoes"},
    "070190": {"fr": "Autres pommes de terre fraîches", "en": "Other fresh potatoes"},
    "070200": {"fr": "Tomates fraîches ou réfrigérées", "en": "Fresh or chilled tomatoes"},
    "070310": {"fr": "Oignons et échalotes", "en": "Onions and shallots"},
    "070320": {"fr": "Ail", "en": "Garlic"},
    "070390": {"fr": "Poireaux et autres alliacées", "en": "Leeks and other alliaceous"},
    "070410": {"fr": "Choux-fleurs et brocolis", "en": "Cauliflowers and broccoli"},
    "070420": {"fr": "Choux de Bruxelles", "en": "Brussels sprouts"},
    "070490": {"fr": "Autres choux", "en": "Other cabbages"},
    "070511": {"fr": "Laitues pommées", "en": "Head lettuce"},
    "070519": {"fr": "Autres laitues", "en": "Other lettuce"},
    "070521": {"fr": "Chicorées witloof", "en": "Witloof chicory"},
    "070529": {"fr": "Autres chicorées", "en": "Other chicory"},
    "070610": {"fr": "Carottes et navets", "en": "Carrots and turnips"},
    "070690": {"fr": "Autres racines comestibles", "en": "Other edible roots"},
    "070700": {"fr": "Concombres et cornichons", "en": "Cucumbers and gherkins"},
    "070810": {"fr": "Pois frais", "en": "Fresh peas"},
    "070820": {"fr": "Haricots frais", "en": "Fresh beans"},
    "070890": {"fr": "Autres légumineuses fraîches", "en": "Other fresh leguminous"},
    "070920": {"fr": "Asperges fraîches", "en": "Fresh asparagus"},
    "070930": {"fr": "Aubergines fraîches", "en": "Fresh aubergines"},
    "070940": {"fr": "Céleris frais", "en": "Fresh celery"},
    "070951": {"fr": "Champignons frais", "en": "Fresh mushrooms"},
    "070959": {"fr": "Autres champignons frais", "en": "Other fresh mushrooms"},
    "070960": {"fr": "Piments et poivrons frais", "en": "Fresh peppers"},
    "070970": {"fr": "Épinards frais", "en": "Fresh spinach"},
    "070991": {"fr": "Artichauts frais", "en": "Fresh artichokes"},
    "070993": {"fr": "Courges fraîches", "en": "Fresh pumpkins"},
    "070999": {"fr": "Autres légumes frais", "en": "Other fresh vegetables"},
    
    # CHAPITRE 08 - FRUITS
    "080111": {"fr": "Noix de coco desséchées", "en": "Desiccated coconuts"},
    "080112": {"fr": "Noix de coco fraîches", "en": "Fresh coconuts"},
    "080119": {"fr": "Autres noix de coco", "en": "Other coconuts"},
    "080121": {"fr": "Noix du Brésil en coques", "en": "Brazil nuts, in shell"},
    "080122": {"fr": "Noix du Brésil décortiquées", "en": "Shelled Brazil nuts"},
    "080131": {"fr": "Noix de cajou en coques", "en": "Cashew nuts, in shell"},
    "080132": {"fr": "Noix de cajou décortiquées", "en": "Shelled cashew nuts"},
    "080211": {"fr": "Amandes en coques", "en": "Almonds, in shell"},
    "080212": {"fr": "Amandes décortiquées", "en": "Shelled almonds"},
    "080221": {"fr": "Noisettes en coques", "en": "Hazelnuts, in shell"},
    "080222": {"fr": "Noisettes décortiquées", "en": "Shelled hazelnuts"},
    "080231": {"fr": "Noix en coques", "en": "Walnuts, in shell"},
    "080232": {"fr": "Noix décortiquées", "en": "Shelled walnuts"},
    "080241": {"fr": "Châtaignes en coques", "en": "Chestnuts, in shell"},
    "080242": {"fr": "Châtaignes décortiquées", "en": "Shelled chestnuts"},
    "080251": {"fr": "Pistaches en coques", "en": "Pistachios, in shell"},
    "080252": {"fr": "Pistaches décortiquées", "en": "Shelled pistachios"},
    "080261": {"fr": "Noix de macadamia en coques", "en": "Macadamia nuts, in shell"},
    "080262": {"fr": "Noix de macadamia décortiquées", "en": "Shelled macadamia nuts"},
    "080290": {"fr": "Autres fruits à coques", "en": "Other nuts"},
    "080310": {"fr": "Bananes plantain", "en": "Plantains"},
    "080390": {"fr": "Autres bananes fraîches", "en": "Other fresh bananas"},
    "080410": {"fr": "Dattes fraîches ou sèches", "en": "Fresh or dried dates"},
    "080420": {"fr": "Figues fraîches ou sèches", "en": "Fresh or dried figs"},
    "080430": {"fr": "Ananas frais ou secs", "en": "Fresh or dried pineapples"},
    "080440": {"fr": "Avocats frais ou secs", "en": "Fresh or dried avocados"},
    "080450": {"fr": "Goyaves, mangues, mangoustans", "en": "Guavas, mangoes, mangosteens"},
    "080510": {"fr": "Oranges fraîches ou sèches", "en": "Fresh or dried oranges"},
    "080520": {"fr": "Mandarines, clémentines", "en": "Mandarins, clementines"},
    "080540": {"fr": "Pamplemousses et pomelos", "en": "Grapefruit and pomelos"},
    "080550": {"fr": "Citrons et limes", "en": "Lemons and limes"},
    "080590": {"fr": "Autres agrumes", "en": "Other citrus fruit"},
    "080610": {"fr": "Raisins frais", "en": "Fresh grapes"},
    "080620": {"fr": "Raisins secs", "en": "Dried grapes"},
    "080711": {"fr": "Pastèques fraîches", "en": "Fresh watermelons"},
    "080719": {"fr": "Autres melons frais", "en": "Other fresh melons"},
    "080720": {"fr": "Papayes fraîches", "en": "Fresh papayas"},
    "080810": {"fr": "Pommes fraîches", "en": "Fresh apples"},
    "080830": {"fr": "Poires fraîches", "en": "Fresh pears"},
    "080840": {"fr": "Coings frais", "en": "Fresh quinces"},
    "080910": {"fr": "Abricots frais", "en": "Fresh apricots"},
    "080921": {"fr": "Cerises acides fraîches", "en": "Fresh sour cherries"},
    "080929": {"fr": "Autres cerises fraîches", "en": "Other fresh cherries"},
    "080930": {"fr": "Pêches et nectarines fraîches", "en": "Fresh peaches and nectarines"},
    "080940": {"fr": "Prunes fraîches", "en": "Fresh plums"},
    "081010": {"fr": "Fraises fraîches", "en": "Fresh strawberries"},
    "081020": {"fr": "Framboises, mûres fraîches", "en": "Fresh raspberries, blackberries"},
    "081030": {"fr": "Groseilles, cassis frais", "en": "Fresh currants, gooseberries"},
    "081040": {"fr": "Airelles, myrtilles fraîches", "en": "Fresh cranberries, blueberries"},
    "081050": {"fr": "Kiwis frais", "en": "Fresh kiwifruit"},
    "081060": {"fr": "Durians frais", "en": "Fresh durians"},
    "081070": {"fr": "Kakis frais", "en": "Fresh persimmons"},
    "081090": {"fr": "Autres fruits frais", "en": "Other fresh fruit"},
    "081110": {"fr": "Fraises congelées", "en": "Frozen strawberries"},
    "081120": {"fr": "Framboises congelées", "en": "Frozen raspberries"},
    "081190": {"fr": "Autres fruits congelés", "en": "Other frozen fruit"},
    "081210": {"fr": "Cerises conservées", "en": "Provisionally preserved cherries"},
    "081290": {"fr": "Autres fruits conservés", "en": "Other provisionally preserved fruit"},
    "081310": {"fr": "Abricots séchés", "en": "Dried apricots"},
    "081320": {"fr": "Pruneaux", "en": "Dried prunes"},
    "081330": {"fr": "Pommes séchées", "en": "Dried apples"},
    "081340": {"fr": "Autres fruits séchés", "en": "Other dried fruit"},
    "081350": {"fr": "Mélanges de fruits secs", "en": "Mixtures of dried fruit"},
    "081400": {"fr": "Écorces d'agrumes ou de melons", "en": "Peel of citrus or melons"},
    
    # CHAPITRE 09 - CAFÉ, THÉ, ÉPICES
    "090111": {"fr": "Café non torréfié, non décaféiné", "en": "Coffee, not roasted, not decaffeinated"},
    "090112": {"fr": "Café non torréfié, décaféiné", "en": "Coffee, not roasted, decaffeinated"},
    "090121": {"fr": "Café torréfié, non décaféiné", "en": "Coffee, roasted, not decaffeinated"},
    "090122": {"fr": "Café torréfié, décaféiné", "en": "Coffee, roasted, decaffeinated"},
    "090130": {"fr": "Coques et pellicules de café", "en": "Coffee husks and skins"},
    "090190": {"fr": "Succédanés de café contenant du café", "en": "Coffee substitutes containing coffee"},
    "090210": {"fr": "Thé vert non fermenté ≤3kg", "en": "Green tea, not fermented, ≤3kg"},
    "090220": {"fr": "Autres thés verts ≤3kg", "en": "Other green tea, ≤3kg"},
    "090230": {"fr": "Thé noir fermenté ≤3kg", "en": "Black tea, fermented, ≤3kg"},
    "090240": {"fr": "Autres thés noirs ≤3kg", "en": "Other black tea, ≤3kg"},
    "090300": {"fr": "Maté", "en": "Maté"},
    "090411": {"fr": "Poivre non broyé", "en": "Pepper, not crushed"},
    "090412": {"fr": "Poivre broyé", "en": "Pepper, crushed"},
    "090420": {"fr": "Piments séchés, broyés ou non", "en": "Dried peppers, crushed or not"},
    "090500": {"fr": "Vanille", "en": "Vanilla"},
    "090611": {"fr": "Cannelle non broyée", "en": "Cinnamon, not crushed"},
    "090619": {"fr": "Cannelle broyée", "en": "Cinnamon, crushed"},
    "090620": {"fr": "Fleurs de cannelier", "en": "Cinnamon-tree flowers"},
    "090700": {"fr": "Girofles", "en": "Cloves"},
    "090810": {"fr": "Noix muscade", "en": "Nutmeg"},
    "090820": {"fr": "Macis", "en": "Mace"},
    "090830": {"fr": "Amomes et cardamomes", "en": "Cardamoms"},
    "090910": {"fr": "Graines d'anis ou de badiane", "en": "Seeds of anise or badian"},
    "090921": {"fr": "Graines de coriandre non broyées", "en": "Coriander seeds, not crushed"},
    "090922": {"fr": "Graines de coriandre broyées", "en": "Coriander seeds, crushed"},
    "090931": {"fr": "Graines de cumin non broyées", "en": "Cumin seeds, not crushed"},
    "090932": {"fr": "Graines de cumin broyées", "en": "Cumin seeds, crushed"},
    "090961": {"fr": "Graines de genièvre", "en": "Juniper berries"},
    "090962": {"fr": "Autres graines aromatiques", "en": "Other aromatic seeds"},
    "091010": {"fr": "Gingembre", "en": "Ginger"},
    "091020": {"fr": "Safran", "en": "Saffron"},
    "091030": {"fr": "Curcuma", "en": "Turmeric"},
    "091091": {"fr": "Mélanges d'épices", "en": "Mixtures of spices"},
    "091099": {"fr": "Autres épices", "en": "Other spices"},
    
    # CHAPITRE 10 - CÉRÉALES
    "100110": {"fr": "Froment dur", "en": "Durum wheat"},
    "100190": {"fr": "Autres froments et méteil", "en": "Other wheat and meslin"},
    "100200": {"fr": "Seigle", "en": "Rye"},
    "100300": {"fr": "Orge", "en": "Barley"},
    "100400": {"fr": "Avoine", "en": "Oats"},
    "100510": {"fr": "Maïs de semence", "en": "Maize seed"},
    "100590": {"fr": "Autres maïs", "en": "Other maize"},
    "100610": {"fr": "Riz en paille", "en": "Rice in the husk"},
    "100620": {"fr": "Riz décortiqué", "en": "Husked rice"},
    "100630": {"fr": "Riz semi-blanchi ou blanchi", "en": "Semi-milled or wholly milled rice"},
    "100640": {"fr": "Riz en brisures", "en": "Broken rice"},
    "100700": {"fr": "Sorgho à grains", "en": "Grain sorghum"},
    "100810": {"fr": "Sarrasin", "en": "Buckwheat"},
    "100821": {"fr": "Millet de semence", "en": "Millet seed"},
    "100829": {"fr": "Autres millets", "en": "Other millet"},
    "100830": {"fr": "Alpiste", "en": "Canary seed"},
    "100840": {"fr": "Fonio", "en": "Fonio"},
    "100850": {"fr": "Quinoa", "en": "Quinoa"},
    "100860": {"fr": "Triticale", "en": "Triticale"},
    "100890": {"fr": "Autres céréales", "en": "Other cereals"},
    
    # CHAPITRE 15 - HUILES
    "150710": {"fr": "Huile de soja brute", "en": "Crude soybean oil"},
    "150790": {"fr": "Autres huiles de soja", "en": "Other soybean oil"},
    "150810": {"fr": "Huile d'arachide brute", "en": "Crude groundnut oil"},
    "150890": {"fr": "Autres huiles d'arachide", "en": "Other groundnut oil"},
    "150910": {"fr": "Huile d'olive vierge", "en": "Virgin olive oil"},
    "150990": {"fr": "Autres huiles d'olive", "en": "Other olive oil"},
    "151110": {"fr": "Huile de palme brute", "en": "Crude palm oil"},
    "151190": {"fr": "Autres huiles de palme", "en": "Other palm oil"},
    "151211": {"fr": "Huile de tournesol brute", "en": "Crude sunflower oil"},
    "151219": {"fr": "Autres huiles de tournesol", "en": "Other sunflower oil"},
    "151221": {"fr": "Huile de coton brute", "en": "Crude cottonseed oil"},
    "151229": {"fr": "Autres huiles de coton", "en": "Other cottonseed oil"},
    "151311": {"fr": "Huile de coco brute", "en": "Crude coconut oil"},
    "151319": {"fr": "Autres huiles de coco", "en": "Other coconut oil"},
    "151321": {"fr": "Huile de palmiste brute", "en": "Crude palm kernel oil"},
    "151329": {"fr": "Autres huiles de palmiste", "en": "Other palm kernel oil"},
    "151411": {"fr": "Huile de colza brute à faible teneur", "en": "Crude low erucic acid rape oil"},
    "151419": {"fr": "Autres huiles de colza à faible teneur", "en": "Other low erucic acid rape oil"},
    "151491": {"fr": "Huile de colza brute", "en": "Crude rape oil"},
    "151499": {"fr": "Autres huiles de colza", "en": "Other rape oil"},
    "151511": {"fr": "Huile de lin brute", "en": "Crude linseed oil"},
    "151519": {"fr": "Autres huiles de lin", "en": "Other linseed oil"},
    "151521": {"fr": "Huile de maïs brute", "en": "Crude maize oil"},
    "151529": {"fr": "Autres huiles de maïs", "en": "Other maize oil"},
    "151530": {"fr": "Huile de ricin", "en": "Castor oil"},
    "151540": {"fr": "Huile de tung", "en": "Tung oil"},
    "151550": {"fr": "Huile de sésame", "en": "Sesame oil"},
    "151590": {"fr": "Autres huiles végétales fixes", "en": "Other fixed vegetable fats and oils"},
    "151610": {"fr": "Graisses animales hydrogénées", "en": "Hydrogenated animal fats"},
    "151620": {"fr": "Graisses végétales hydrogénées", "en": "Hydrogenated vegetable fats"},
    "151710": {"fr": "Margarine", "en": "Margarine"},
    "151790": {"fr": "Autres mélanges de graisses", "en": "Other edible mixtures of fats"},
    
    # CHAPITRE 17 - SUCRES
    "170111": {"fr": "Sucre de canne brut", "en": "Raw cane sugar"},
    "170112": {"fr": "Sucre de betterave brut", "en": "Raw beet sugar"},
    "170113": {"fr": "Sucre de canne mentionné dans la note 2", "en": "Cane sugar as specified in note 2"},
    "170114": {"fr": "Autres sucres de canne", "en": "Other cane sugar"},
    "170191": {"fr": "Sucre raffiné avec aromatisants", "en": "Refined sugar with flavoring"},
    "170199": {"fr": "Autres sucres raffinés", "en": "Other refined sugar"},
    "170211": {"fr": "Lactose ≥99% pureté", "en": "Lactose ≥99% purity"},
    "170219": {"fr": "Autres lactoses", "en": "Other lactose"},
    "170220": {"fr": "Sucre d'érable", "en": "Maple sugar"},
    "170230": {"fr": "Glucose", "en": "Glucose"},
    "170240": {"fr": "Glucose sous forme solide", "en": "Glucose in solid form"},
    "170250": {"fr": "Fructose chimiquement pur", "en": "Chemically pure fructose"},
    "170260": {"fr": "Autres fructoses", "en": "Other fructose"},
    "170290": {"fr": "Autres sucres", "en": "Other sugars"},
    "170310": {"fr": "Mélasse de canne", "en": "Cane molasses"},
    "170390": {"fr": "Autres mélasses", "en": "Other molasses"},
    "170410": {"fr": "Gommes à mâcher", "en": "Chewing gum"},
    "170490": {"fr": "Autres sucreries sans cacao", "en": "Other sugar confectionery"},
    
    # CHAPITRE 18 - CACAO
    "180100": {"fr": "Cacao en fèves", "en": "Cocoa beans"},
    "180200": {"fr": "Coques et pellicules de cacao", "en": "Cocoa shells and husks"},
    "180310": {"fr": "Pâte de cacao non dégraissée", "en": "Cocoa paste, not defatted"},
    "180320": {"fr": "Pâte de cacao dégraissée", "en": "Cocoa paste, defatted"},
    "180400": {"fr": "Beurre de cacao", "en": "Cocoa butter"},
    "180500": {"fr": "Poudre de cacao sans sucre", "en": "Cocoa powder, unsweetened"},
    "180610": {"fr": "Poudre de cacao sucrée", "en": "Cocoa powder, sweetened"},
    "180620": {"fr": "Autres préparations au cacao >2kg", "en": "Other cocoa preparations >2kg"},
    "180631": {"fr": "Chocolat fourré en tablettes", "en": "Filled chocolate in blocks"},
    "180632": {"fr": "Chocolat non fourré en tablettes", "en": "Unfilled chocolate in blocks"},
    "180690": {"fr": "Autres chocolats et préparations", "en": "Other chocolate and preparations"},
    
    # CHAPITRE 22 - BOISSONS
    "220110": {"fr": "Eaux minérales gazeuses", "en": "Sparkling mineral water"},
    "220190": {"fr": "Autres eaux minérales", "en": "Other mineral water"},
    "220210": {"fr": "Eaux additionnées de sucre", "en": "Waters with added sugar"},
    "220290": {"fr": "Autres boissons non alcooliques", "en": "Other non-alcoholic beverages"},
    "220300": {"fr": "Bières de malt", "en": "Beer made from malt"},
    "220410": {"fr": "Vins mousseux", "en": "Sparkling wine"},
    "220421": {"fr": "Vins en récipients ≤2L", "en": "Wine in containers ≤2L"},
    "220422": {"fr": "Vins en récipients 2-10L", "en": "Wine in containers 2-10L"},
    "220429": {"fr": "Autres vins de raisins", "en": "Other grape wine"},
    "220430": {"fr": "Moûts de raisins", "en": "Grape must"},
    "220510": {"fr": "Vermouths ≤2L", "en": "Vermouth ≤2L"},
    "220590": {"fr": "Autres vermouths", "en": "Other vermouth"},
    "220600": {"fr": "Autres boissons fermentées", "en": "Other fermented beverages"},
    "220710": {"fr": "Alcool éthylique ≥80%", "en": "Ethyl alcohol ≥80%"},
    "220720": {"fr": "Alcool éthylique dénaturé", "en": "Denatured ethyl alcohol"},
    "220810": {"fr": "Rhum et tafia", "en": "Rum and tafia"},
    "220820": {"fr": "Eaux-de-vie de vin ou marc", "en": "Spirits from wine or grape marc"},
    "220830": {"fr": "Whisky", "en": "Whisky"},
    "220840": {"fr": "Rhum et autres eaux-de-vie de canne", "en": "Rum and other cane spirits"},
    "220850": {"fr": "Gin et genièvre", "en": "Gin and Geneva"},
    "220860": {"fr": "Vodka", "en": "Vodka"},
    "220870": {"fr": "Liqueurs", "en": "Liqueurs"},
    "220890": {"fr": "Autres alcools", "en": "Other spirits"},
    "220900": {"fr": "Vinaigres", "en": "Vinegar"},
    
    # CHAPITRE 24 - TABACS
    "240110": {"fr": "Tabacs bruts non écôtés", "en": "Tobacco, not stemmed"},
    "240120": {"fr": "Tabacs bruts écôtés", "en": "Tobacco, stemmed"},
    "240130": {"fr": "Déchets de tabac", "en": "Tobacco refuse"},
    "240210": {"fr": "Cigares et cigarillos", "en": "Cigars and cigarillos"},
    "240220": {"fr": "Cigarettes contenant du tabac", "en": "Cigarettes containing tobacco"},
    "240290": {"fr": "Autres tabacs manufacturés", "en": "Other manufactured tobacco"},
    "240311": {"fr": "Tabac à pipe", "en": "Pipe tobacco"},
    "240319": {"fr": "Autres tabacs à fumer", "en": "Other smoking tobacco"},
    "240391": {"fr": "Tabacs homogénéisés", "en": "Homogenized tobacco"},
    "240399": {"fr": "Autres tabacs transformés", "en": "Other processed tobacco"},
    
    # CHAPITRE 27 - COMBUSTIBLES MINÉRAUX
    "270111": {"fr": "Anthracite", "en": "Anthracite"},
    "270112": {"fr": "Houille bitumineuse", "en": "Bituminous coal"},
    "270119": {"fr": "Autres houilles", "en": "Other coal"},
    "270120": {"fr": "Briquettes de houille", "en": "Coal briquettes"},
    "270210": {"fr": "Lignites", "en": "Lignite"},
    "270220": {"fr": "Lignites agglomérés", "en": "Agglomerated lignite"},
    "270300": {"fr": "Tourbe", "en": "Peat"},
    "270400": {"fr": "Cokes de houille", "en": "Coke from coal"},
    "270500": {"fr": "Gaz de houille", "en": "Coal gas"},
    "270600": {"fr": "Goudrons de houille", "en": "Coal tar"},
    "270710": {"fr": "Benzols", "en": "Benzol"},
    "270720": {"fr": "Toluols", "en": "Toluol"},
    "270730": {"fr": "Xylols", "en": "Xylol"},
    "270740": {"fr": "Naphtalène", "en": "Naphthalene"},
    "270750": {"fr": "Autres mélanges aromatiques", "en": "Other aromatic hydrocarbon mixtures"},
    "270799": {"fr": "Autres huiles de goudron", "en": "Other tar oils"},
    "270810": {"fr": "Brai", "en": "Pitch"},
    "270820": {"fr": "Coke de brai", "en": "Pitch coke"},
    "270900": {"fr": "Huiles brutes de pétrole", "en": "Crude petroleum oils"},
    "271011": {"fr": "Essences pour moteurs légères", "en": "Light motor spirit"},
    "271012": {"fr": "Essences pour moteurs autres", "en": "Other motor spirit"},
    "271019": {"fr": "Autres huiles légères de pétrole", "en": "Other light petroleum oils"},
    "271020": {"fr": "Huiles moyennes de pétrole", "en": "Medium petroleum oils"},
    "271091": {"fr": "Huiles lourdes de pétrole - déchets", "en": "Waste heavy petroleum oils"},
    "271099": {"fr": "Autres huiles lourdes de pétrole", "en": "Other heavy petroleum oils"},
    "271111": {"fr": "Gaz naturel liquéfié", "en": "Liquefied natural gas"},
    "271112": {"fr": "Propane liquéfié", "en": "Liquefied propane"},
    "271113": {"fr": "Butanes liquéfiés", "en": "Liquefied butanes"},
    "271114": {"fr": "Éthylène, propylène, butylène", "en": "Ethylene, propylene, butylene"},
    "271119": {"fr": "Autres gaz de pétrole liquéfiés", "en": "Other LPG"},
    "271121": {"fr": "Gaz naturel à l'état gazeux", "en": "Natural gas in gaseous state"},
    "271129": {"fr": "Autres gaz de pétrole", "en": "Other petroleum gases"},
    "271210": {"fr": "Vaseline", "en": "Petroleum jelly"},
    "271220": {"fr": "Paraffine", "en": "Paraffin wax"},
    "271290": {"fr": "Autres cires minérales", "en": "Other mineral waxes"},
    "271311": {"fr": "Coke de pétrole non calciné", "en": "Non-calcined petroleum coke"},
    "271312": {"fr": "Coke de pétrole calciné", "en": "Calcined petroleum coke"},
    "271320": {"fr": "Bitume de pétrole", "en": "Petroleum bitumen"},
    "271390": {"fr": "Autres résidus de pétrole", "en": "Other petroleum residues"},
    "271410": {"fr": "Schistes bitumineux", "en": "Bituminous shale"},
    "271490": {"fr": "Autres bitumes", "en": "Other bitumen"},
    "271500": {"fr": "Mélanges bitumineux", "en": "Bituminous mixtures"},
    "271600": {"fr": "Énergie électrique", "en": "Electrical energy"},
    
    # CHAPITRE 72 - FONTE, FER ET ACIER
    "720110": {"fr": "Fontes brutes non alliées", "en": "Non-alloy pig iron"},
    "720120": {"fr": "Fontes brutes alliées", "en": "Alloy pig iron"},
    "720150": {"fr": "Fontes spiegel", "en": "Spiegeleisen"},
    "720211": {"fr": "Ferromanganèse >2% carbone", "en": "Ferromanganese >2% carbon"},
    "720219": {"fr": "Ferromanganèse ≤2% carbone", "en": "Ferromanganese ≤2% carbon"},
    "720221": {"fr": "Ferrosilicium >55% silicium", "en": "Ferrosilicon >55% silicon"},
    "720229": {"fr": "Autres ferrosiliciums", "en": "Other ferrosilicon"},
    "720230": {"fr": "Ferrosilicomanganese", "en": "Ferrosilicomanganese"},
    "720241": {"fr": "Ferrochrome >4% carbone", "en": "Ferrochromium >4% carbon"},
    "720249": {"fr": "Autres ferrochromes", "en": "Other ferrochromium"},
    "720250": {"fr": "Ferrosilicochrome", "en": "Ferrosilicochromium"},
    "720260": {"fr": "Ferronickel", "en": "Ferronickel"},
    "720270": {"fr": "Ferromolybdène", "en": "Ferromolybdenum"},
    "720280": {"fr": "Ferrotungstène et ferrosilicotungstène", "en": "Ferrotungsten"},
    "720291": {"fr": "Ferrotitane et ferrosilicotitane", "en": "Ferrotitanium"},
    "720292": {"fr": "Ferrovanadium", "en": "Ferrovanadium"},
    "720293": {"fr": "Ferroniobium", "en": "Ferroniobium"},
    "720299": {"fr": "Autres ferro-alliages", "en": "Other ferro-alloys"},
    "720310": {"fr": "Produits ferreux obtenus par réduction directe", "en": "Ferrous products from direct reduction"},
    "720390": {"fr": "Autres produits ferreux spongieux", "en": "Other spongy ferrous products"},
    "720410": {"fr": "Déchets de fonte", "en": "Waste of cast iron"},
    "720421": {"fr": "Déchets d'aciers inoxydables", "en": "Waste of stainless steel"},
    "720429": {"fr": "Autres déchets d'aciers alliés", "en": "Other alloy steel waste"},
    "720430": {"fr": "Déchets de fer ou acier étamés", "en": "Waste of tinned iron or steel"},
    "720441": {"fr": "Tournures et copeaux", "en": "Turnings and shavings"},
    "720449": {"fr": "Autres déchets de fer ou acier", "en": "Other iron or steel waste"},
    "720450": {"fr": "Déchets lingotés", "en": "Remelting scrap ingots"},
    "720510": {"fr": "Grenailles de fonte", "en": "Granules of pig iron"},
    "720521": {"fr": "Poudres de fontes alliées", "en": "Powders of alloy steel"},
    "720529": {"fr": "Autres poudres de fer ou acier", "en": "Other iron or steel powders"},
    "720610": {"fr": "Lingots de fer ou d'acier non allié", "en": "Non-alloy iron or steel ingots"},
    "720690": {"fr": "Autres fers et aciers non alliés", "en": "Other non-alloy iron and steel"},
    "720711": {"fr": "Demi-produits en fer <0.25% carbone", "en": "Iron semi-products <0.25% carbon"},
    "720712": {"fr": "Autres demi-produits en fer", "en": "Other iron semi-products"},
    "720719": {"fr": "Demi-produits en fer autres", "en": "Other iron semi-finished products"},
    "720720": {"fr": "Demi-produits en fer >0.25% carbone", "en": "Iron semi-products >0.25% carbon"},
    "720810": {"fr": "Produits laminés à chaud en rouleaux", "en": "Hot-rolled products in coils"},
    "720825": {"fr": "Produits laminés à chaud épaisseur ≥4.75mm", "en": "Hot-rolled products thickness ≥4.75mm"},
    "720826": {"fr": "Produits laminés à chaud épaisseur 3-4.75mm", "en": "Hot-rolled products thickness 3-4.75mm"},
    "720827": {"fr": "Produits laminés à chaud épaisseur <3mm", "en": "Hot-rolled products thickness <3mm"},
    "720836": {"fr": "Autres produits laminés à chaud", "en": "Other hot-rolled products"},
    "720837": {"fr": "Produits laminés à chaud épaisseur 4.75-10mm", "en": "Hot-rolled products thickness 4.75-10mm"},
    "720838": {"fr": "Produits laminés à chaud épaisseur 3-4.75mm", "en": "Hot-rolled products 3-4.75mm"},
    "720839": {"fr": "Produits laminés à chaud <3mm", "en": "Hot-rolled products <3mm"},
    "720840": {"fr": "Produits laminés à chaud avec motifs", "en": "Hot-rolled products with patterns"},
    "720851": {"fr": "Produits laminés à froid >3mm", "en": "Cold-rolled products >3mm"},
    "720852": {"fr": "Produits laminés à froid 1-3mm", "en": "Cold-rolled products 1-3mm"},
    "720853": {"fr": "Produits laminés à froid 0.5-1mm", "en": "Cold-rolled products 0.5-1mm"},
    "720854": {"fr": "Produits laminés à froid <0.5mm", "en": "Cold-rolled products <0.5mm"},
    "720890": {"fr": "Autres produits laminés plats", "en": "Other flat-rolled products"},
    
    # CHAPITRE 84 - MACHINES
    "840110": {"fr": "Réacteurs nucléaires", "en": "Nuclear reactors"},
    "840120": {"fr": "Machines pour la séparation isotopique", "en": "Isotope separation machinery"},
    "840130": {"fr": "Éléments combustibles non irradiés", "en": "Fuel elements, non-irradiated"},
    "840140": {"fr": "Parties de réacteurs nucléaires", "en": "Parts of nuclear reactors"},
    "840211": {"fr": "Chaudières à vapeur >45t/h", "en": "Water tube boilers >45t/h"},
    "840212": {"fr": "Chaudières à vapeur ≤45t/h", "en": "Water tube boilers ≤45t/h"},
    "840219": {"fr": "Autres chaudières à vapeur", "en": "Other steam boilers"},
    "840220": {"fr": "Chaudières à eau surchauffée", "en": "Super-heated water boilers"},
    "840290": {"fr": "Parties de chaudières à vapeur", "en": "Parts of steam boilers"},
    "840310": {"fr": "Chaudières pour chauffage central", "en": "Central heating boilers"},
    "840390": {"fr": "Parties de chaudières de chauffage", "en": "Parts of central heating boilers"},
    "840410": {"fr": "Appareils auxiliaires pour chaudières", "en": "Auxiliary plant for boilers"},
    "840420": {"fr": "Condenseurs pour machines à vapeur", "en": "Condensers for steam engines"},
    "840490": {"fr": "Parties d'appareils auxiliaires", "en": "Parts of auxiliary plant"},
    "840510": {"fr": "Générateurs de gaz", "en": "Producer gas generators"},
    "840590": {"fr": "Parties de générateurs de gaz", "en": "Parts of gas generators"},
    "840610": {"fr": "Turbines à vapeur pour propulsion marine", "en": "Steam turbines for marine propulsion"},
    "840681": {"fr": "Autres turbines à vapeur >40MW", "en": "Other steam turbines >40MW"},
    "840682": {"fr": "Autres turbines à vapeur ≤40MW", "en": "Other steam turbines ≤40MW"},
    "840690": {"fr": "Parties de turbines à vapeur", "en": "Parts of steam turbines"},
    "840710": {"fr": "Moteurs d'avions", "en": "Aircraft engines"},
    "840721": {"fr": "Moteurs hors-bord", "en": "Outboard motors"},
    "840729": {"fr": "Autres moteurs pour propulsion marine", "en": "Other marine propulsion engines"},
    "840731": {"fr": "Moteurs à piston ≤50cc", "en": "Spark-ignition engines ≤50cc"},
    "840732": {"fr": "Moteurs à piston 50-250cc", "en": "Spark-ignition engines 50-250cc"},
    "840733": {"fr": "Moteurs à piston 250-1000cc", "en": "Spark-ignition engines 250-1000cc"},
    "840734": {"fr": "Moteurs à piston >1000cc", "en": "Spark-ignition engines >1000cc"},
    "840790": {"fr": "Autres moteurs à piston", "en": "Other spark-ignition engines"},
    "840810": {"fr": "Moteurs diesel pour propulsion marine", "en": "Marine diesel engines"},
    "840820": {"fr": "Moteurs diesel pour véhicules", "en": "Diesel engines for vehicles"},
    "840890": {"fr": "Autres moteurs diesel", "en": "Other diesel engines"},
    "840910": {"fr": "Parties de moteurs d'avions", "en": "Parts of aircraft engines"},
    "840991": {"fr": "Parties de moteurs à piston", "en": "Parts of spark-ignition engines"},
    "840999": {"fr": "Parties d'autres moteurs", "en": "Parts of other engines"},
    "841011": {"fr": "Turbines hydrauliques ≤1000kW", "en": "Hydraulic turbines ≤1000kW"},
    "841012": {"fr": "Turbines hydrauliques 1-10MW", "en": "Hydraulic turbines 1-10MW"},
    "841013": {"fr": "Turbines hydrauliques >10MW", "en": "Hydraulic turbines >10MW"},
    "841090": {"fr": "Parties de turbines hydrauliques", "en": "Parts of hydraulic turbines"},
    "841111": {"fr": "Turboréacteurs ≤25kN", "en": "Turbojets ≤25kN"},
    "841112": {"fr": "Turboréacteurs >25kN", "en": "Turbojets >25kN"},
    "841121": {"fr": "Turbopropulseurs ≤1100kW", "en": "Turboprops ≤1100kW"},
    "841122": {"fr": "Turbopropulseurs >1100kW", "en": "Turboprops >1100kW"},
    "841181": {"fr": "Autres turbines à gaz ≤5000kW", "en": "Other gas turbines ≤5000kW"},
    "841182": {"fr": "Autres turbines à gaz >5000kW", "en": "Other gas turbines >5000kW"},
    "841191": {"fr": "Parties de turboréacteurs", "en": "Parts of turbojets"},
    "841199": {"fr": "Parties d'autres turbines à gaz", "en": "Parts of other gas turbines"},
    "841210": {"fr": "Propulseurs à réaction", "en": "Reaction engines"},
    "841221": {"fr": "Moteurs hydrauliques linéaires", "en": "Linear acting hydraulic motors"},
    "841229": {"fr": "Autres moteurs hydrauliques", "en": "Other hydraulic motors"},
    "841231": {"fr": "Moteurs pneumatiques linéaires", "en": "Linear acting pneumatic motors"},
    "841239": {"fr": "Autres moteurs pneumatiques", "en": "Other pneumatic motors"},
    "841280": {"fr": "Autres moteurs et machines motrices", "en": "Other engines and motors"},
    "841290": {"fr": "Parties de moteurs", "en": "Parts of motors"},
    "841311": {"fr": "Pompes pour carburants", "en": "Fuel pumps"},
    "841319": {"fr": "Autres pompes pour liquides", "en": "Other pumps for liquids"},
    "841320": {"fr": "Pompes à main", "en": "Hand pumps"},
    "841330": {"fr": "Pompes à carburant pour moteurs", "en": "Fuel pumps for engines"},
    "841340": {"fr": "Pompes à béton", "en": "Concrete pumps"},
    "841350": {"fr": "Autres pompes volumétriques", "en": "Other reciprocating pumps"},
    "841360": {"fr": "Autres pompes rotatives", "en": "Other rotary pumps"},
    "841370": {"fr": "Autres pompes centrifuges", "en": "Other centrifugal pumps"},
    "841381": {"fr": "Autres pompes", "en": "Other pumps"},
    "841382": {"fr": "Élévateurs à liquides", "en": "Liquid elevators"},
    "841391": {"fr": "Parties de pompes", "en": "Parts of pumps"},
    "841392": {"fr": "Parties d'élévateurs à liquides", "en": "Parts of liquid elevators"},
    "841410": {"fr": "Pompes à vide", "en": "Vacuum pumps"},
    "841420": {"fr": "Pompes à air à main ou à pédale", "en": "Hand or foot-operated air pumps"},
    "841430": {"fr": "Compresseurs pour équipements frigorifiques", "en": "Compressors for refrigerating equipment"},
    "841440": {"fr": "Compresseurs d'air montés sur châssis", "en": "Air compressors mounted on wheeled chassis"},
    "841451": {"fr": "Ventilateurs de table ≤125W", "en": "Table fans ≤125W"},
    "841459": {"fr": "Autres ventilateurs", "en": "Other fans"},
    "841460": {"fr": "Hottes aspirantes ≤120cm", "en": "Hoods ≤120cm"},
    "841480": {"fr": "Autres pompes à air et compresseurs", "en": "Other air pumps and compressors"},
    "841490": {"fr": "Parties de pompes et compresseurs", "en": "Parts of pumps and compressors"},
    "841510": {"fr": "Machines pour climatisation murales", "en": "Wall-mounted air conditioners"},
    "841520": {"fr": "Machines pour climatisation de véhicules", "en": "Air conditioners for vehicles"},
    "841581": {"fr": "Autres machines pour climatisation avec groupe frigorifique", "en": "Other air conditioners with refrigeration unit"},
    "841582": {"fr": "Autres machines pour climatisation", "en": "Other air conditioning machines"},
    "841583": {"fr": "Machines pour climatisation sans groupe frigorifique", "en": "Air conditioners without refrigeration"},
    "841590": {"fr": "Parties de machines pour climatisation", "en": "Parts of air conditioning machines"},
    
    # CHAPITRE 85 - MACHINES ÉLECTRIQUES
    "850110": {"fr": "Moteurs électriques ≤37.5W", "en": "Electric motors ≤37.5W"},
    "850120": {"fr": "Moteurs universels >37.5W", "en": "Universal motors >37.5W"},
    "850131": {"fr": "Moteurs DC ≤750W", "en": "DC motors ≤750W"},
    "850132": {"fr": "Moteurs DC 750W-75kW", "en": "DC motors 750W-75kW"},
    "850133": {"fr": "Moteurs DC 75-375kW", "en": "DC motors 75-375kW"},
    "850134": {"fr": "Moteurs DC >375kW", "en": "DC motors >375kW"},
    "850140": {"fr": "Autres moteurs AC monophasés", "en": "Other AC single-phase motors"},
    "850151": {"fr": "Moteurs AC polyphasés ≤750W", "en": "AC multi-phase motors ≤750W"},
    "850152": {"fr": "Moteurs AC polyphasés 750W-75kW", "en": "AC multi-phase motors 750W-75kW"},
    "850153": {"fr": "Moteurs AC polyphasés >75kW", "en": "AC multi-phase motors >75kW"},
    "850161": {"fr": "Générateurs AC ≤75kVA", "en": "AC generators ≤75kVA"},
    "850162": {"fr": "Générateurs AC 75-375kVA", "en": "AC generators 75-375kVA"},
    "850163": {"fr": "Générateurs AC 375-750kVA", "en": "AC generators 375-750kVA"},
    "850164": {"fr": "Générateurs AC >750kVA", "en": "AC generators >750kVA"},
    "850211": {"fr": "Groupes électrogènes diesel ≤75kVA", "en": "Diesel generating sets ≤75kVA"},
    "850212": {"fr": "Groupes électrogènes diesel 75-375kVA", "en": "Diesel generating sets 75-375kVA"},
    "850213": {"fr": "Groupes électrogènes diesel >375kVA", "en": "Diesel generating sets >375kVA"},
    "850220": {"fr": "Groupes électrogènes à essence", "en": "Generating sets with spark-ignition engines"},
    "850231": {"fr": "Groupes électrogènes éoliens", "en": "Wind-powered generating sets"},
    "850239": {"fr": "Autres groupes électrogènes", "en": "Other generating sets"},
    "850240": {"fr": "Convertisseurs rotatifs électriques", "en": "Electric rotary converters"},
    "850300": {"fr": "Parties de moteurs et générateurs", "en": "Parts of motors and generators"},
    "850410": {"fr": "Ballasts pour lampes", "en": "Ballasts for discharge lamps"},
    "850421": {"fr": "Transformateurs ≤650kVA", "en": "Liquid dielectric transformers ≤650kVA"},
    "850422": {"fr": "Transformateurs 650kVA-10MVA", "en": "Liquid dielectric transformers 650kVA-10MVA"},
    "850423": {"fr": "Transformateurs >10MVA", "en": "Liquid dielectric transformers >10MVA"},
    "850431": {"fr": "Autres transformateurs ≤1kVA", "en": "Other transformers ≤1kVA"},
    "850432": {"fr": "Autres transformateurs 1-16kVA", "en": "Other transformers 1-16kVA"},
    "850433": {"fr": "Autres transformateurs 16-500kVA", "en": "Other transformers 16-500kVA"},
    "850434": {"fr": "Autres transformateurs >500kVA", "en": "Other transformers >500kVA"},
    "850440": {"fr": "Convertisseurs statiques", "en": "Static converters"},
    "850450": {"fr": "Autres bobines de réactance", "en": "Other inductors"},
    "850490": {"fr": "Parties de transformateurs", "en": "Parts of transformers"},
    "850510": {"fr": "Aimants permanents métalliques", "en": "Permanent magnets of metal"},
    "850511": {"fr": "Aimants permanents en métal", "en": "Permanent magnets, metal"},
    "850519": {"fr": "Autres aimants permanents", "en": "Other permanent magnets"},
    "850520": {"fr": "Accouplements électromagnétiques", "en": "Electromagnetic couplings"},
    "850590": {"fr": "Autres électro-aimants", "en": "Other electro-magnets"},
    "850610": {"fr": "Piles au dioxyde de manganèse", "en": "Manganese dioxide primary cells"},
    "850630": {"fr": "Piles à l'oxyde de mercure", "en": "Mercuric oxide primary cells"},
    "850640": {"fr": "Piles à l'oxyde d'argent", "en": "Silver oxide primary cells"},
    "850650": {"fr": "Piles au lithium", "en": "Lithium primary cells"},
    "850660": {"fr": "Piles zinc-air", "en": "Air-zinc primary cells"},
    "850680": {"fr": "Autres piles", "en": "Other primary cells"},
    "850690": {"fr": "Parties de piles", "en": "Parts of primary cells"},
    "850710": {"fr": "Accumulateurs au plomb pour démarrage", "en": "Lead-acid accumulators for starting"},
    "850720": {"fr": "Autres accumulateurs au plomb", "en": "Other lead-acid accumulators"},
    "850730": {"fr": "Accumulateurs au nickel-cadmium", "en": "Nickel-cadmium accumulators"},
    "850740": {"fr": "Accumulateurs au nickel-fer", "en": "Nickel-iron accumulators"},
    "850750": {"fr": "Accumulateurs au nickel-hydrure", "en": "Nickel-metal hydride accumulators"},
    "850760": {"fr": "Accumulateurs lithium-ion", "en": "Lithium-ion accumulators"},
    "850780": {"fr": "Autres accumulateurs électriques", "en": "Other electric accumulators"},
    "850790": {"fr": "Parties d'accumulateurs", "en": "Parts of accumulators"},
    "851711": {"fr": "Téléphones filaires à combiné sans fil", "en": "Line telephones with cordless handset"},
    "851712": {"fr": "Téléphones pour réseaux cellulaires", "en": "Telephones for cellular networks"},
    "851713": {"fr": "Smartphones", "en": "Smartphones"},
    "851714": {"fr": "Autres téléphones pour réseaux sans fil", "en": "Other wireless network telephones"},
    "851718": {"fr": "Autres téléphones", "en": "Other telephones"},
    "851761": {"fr": "Stations de base", "en": "Base stations"},
    "851762": {"fr": "Machines pour la réception/transmission", "en": "Reception/transmission machines"},
    "851769": {"fr": "Autres appareils de transmission", "en": "Other transmission apparatus"},
    "851770": {"fr": "Parties de téléphones et appareils", "en": "Parts of telephones and apparatus"},
    "852110": {"fr": "Appareils d'enregistrement vidéo à bande", "en": "Video recording apparatus, magnetic tape"},
    "852190": {"fr": "Autres appareils d'enregistrement vidéo", "en": "Other video recording apparatus"},
    "852210": {"fr": "Têtes de lecture", "en": "Pick-up cartridges"},
    "852290": {"fr": "Autres parties d'appareils", "en": "Other parts of apparatus"},
    "852311": {"fr": "Cartes avec bande magnétique", "en": "Cards with magnetic stripe"},
    "852321": {"fr": "Cartes à puce (smart cards)", "en": "Smart cards"},
    "852329": {"fr": "Autres supports magnétiques", "en": "Other magnetic media"},
    "852341": {"fr": "Supports optiques pour enregistrement", "en": "Optical media for recording"},
    "852349": {"fr": "Autres supports optiques", "en": "Other optical media"},
    "852351": {"fr": "Supports à semi-conducteurs", "en": "Solid-state storage media"},
    "852352": {"fr": "Cartes à puce (smart cards)", "en": "Smart cards"},
    "852359": {"fr": "Autres supports à semi-conducteurs", "en": "Other solid-state storage"},
    "852380": {"fr": "Autres supports d'enregistrement", "en": "Other recording media"},
    "852410": {"fr": "Disques pour phonographes", "en": "Gramophone records"},
    "852431": {"fr": "Disques pour systèmes laser", "en": "Discs for laser reading systems"},
    "852432": {"fr": "Disques laser pour lecture", "en": "Laser discs for reading"},
    "852439": {"fr": "Autres disques", "en": "Other discs"},
    "852440": {"fr": "Bandes magnétiques pour son", "en": "Magnetic tapes for sound"},
    "852451": {"fr": "Dispositifs à semi-conducteurs", "en": "Solid-state non-volatile storage"},
    "852452": {"fr": "Cartes à puce", "en": "Smart cards"},
    "852459": {"fr": "Autres dispositifs à semi-conducteurs", "en": "Other solid-state devices"},
    "852491": {"fr": "Autres supports magnétiques", "en": "Other magnetic media"},
    "852499": {"fr": "Autres supports d'enregistrement", "en": "Other recorded media"},
    "852510": {"fr": "Appareils d'émission radio", "en": "Radio transmission apparatus"},
    "852520": {"fr": "Appareils radio avec récepteur", "en": "Radio apparatus with receiver"},
    "852550": {"fr": "Appareils d'émission TV", "en": "Television transmission apparatus"},
    "852560": {"fr": "Appareils TV avec récepteur", "en": "TV apparatus with receiver"},
    "852580": {"fr": "Caméras de télévision", "en": "Television cameras"},
    "852590": {"fr": "Parties d'appareils", "en": "Parts of apparatus"},
    "852610": {"fr": "Appareils radar", "en": "Radar apparatus"},
    "852691": {"fr": "Appareils de radionavigation", "en": "Radio navigational aid apparatus"},
    "852692": {"fr": "Appareils de radiotélécommande", "en": "Radio remote control apparatus"},
    "852712": {"fr": "Récepteurs radio portatifs", "en": "Pocket-size radio receivers"},
    "852713": {"fr": "Autres récepteurs radio", "en": "Other radio receivers"},
    "852719": {"fr": "Autres appareils radio", "en": "Other radio apparatus"},
    "852721": {"fr": "Récepteurs radio pour véhicules", "en": "Radio receivers for motor vehicles"},
    "852729": {"fr": "Autres récepteurs radio pour véhicules", "en": "Other radio receivers for vehicles"},
    "852791": {"fr": "Appareils audio combinés", "en": "Combined audio apparatus"},
    "852792": {"fr": "Autres appareils non combinés", "en": "Other non-combined apparatus"},
    "852799": {"fr": "Autres appareils audio", "en": "Other audio apparatus"},
    "852810": {"fr": "Téléviseurs couleur à tube cathodique", "en": "Colour CRT televisions"},
    "852821": {"fr": "Moniteurs couleur à tube cathodique", "en": "Colour CRT monitors"},
    "852829": {"fr": "Autres moniteurs à tube cathodique", "en": "Other CRT monitors"},
    "852841": {"fr": "Moniteurs à tube cathodique", "en": "CRT monitors"},
    "852842": {"fr": "Appareils avec LCD pouvant recevoir TV", "en": "LCD apparatus capable of receiving TV"},
    "852843": {"fr": "Appareils avec LCD ne pouvant recevoir TV", "en": "LCD apparatus not capable of receiving TV"},
    "852849": {"fr": "Autres moniteurs LCD", "en": "Other LCD monitors"},
    "852851": {"fr": "Autres moniteurs ne pouvant recevoir TV", "en": "Other monitors not capable of TV"},
    "852852": {"fr": "Autres appareils pouvant recevoir TV", "en": "Other apparatus capable of TV"},
    "852859": {"fr": "Autres moniteurs et projecteurs", "en": "Other monitors and projectors"},
    "852861": {"fr": "Projecteurs à tube cathodique", "en": "CRT projectors"},
    "852862": {"fr": "Autres projecteurs LCD", "en": "Other LCD projectors"},
    "852869": {"fr": "Autres projecteurs", "en": "Other projectors"},
    "852871": {"fr": "Appareils TV sans écran", "en": "TV apparatus without display"},
    "852872": {"fr": "Autres appareils TV couleur", "en": "Other colour TV apparatus"},
    "852873": {"fr": "Autres appareils TV noir et blanc", "en": "Other monochrome TV apparatus"},
    "852910": {"fr": "Antennes", "en": "Aerials and antennas"},
    "852990": {"fr": "Parties d'appareils de télécommunication", "en": "Parts of telecommunication apparatus"},
    
    # CHAPITRE 87 - VÉHICULES
    "870110": {"fr": "Motoculteurs", "en": "Pedestrian controlled tractors"},
    "870120": {"fr": "Tracteurs routiers pour semi-remorques", "en": "Road tractors for semi-trailers"},
    "870130": {"fr": "Tracteurs à chenilles", "en": "Track-laying tractors"},
    "870190": {"fr": "Autres tracteurs", "en": "Other tractors"},
    "870210": {"fr": "Véhicules pour ≥10 personnes diesel", "en": "Diesel vehicles for ≥10 persons"},
    "870220": {"fr": "Véhicules pour ≥10 personnes diesel + électrique", "en": "Diesel-electric vehicles for ≥10 persons"},
    "870230": {"fr": "Véhicules pour ≥10 personnes essence", "en": "Spark-ignition vehicles for ≥10 persons"},
    "870240": {"fr": "Véhicules pour ≥10 personnes électriques", "en": "Electric vehicles for ≥10 persons"},
    "870290": {"fr": "Autres véhicules pour ≥10 personnes", "en": "Other vehicles for ≥10 persons"},
    "870310": {"fr": "Véhicules spécialement conçus pour neige", "en": "Vehicles for snow"},
    "870321": {"fr": "Voitures essence ≤1000cc", "en": "Spark-ignition cars ≤1000cc"},
    "870322": {"fr": "Voitures essence 1000-1500cc", "en": "Spark-ignition cars 1000-1500cc"},
    "870323": {"fr": "Voitures essence 1500-3000cc", "en": "Spark-ignition cars 1500-3000cc"},
    "870324": {"fr": "Voitures essence >3000cc", "en": "Spark-ignition cars >3000cc"},
    "870331": {"fr": "Voitures diesel ≤1500cc", "en": "Diesel cars ≤1500cc"},
    "870332": {"fr": "Voitures diesel 1500-2500cc", "en": "Diesel cars 1500-2500cc"},
    "870333": {"fr": "Voitures diesel >2500cc", "en": "Diesel cars >2500cc"},
    "870340": {"fr": "Véhicules hybrides essence-électrique", "en": "Spark-ignition hybrid vehicles"},
    "870350": {"fr": "Véhicules hybrides diesel-électrique", "en": "Diesel-electric hybrid vehicles"},
    "870360": {"fr": "Véhicules électriques", "en": "Electric vehicles"},
    "870370": {"fr": "Autres véhicules", "en": "Other vehicles"},
    "870380": {"fr": "Véhicules à propulsion électrique uniquement", "en": "Vehicles with only electric motor"},
    "870390": {"fr": "Autres voitures", "en": "Other motor cars"},
    "870410": {"fr": "Tombereaux pour utilisation hors-route", "en": "Dumpers for off-highway use"},
    "870421": {"fr": "Véhicules diesel ≤5t", "en": "Diesel vehicles ≤5t"},
    "870422": {"fr": "Véhicules diesel 5-20t", "en": "Diesel vehicles 5-20t"},
    "870423": {"fr": "Véhicules diesel >20t", "en": "Diesel vehicles >20t"},
    "870431": {"fr": "Véhicules essence ≤5t", "en": "Spark-ignition vehicles ≤5t"},
    "870432": {"fr": "Véhicules essence >5t", "en": "Spark-ignition vehicles >5t"},
    "870490": {"fr": "Autres véhicules pour transport de marchandises", "en": "Other goods transport vehicles"},
    "870510": {"fr": "Camions-grues", "en": "Mobile cranes"},
    "870520": {"fr": "Derricks automobiles pour sondage", "en": "Mobile drilling derricks"},
    "870530": {"fr": "Voitures de lutte contre l'incendie", "en": "Fire fighting vehicles"},
    "870540": {"fr": "Camions-bétonnières", "en": "Concrete-mixer lorries"},
    "870590": {"fr": "Autres véhicules spéciaux", "en": "Other special purpose vehicles"},
    "870600": {"fr": "Châssis avec moteurs", "en": "Chassis with engines"},
    "870710": {"fr": "Carrosseries pour voitures", "en": "Bodies for motor cars"},
    "870790": {"fr": "Autres carrosseries", "en": "Other bodies"},
    "870810": {"fr": "Pare-chocs", "en": "Bumpers"},
    "870821": {"fr": "Ceintures de sécurité", "en": "Safety seat belts"},
    "870829": {"fr": "Autres parties de carrosseries", "en": "Other body parts"},
    "870830": {"fr": "Freins et servo-freins", "en": "Brakes and servo-brakes"},
    "870840": {"fr": "Boîtes de vitesses", "en": "Gear boxes"},
    "870850": {"fr": "Essieux moteurs", "en": "Drive-axles"},
    "870860": {"fr": "Essieux non moteurs", "en": "Non-driving axles"},
    "870870": {"fr": "Roues et leurs parties", "en": "Road wheels"},
    "870880": {"fr": "Amortisseurs de suspension", "en": "Suspension shock absorbers"},
    "870891": {"fr": "Radiateurs", "en": "Radiators"},
    "870892": {"fr": "Silencieux et tuyaux d'échappement", "en": "Silencers and exhaust pipes"},
    "870893": {"fr": "Embrayages et leurs parties", "en": "Clutches and parts"},
    "870894": {"fr": "Volants, colonnes et boîtiers de direction", "en": "Steering wheels and columns"},
    "870895": {"fr": "Coussins gonflables de sécurité", "en": "Safety airbags"},
    "870899": {"fr": "Autres parties et accessoires", "en": "Other parts and accessories"},
    "870911": {"fr": "Chariots électriques", "en": "Works trucks, electric"},
    "870919": {"fr": "Autres chariots", "en": "Other works trucks"},
    "870990": {"fr": "Parties de chariots", "en": "Parts of works trucks"},
    "871000": {"fr": "Chars et automobiles blindées", "en": "Tanks and armoured vehicles"},
    "871110": {"fr": "Motocycles ≤50cc", "en": "Motorcycles ≤50cc"},
    "871120": {"fr": "Motocycles 50-250cc", "en": "Motorcycles 50-250cc"},
    "871130": {"fr": "Motocycles 250-500cc", "en": "Motorcycles 250-500cc"},
    "871140": {"fr": "Motocycles 500-800cc", "en": "Motorcycles 500-800cc"},
    "871150": {"fr": "Motocycles >800cc", "en": "Motorcycles >800cc"},
    "871160": {"fr": "Motocycles électriques", "en": "Electric motorcycles"},
    "871190": {"fr": "Autres motocycles", "en": "Other motorcycles"},
    "871200": {"fr": "Bicyclettes et autres cycles", "en": "Bicycles and other cycles"},
    "871310": {"fr": "Fauteuils roulants non mécaniques", "en": "Invalid carriages, not motorized"},
    "871390": {"fr": "Autres fauteuils roulants", "en": "Other invalid carriages"},
    "871411": {"fr": "Selles de motocycles", "en": "Motorcycle saddles"},
    "871419": {"fr": "Autres parties de motocycles", "en": "Other motorcycle parts"},
    "871420": {"fr": "Parties de fauteuils roulants", "en": "Parts of invalid carriages"},
    "871491": {"fr": "Cadres et fourches", "en": "Frames and forks"},
    "871492": {"fr": "Jantes et rayons", "en": "Wheel rims and spokes"},
    "871493": {"fr": "Moyeux et pignons", "en": "Hubs and sprockets"},
    "871494": {"fr": "Freins", "en": "Brakes"},
    "871495": {"fr": "Selles", "en": "Saddles"},
    "871496": {"fr": "Pédales et pédaliers", "en": "Pedals and crank-gear"},
    "871499": {"fr": "Autres parties de cycles", "en": "Other cycle parts"},
    "871500": {"fr": "Landaus, poussettes", "en": "Baby carriages"},
    "871610": {"fr": "Remorques pour l'habitation", "en": "Trailers for housing"},
    "871620": {"fr": "Remorques autochargeuses pour l'agriculture", "en": "Self-loading trailers for agriculture"},
    "871631": {"fr": "Remorques-citernes", "en": "Tanker trailers"},
    "871639": {"fr": "Autres remorques pour transport de marchandises", "en": "Other goods transport trailers"},
    "871640": {"fr": "Autres remorques", "en": "Other trailers"},
    "871680": {"fr": "Autres véhicules non automobiles", "en": "Other non-motorized vehicles"},
    "871690": {"fr": "Parties de remorques", "en": "Parts of trailers"}
}

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def get_hs_chapters() -> Dict:
    """Get all HS chapters (2-digit codes)"""
    return HS_CHAPTERS

def get_hs6_codes() -> Dict:
    """Get all HS6 codes with labels"""
    return HS6_CODES

def get_hs6_code(code: str, language: str = 'fr') -> Optional[Dict]:
    """Get a specific HS6 code with its label"""
    if code in HS6_CODES:
        return {
            "code": code,
            "label": HS6_CODES[code].get(language, HS6_CODES[code].get('fr')),
            "chapter": code[:2],
            "chapter_name": HS_CHAPTERS.get(code[:2], {}).get(language, '')
        }
    return None

def normalize_accent(text: str) -> str:
    """Remove accents from text for search matching"""
    import unicodedata
    return ''.join(
        c for c in unicodedata.normalize('NFD', text)
        if unicodedata.category(c) != 'Mn'
    )

def search_hs_codes(query: str, language: str = 'fr', limit: int = 20) -> List[Dict]:
    """Search HS codes by keyword (accent-insensitive)"""
    query_normalized = normalize_accent(query.lower())
    results = []
    
    for code, labels in HS6_CODES.items():
        label = labels.get(language, labels.get('fr', ''))
        label_normalized = normalize_accent(label.lower())
        if query_normalized in label_normalized or query_normalized in code:
            results.append({
                "code": code,
                "label": label,
                "chapter": code[:2],
                "chapter_name": HS_CHAPTERS.get(code[:2], {}).get(language, '')
            })
            if len(results) >= limit:
                break
    
    return results

def get_codes_by_chapter(chapter: str, language: str = 'fr') -> List[Dict]:
    """Get all HS6 codes for a given chapter"""
    results = []
    for code, labels in HS6_CODES.items():
        if code.startswith(chapter):
            results.append({
                "code": code,
                "label": labels.get(language, labels.get('fr', '')),
                "chapter": chapter,
                "chapter_name": HS_CHAPTERS.get(chapter, {}).get(language, '')
            })
    return results

def get_all_hs_data() -> Dict:
    """Get all HS code data"""
    return {
        "chapters": HS_CHAPTERS,
        "hs6_codes": HS6_CODES,
        "total_chapters": len(HS_CHAPTERS),
        "total_codes": len(HS6_CODES),
        "source": "World Customs Organization (WCO) HS 2022",
        "last_updated": "2025-01-12"
    }
