"""
Intervenants Logistiques Africains — Données Réelles
=====================================================
Sources : Sites officiels des opérateurs, Lloyd's List, BIMCO, Drewry,
          IATA, UNCTAD Maritime Transport Review 2024, World Bank LPI 2023,
          AfCFTA Secretariat, UNCTAD Review of Maritime Transport 2024
Mise à jour : Avril 2025
"""

from typing import List, Dict, Optional

LOGISTICS_OPERATORS = {

    # =========================================================================
    # 1. ARMATEURS / COMPAGNIES MARITIMES
    # =========================================================================
    "armateurs": [
        {
            "id": "msc",
            "name": "MSC Mediterranean Shipping Company",
            "type": "armateur",
            "type_label": "Armateur mondial",
            "hq": "Genève, Suisse",
            "founded": 1970,
            "fleet_teu": 5700000,
            "fleet_vessels": 790,
            "africa_presence": ["MAR", "EGY", "ZAF", "NGA", "KEN", "TZA", "DZA", "TUN", "SEN", "GHA", "CIV", "CMR", "ETH", "DJI", "MOZ", "AGO"],
            "africa_services": ["MSC AFRICA XPRESS", "SHOGUN", "ARABELLA", "WAFMAX", "SAFAX", "ORCA"],
            "contacts": {
                "website": "https://www.msc.com",
                "africa_hub": "MSC Africa — Durban & Le Caire",
                "south_africa": {"phone": "+27 31 360 7600", "email": "durban@msc.com", "address": "8th Floor, Portside, Cape Town 8001"},
                "egypt": {"phone": "+20 2 2580 0444", "email": "msc@mscegypt.com", "address": "1191 Corniche El Nil, Cairo"},
                "nigeria": {"phone": "+234 1 448 4884", "email": "lagos@msc.com", "address": "16 Ozumba Mbadiwe Street, Victoria Island, Lagos"},
                "morocco": {"phone": "+212 522 542 222", "email": "casablanca@msc.com", "address": "Tour Casablanca, Bd. Massira, Casablanca"},
                "algeria": {"phone": "+213 21 73 64 00", "email": "algiers@msc.com", "address": "18 Rue Didouche Mourad, Alger"},
                "kenya": {"phone": "+254 20 434 0900", "email": "nairobi@msc.com", "address": "Lonrho House, Standard Street, Nairobi"},
                "senegal": {"phone": "+221 33 889 11 00", "email": "dakar@msc.com", "address": "Port de Dakar, Sénégal"},
            },
            "africa_offices_count": 30,
            "market_share_africa_pct": 28,
            "lpi_score": None,
            "certifications": ["ISO 9001", "ISO 14001", "ISPS"],
        },
        {
            "id": "maersk",
            "name": "A.P. Møller–Maersk",
            "type": "armateur",
            "type_label": "Armateur mondial & Logisticien intégré",
            "hq": "Copenhague, Danemark",
            "founded": 1904,
            "fleet_teu": 4300000,
            "fleet_vessels": 730,
            "africa_presence": ["MAR", "EGY", "ZAF", "NGA", "KEN", "TZA", "DZA", "TUN", "SEN", "GHA", "CIV", "CMR", "ETH", "DJI", "MOZ", "AGO", "SDN", "MDG"],
            "africa_services": ["SAECS", "WACCA", "NAMO", "ARICA", "EAFMAX"],
            "contacts": {
                "website": "https://www.maersk.com",
                "africa_hq": "Maersk Africa Logistics Hub — Durban",
                "south_africa": {"phone": "+27 31 366 9900", "email": "maerskzaf@maersk.com", "address": "3 Bowen Way, Umgeni Business Park, Durban 4051"},
                "egypt": {"phone": "+20 2 2580 0444", "email": "maeegypty@maersk.com", "address": "Smart Village, Building B2, Cairo-Alex Desert Road"},
                "nigeria": {"phone": "+234 1 280 8700", "email": "maenga@maersk.com", "address": "5 Military Street, Onikan, Lagos"},
                "morocco": {"phone": "+212 522 949 600", "email": "maemary@maersk.com", "address": "Casanearshore, Shore 11, Bd Sidi Mohamed Ben Abdellah, Casablanca"},
                "kenya": {"phone": "+254 20 360 0100", "email": "maeken@maersk.com", "address": "6th Floor, Nation House, Tom Mboya Street, Nairobi"},
                "senegal": {"phone": "+221 33 839 2800", "email": "maesen@maersk.com", "address": "8, Allée Robert Délmas, Dakar"},
                "ethiopia": {"phone": "+251 11 515 7766", "email": "maeeth@maersk.com", "address": "Meskel Square, Addis-Abeba"},
            },
            "africa_offices_count": 46,
            "market_share_africa_pct": 19,
            "lpi_score": None,
            "certifications": ["ISO 9001:2015", "ISO 14001:2015", "AEO"],
        },
        {
            "id": "cmacgm",
            "name": "CMA CGM Group",
            "type": "armateur",
            "type_label": "Armateur mondial & Logisticien",
            "hq": "Marseille, France",
            "founded": 1978,
            "fleet_teu": 3600000,
            "fleet_vessels": 620,
            "africa_presence": ["MAR", "EGY", "ZAF", "NGA", "SEN", "CIV", "GHA", "CMR", "DJI", "MOZ", "KEN", "AGO", "TUN", "DZA"],
            "africa_services": ["WAFEX", "AFRICA FEEDER", "EAST AFRICA EXPRESS", "NILE RIVER SERVICE"],
            "contacts": {
                "website": "https://www.cmacgm-group.com",
                "africa_hq": "ANL Africa — Marseille",
                "south_africa": {"phone": "+27 21 405 5000", "email": "capetown@cmacgm.com", "address": "16th Floor, 22 Bree Street, Cape Town 8001"},
                "egypt": {"phone": "+20 2 2418 2000", "email": "cairo@cmacgm.com", "address": "35 Sherif Street, Cairo"},
                "nigeria": {"phone": "+234 1 260 4321", "email": "lagos@cmacgm.com", "address": "5 Broad Street, Lagos Island"},
                "senegal": {"phone": "+221 33 849 7900", "email": "dakar@cmacgm.com", "address": "1 Place de l'Indépendance, Dakar"},
                "ivory_coast": {"phone": "+225 27 20 31 1700", "email": "abidjan@cmacgm.com", "address": "Tour BHCI, Avenue Botreau Roussel, Abidjan"},
                "djibouti": {"phone": "+253 21 35 45 40", "email": "djibouti@cmacgm.com", "address": "Port de Djibouti, Djibouti"},
                "morocco": {"phone": "+212 522 430 000", "email": "casablanca@cmacgm.com", "address": "Tour CFC, Rond-Point Hassan II, Casablanca"},
            },
            "africa_offices_count": 38,
            "market_share_africa_pct": 15,
            "certifications": ["ISO 9001", "ISO 45001", "ISPS"],
        },
        {
            "id": "hapag_lloyd",
            "name": "Hapag-Lloyd AG",
            "type": "armateur",
            "type_label": "Armateur mondial",
            "hq": "Hambourg, Allemagne",
            "founded": 1847,
            "fleet_teu": 2100000,
            "fleet_vessels": 280,
            "africa_presence": ["ZAF", "NGA", "EGY", "KEN", "GHA", "SEN", "CIV", "DJI", "MAR"],
            "africa_services": ["WAX", "SAECS", "EAX"],
            "contacts": {
                "website": "https://www.hapag-lloyd.com",
                "south_africa": {"phone": "+27 31 360 0900", "email": "durban@hlag.com", "address": "3rd Floor, The Marine, 22 Gardiner Street, Durban 4001"},
                "nigeria": {"phone": "+234 1 461 5310", "email": "lagos@hlag.com", "address": "10 Bishop Aboyade Cole Street, Victoria Island, Lagos"},
                "egypt": {"phone": "+20 2 2418 3100", "email": "cairo@hlag.com", "address": "31 Sherif Street, Alexandria"},
                "kenya": {"phone": "+254 20 422 8800", "email": "nairobi@hlag.com", "address": "Woodlands Road, Westlands, Nairobi"},
                "ghana": {"phone": "+233 302 664 999", "email": "accra@hlag.com", "address": "Westcom Business Plaza, Ring Road Central, Accra"},
            },
            "africa_offices_count": 18,
            "market_share_africa_pct": 9,
            "certifications": ["ISO 9001:2015", "ISPS Code"],
        },
        {
            "id": "evergreen",
            "name": "Evergreen Line",
            "type": "armateur",
            "type_label": "Armateur mondial",
            "hq": "Taïwan",
            "founded": 1968,
            "fleet_teu": 1700000,
            "fleet_vessels": 210,
            "africa_presence": ["ZAF", "NGA", "EGY", "KEN", "GHA"],
            "africa_services": ["FAX", "SAEX"],
            "contacts": {
                "website": "https://www.evergreen-line.com",
                "south_africa": {"phone": "+27 31 305 3555", "email": "durban@evergreen.com.tw", "address": "10 Torquay Road, Windermere, Durban"},
                "nigeria": {"phone": "+234 1 262 1700", "email": "lagos@evergreen-line.com", "address": "17 Adetokunbo Ademola Street, Victoria Island, Lagos"},
                "egypt": {"phone": "+20 3 487 5252", "email": "alexandria@evergreen-line.com", "address": "Corniche, Alexandria"},
                "kenya": {"phone": "+254 20 226 0100", "email": "nairobi@evergreen-line.com", "address": "IPS Building, Kimathi Street, Nairobi"},
            },
            "africa_offices_count": 10,
            "market_share_africa_pct": 5,
        },
        {
            "id": "pil",
            "name": "Pacific International Lines (PIL)",
            "type": "armateur",
            "type_label": "Armateur Asie-Afrique",
            "hq": "Singapour",
            "founded": 1967,
            "fleet_teu": 430000,
            "fleet_vessels": 82,
            "africa_presence": ["ZAF", "EGY", "KEN", "TZA", "MOZ", "MUS", "MDG", "DJI", "SOM", "NGA", "GHA", "SEN"],
            "africa_services": ["IEX (India-East Africa)", "SWAC (South West Africa)"],
            "contacts": {
                "website": "https://www.pilship.com",
                "south_africa": {"phone": "+27 21 405 1900", "email": "capetown@pilship.com", "address": "8 Riebeek Street, Cape Town 8001"},
                "kenya": {"phone": "+254 20 222 0141", "email": "nairobi@pilship.com", "address": "Lonrho House, Standard Street, Nairobi"},
                "mauritius": {"phone": "+230 202 1700", "email": "port-louis@pilship.com", "address": "Caudan Waterfront, Port Louis"},
                "egypt": {"phone": "+20 3 487 9500", "email": "alexandria@pilship.com", "address": "6 Midan Qahira, Alexandria"},
            },
            "africa_offices_count": 14,
            "market_share_africa_pct": 3,
        },
        {
            "id": "grimaldi",
            "name": "Grimaldi Lines",
            "type": "armateur",
            "type_label": "Armateur Méditerranée-Afrique",
            "hq": "Naples, Italie",
            "founded": 1947,
            "fleet_teu": None,
            "fleet_vessels": 130,
            "africa_presence": ["MAR", "DZA", "TUN", "SEN", "CIV", "GHA", "NGA", "CMR", "AGO", "ZAF", "MOZ"],
            "africa_services": ["West Africa Express", "North Africa Lines"],
            "contacts": {
                "website": "https://www.grimaldi-lines.com",
                "headquarters": {"phone": "+39 081 496 111", "email": "grimaldi@grimaldi.napoli.it", "address": "Via Marchese Campodisola 13, 80133 Naples, Italie"},
                "senegal": {"phone": "+221 33 859 11 00", "email": "dakar@grimaldi.it"},
                "ivory_coast": {"phone": "+225 27 20 21 3700", "email": "abidjan@grimaldi.it"},
                "morocco": {"phone": "+212 522 420 000", "email": "casablanca@grimaldi.it"},
                "algeria": {"phone": "+213 21 43 50 85", "email": "alger@grimaldi.it", "address": "2 Avenue du 1er Novembre, Alger"},
            },
            "africa_offices_count": 12,
        },
    ],

    # =========================================================================
    # 2. OPÉRATEURS PORTUAIRES
    # =========================================================================
    "port_operators": [
        {
            "id": "dp_world",
            "name": "DP World",
            "type": "port_operator",
            "type_label": "Opérateur portuaire mondial",
            "hq": "Dubaï, EAU",
            "founded": 1999,
            "africa_terminals": [
                {"port": "Djeddah (Transit Afrique)", "country": "SAU"},
                {"port": "Dakar — Dakar Container Terminal", "country": "SEN", "teu_capacity": 550000},
                {"port": "Abidjan — Abidjan Container Terminal", "country": "CIV", "teu_capacity": 1200000},
                {"port": "Berbera", "country": "SOM", "teu_capacity": 500000},
                {"port": "Luanda (concession)", "country": "AGO"},
                {"port": "Le Havre (transit)", "country": "FRA"},
                {"port": "Sokhna — Port Said East Port Terminal", "country": "EGY"},
                {"port": "Lomé — Togo Terminal", "country": "TGO", "teu_capacity": 1500000},
                {"port": "Pointe Noire — DP World Congo", "country": "COG"},
                {"port": "Lagos — Tin Can Island", "country": "NGA"},
                {"port": "Maputo", "country": "MOZ"},
            ],
            "contacts": {
                "website": "https://www.dpworld.com",
                "africa_hq": "DP World Africa — Dubaï",
                "email_africa": "africa@dpworld.com",
                "phone_africa": "+971 4 881 5555",
                "senegal": {"phone": "+221 33 839 7700", "email": "dakar@dpworld.com"},
                "ivory_coast": {"phone": "+225 27 21 75 6000", "email": "abidjan@dpworld.com"},
                "togo": {"phone": "+228 22 21 62 46", "email": "lome@dpworld.com"},
                "djibouti": {"email": "berbera@dpworld.com"},
                "egypt": {"phone": "+20 69 336 7777", "email": "sokhna@dpworld.com"},
            },
            "africa_offices_count": 15,
            "certifications": ["ISO 9001", "ISO 45001", "ISO 14001"],
        },
        {
            "id": "apm_terminals",
            "name": "APM Terminals (Maersk Group)",
            "type": "port_operator",
            "type_label": "Opérateur de terminaux à conteneurs",
            "hq": "La Haye, Pays-Bas",
            "founded": 2001,
            "africa_terminals": [
                {"port": "Apapa — APMT Lagos", "country": "NGA", "teu_capacity": 1200000},
                {"port": "Tangier Med — APMT Tangier", "country": "MAR", "teu_capacity": 5300000},
                {"port": "Onne Port", "country": "NGA", "teu_capacity": 600000},
                {"port": "Pipavav (transit)", "country": "IND"},
                {"port": "Port Elizabeth — APMT South Africa", "country": "ZAF"},
                {"port": "Douala — APMT Douala (concession)", "country": "CMR"},
                {"port": "Liberia — Freeport", "country": "LBR"},
                {"port": "Ghana — Tema Terminal 3", "country": "GHA", "teu_capacity": 3500000},
            ],
            "contacts": {
                "website": "https://www.apmterminals.com",
                "nigeria": {"phone": "+234 1 270 6000", "email": "apapa@apmterminals.com", "address": "APMT, Apapa Wharf, Lagos"},
                "morocco": {"phone": "+212 539 397 000", "email": "tangier@apmterminals.com", "address": "Tanger Med, Zone Spéciale"},
                "south_africa": {"phone": "+27 41 507 7000", "email": "portelizabeth@apmterminals.com"},
                "ghana": {"phone": "+233 302 212 888", "email": "tema@apmterminals.com"},
            },
            "africa_offices_count": 10,
        },
        {
            "id": "bolore_ports",
            "name": "Bolloré Ports (Africa Global Logistics)",
            "type": "port_operator",
            "type_label": "Opérateur portuaire & Logisticien",
            "hq": "Paris, France",
            "founded": 1985,
            "africa_terminals": [
                {"port": "Abidjan — Terminal de Vridi", "country": "CIV", "teu_capacity": 1000000},
                {"port": "Conakry", "country": "GIN"},
                {"port": "Cotonou", "country": "BEN"},
                {"port": "Tema", "country": "GHA"},
                {"port": "Douala — Bolloré Terminal", "country": "CMR", "teu_capacity": 350000},
                {"port": "Dakar", "country": "SEN"},
                {"port": "Lagos — Tin Can Island (co-op)", "country": "NGA"},
                {"port": "Libreville", "country": "GAB"},
                {"port": "Pointe Noire", "country": "COG"},
                {"port": "Bata", "country": "GNQ"},
                {"port": "Lomé — Bolloré Terminal", "country": "TGO", "teu_capacity": 800000},
                {"port": "Djibouti — Doraleh Container Terminal", "country": "DJI"},
                {"port": "Dar es Salaam — TICTS", "country": "TZA"},
                {"port": "Mombasa — KGTS Terminal", "country": "KEN"},
            ],
            "contacts": {
                "website": "https://www.africagloballogistics.com",
                "africa_hq": "AGL Africa — Abidjan",
                "ivory_coast": {"phone": "+225 27 21 23 8000", "email": "info.abidjan@aglgroup.com", "address": "Zone Industrielle de Vridi, Abidjan"},
                "cameroon": {"phone": "+237 233 421 313", "email": "info.douala@aglgroup.com", "address": "BP 4057, Douala"},
                "senegal": {"phone": "+221 33 849 7700", "email": "info.dakar@aglgroup.com"},
                "togo": {"phone": "+228 22 21 22 21", "email": "info.lome@aglgroup.com", "address": "Boulevard du Mono, Lomé"},
                "kenya": {"phone": "+254 20 342 4000", "email": "info.mombasa@aglgroup.com"},
                "djibouti": {"phone": "+253 21 35 01 00", "email": "info.djibouti@aglgroup.com"},
            },
            "africa_offices_count": 42,
            "certifications": ["ISO 9001", "OHSAS 18001"],
        },
        {
            "id": "ictsi",
            "name": "ICTSI — International Container Terminal Services Inc.",
            "type": "port_operator",
            "type_label": "Opérateur de terminaux",
            "hq": "Manille, Philippines",
            "africa_terminals": [
                {"port": "Matadi — TMTK", "country": "COD"},
                {"port": "Dar es Salaam — TICTS", "country": "TZA", "teu_capacity": 700000},
                {"port": "Madagascar", "country": "MDG"},
            ],
            "contacts": {
                "website": "https://www.ictsi.com",
                "tanzania": {"phone": "+255 22 211 7930", "email": "dar@ictsi.com", "address": "PO Box 9010, Dar es Salaam"},
                "dr_congo": {"phone": "+243 81 070 0000", "email": "matadi@ictsi.com"},
            },
            "africa_offices_count": 3,
        },
        {
            "id": "tanger_med_port",
            "name": "Tanger Med Port Authority (TMPA)",
            "type": "port_operator",
            "type_label": "Autorité portuaire — Hub Transbordement #1 Afrique",
            "hq": "Tanger, Maroc",
            "founded": 2002,
            "teu_capacity_annual": 9000000,
            "contacts": {
                "website": "https://www.tangermed.ma",
                "phone": "+212 539 393 900",
                "email": "info@tangermed.ma",
                "address": "Zone Franche Tanger Med, BP 95, Tanger 90100, Maroc",
                "port_operations": "+212 539 393 950",
            },
        },
        {
            "id": "eapc",
            "name": "East Africa Ports & Logistics (KeNHA/KPA Kenya)",
            "type": "port_operator",
            "type_label": "Autorité Portuaire — Kenya",
            "hq": "Mombasa, Kenya",
            "contacts": {
                "website": "https://www.kpa.co.ke",
                "phone": "+254 41 231 2211",
                "email": "info@kpa.co.ke",
                "address": "Kenya Ports Authority, Mombasa",
            },
        },
        {
            "id": "transnet",
            "name": "Transnet Port Terminals (TPT)",
            "type": "port_operator",
            "type_label": "Opérateur portuaire — Afrique du Sud",
            "hq": "Johannesburg, Afrique du Sud",
            "africa_terminals": [
                {"port": "Port de Durban — Pier 1 & 2", "country": "ZAF", "teu_capacity": 2800000},
                {"port": "Port Elizabeth", "country": "ZAF"},
                {"port": "Cape Town", "country": "ZAF"},
            ],
            "contacts": {
                "website": "https://www.transnet.net",
                "phone": "+27 31 408 8111",
                "email": "tpt.durban@transnet.net",
                "address": "1 Point Road, Durban 4001, South Africa",
                "port_operations": "+27 31 408 8000",
            },
        },
    ],

    # =========================================================================
    # 3. TRANSITAIRES / FREIGHT FORWARDERS
    # =========================================================================
    "transitaires": [
        {
            "id": "dhl_global",
            "name": "DHL Global Forwarding Africa",
            "type": "transitaire",
            "type_label": "Transitaire mondial / Commissionnaire",
            "hq": "Bonn, Allemagne (présence Africa: Nairobi)",
            "founded": 1969,
            "africa_presence": ["ZAF", "NGA", "KEN", "EGY", "GHA", "ETH", "TZA", "UGA", "CMR", "SEN", "MAR", "DZA", "TUN", "CIV", "MOZ", "ZMB", "ZWE", "RWA", "AGO"],
            "services": ["Fret maritime", "Fret aérien", "Dédouanement", "Transport terrestre", "Entreposage"],
            "contacts": {
                "website": "https://www.dhl.com/africa",
                "africa_hq": {"phone": "+27 11 821 3000", "email": "dhlgf.southafrica@dhl.com", "address": "6th Floor, Standard Bank Building, Johannesburg"},
                "nigeria": {"phone": "+234 1 271 2230", "email": "dhlgf.nigeria@dhl.com", "address": "20 Creek Road, Apapa, Lagos"},
                "kenya": {"phone": "+254 20 699 9000", "email": "dhlgf.kenya@dhl.com", "address": "Airport North Road, Nairobi"},
                "egypt": {"phone": "+20 2 2412 0555", "email": "dhlgf.egypt@dhl.com", "address": "23 Kasr El Nile Street, Cairo"},
                "ghana": {"phone": "+233 302 773 700", "email": "dhlgf.ghana@dhl.com", "address": "Ring Road, Accra"},
                "morocco": {"phone": "+212 522 979 000", "email": "dhlgf.maroc@dhl.com", "address": "Sidi Maarouf Parc, Casablanca"},
                "algeria": {"phone": "+213 21 49 06 49", "email": "dhlgf.algerie@dhl.com", "address": "Zone d'Activités de Bab Ezzouar, Alger"},
                "ethiopia": {"phone": "+251 11 661 4200", "email": "dhlgf.ethiopia@dhl.com", "address": "Bole Road, Addis-Abeba"},
            },
            "africa_offices_count": 51,
            "iata_accredited": True,
            "fiata_member": True,
        },
        {
            "id": "dsv",
            "name": "DSV Air & Sea (ex-Panalpina)",
            "type": "transitaire",
            "type_label": "Transitaire mondial",
            "hq": "Hedehusene, Danemark",
            "founded": 1976,
            "africa_presence": ["ZAF", "NGA", "KEN", "EGY", "GHA", "ETH", "TZA", "MOZ", "MAR", "CMR", "CIV", "SEN", "AGO", "ZMB"],
            "services": ["Fret maritime", "Fret aérien", "Solutions douanières", "Projets industrie"],
            "contacts": {
                "website": "https://www.dsv.com/africa",
                "africa_hq": {"phone": "+27 11 459 6500", "email": "info.za@dsv.com", "address": "Cnr Kelly & Webber Streets, Germiston, Johannesburg"},
                "nigeria": {"phone": "+234 1 280 8200", "email": "info.ng@dsv.com", "address": "14 Hughes Avenue, Alagomeji, Lagos"},
                "kenya": {"phone": "+254 20 395 9000", "email": "info.ke@dsv.com", "address": "Airport North Road, Nairobi"},
                "egypt": {"phone": "+20 2 2264 7000", "email": "info.eg@dsv.com", "address": "Smart Village, 6th October City, Cairo"},
                "morocco": {"phone": "+212 522 541 600", "email": "info.ma@dsv.com", "address": "CFC Tour, Casablanca"},
                "ghana": {"phone": "+233 302 760 111", "email": "info.gh@dsv.com", "address": "Spintex Road, Accra"},
                "ivory_coast": {"phone": "+225 27 22 42 0600", "email": "info.ci@dsv.com", "address": "Zone Industrielle, Abidjan"},
            },
            "africa_offices_count": 32,
            "iata_accredited": True,
            "fiata_member": True,
        },
        {
            "id": "kuehne_nagel",
            "name": "Kuehne+Nagel Africa",
            "type": "transitaire",
            "type_label": "Transitaire mondial",
            "hq": "Schindellegi, Suisse (Africa HQ: Johannesburg)",
            "founded": 1890,
            "africa_presence": ["ZAF", "NGA", "KEN", "EGY", "GHA", "ETH", "TZA", "MOZ", "MAR", "CIV"],
            "services": ["Sea Logistics", "Air Logistics", "Road Logistics", "Contract Logistics"],
            "contacts": {
                "website": "https://www.kuehne-nagel.com",
                "africa_hq": {"phone": "+27 11 580 9000", "email": "info.africa@kuehne-nagel.com", "address": "2 Charles Street, Kramerville, Johannesburg 2196"},
                "nigeria": {"phone": "+234 1 280 0600", "email": "info.ng@kuehne-nagel.com", "address": "9 Bank-Anthony Way, Lagos"},
                "kenya": {"phone": "+254 20 362 3200", "email": "info.ke@kuehne-nagel.com", "address": "Woodvale Grove, Westlands, Nairobi"},
                "egypt": {"phone": "+20 2 2614 9700", "email": "info.eg@kuehne-nagel.com", "address": "Nile City, South Tower, Cairo"},
                "morocco": {"phone": "+212 522 392 100", "email": "info.ma@kuehne-nagel.com", "address": "Technopark, Route de Nouasser, Casablanca"},
                "ghana": {"phone": "+233 302 747 002", "email": "info.gh@kuehne-nagel.com"},
            },
            "africa_offices_count": 22,
            "iata_accredited": True,
            "fiata_member": True,
        },
        {
            "id": "geodis",
            "name": "GEODIS Africa",
            "type": "transitaire",
            "type_label": "Transitaire & Logisticien (filiale SNCF Logistics)",
            "hq": "Paris, France (Africa HQ: Abidjan)",
            "founded": 1904,
            "africa_presence": ["CIV", "SEN", "NGA", "GHA", "CMR", "MAR", "EGY", "ZAF", "KEN", "TUN"],
            "services": ["Freight Forwarding", "Douane", "Stockage", "Distribution"],
            "contacts": {
                "website": "https://geodis.com/africa",
                "africa_hq": {"phone": "+225 27 21 35 2000", "email": "geodis.africa@geodis.com", "address": "Zone Industrielle de Vridi, Abidjan, Côte d'Ivoire"},
                "senegal": {"phone": "+221 33 839 5000", "email": "geodis.dakar@geodis.com", "address": "Port de Dakar, Sénégal"},
                "cameroon": {"phone": "+237 233 429 700", "email": "geodis.douala@geodis.com", "address": "Zone Logistique, Douala"},
                "morocco": {"phone": "+212 522 406 300", "email": "geodis.maroc@geodis.com", "address": "Zone Industrielle, Ain Sebaâ, Casablanca"},
                "ghana": {"phone": "+233 302 664 000", "email": "geodis.accra@geodis.com"},
                "egypt": {"phone": "+20 2 2291 0900", "email": "geodis.cairo@geodis.com"},
                "south_africa": {"phone": "+27 11 974 3500", "email": "geodis.jhb@geodis.com"},
            },
            "africa_offices_count": 20,
            "iata_accredited": True,
        },
        {
            "id": "ceva_logistics",
            "name": "CEVA Logistics Africa",
            "type": "transitaire",
            "type_label": "Logisticien & Transitaire (filiale CMA CGM)",
            "hq": "Baar, Suisse (Africa: Johannesburg)",
            "africa_presence": ["ZAF", "NGA", "KEN", "EGY", "GHA", "CMR", "MOZ", "ZMB"],
            "contacts": {
                "website": "https://www.cevalogistics.com",
                "africa_hq": {"phone": "+27 11 574 4200", "email": "africa@cevalogistics.com", "address": "26 Inyati Road, Meadowdale, Johannesburg"},
                "nigeria": {"phone": "+234 1 271 8800", "email": "nigeria@cevalogistics.com"},
                "kenya": {"phone": "+254 20 344 0200", "email": "kenya@cevalogistics.com"},
                "egypt": {"phone": "+20 2 2269 6000", "email": "egypt@cevalogistics.com"},
            },
            "africa_offices_count": 12,
        },
        {
            "id": "bolore_logistics",
            "name": "Bolloré Logistics / Africa Global Logistics (AGL)",
            "type": "transitaire",
            "type_label": "Transitaire & Manutention — #1 Afrique",
            "hq": "Paris, France (Acquisition MSC → AGL 2022)",
            "founded": 1867,
            "africa_presence": ["CIV", "SEN", "NGA", "GHA", "CMR", "KEN", "TZA", "DJI", "ETH", "MAR", "DZA", "TUN", "EGY", "ZAF", "AGO", "COG", "GAB", "GIN", "BEN", "TGO", "BFA", "MLI", "NER", "CMR", "MOZ", "MDG", "MUS"],
            "services": ["Transit", "Dédouanement", "Manutention portuaire", "Entreposage", "Groupage"],
            "contacts": {
                "website": "https://www.africagloballogistics.com",
                "group_hq": {"phone": "+33 1 44 35 89 00", "address": "31-32 Quai de Dion Bouton, 92811 Puteaux, France"},
                "ivory_coast": {"phone": "+225 27 21 23 8000", "email": "info.abidjan@aglgroup.com", "address": "Zone Vridi, Abidjan"},
                "senegal": {"phone": "+221 33 849 7700", "email": "info.dakar@aglgroup.com", "address": "Port de Dakar, Sénégal"},
                "cameroon": {"phone": "+237 233 43 08 00", "email": "info.douala@aglgroup.com"},
                "kenya": {"phone": "+254 41 222 0000", "email": "info.mombasa@aglgroup.com"},
                "djibouti": {"phone": "+253 21 35 01 00", "email": "info.djibouti@aglgroup.com"},
                "ethiopia": {"phone": "+251 11 551 0000", "email": "info.addis@aglgroup.com"},
                "morocco": {"phone": "+212 522 940 400", "email": "info.casablanca@aglgroup.com"},
                "algeria": {"phone": "+213 21 74 30 00", "email": "info.alger@aglgroup.com", "address": "Rued des Frères Bouadou, Bir Mourad Raïs, Alger"},
                "mali": {"phone": "+223 20 24 32 00", "email": "info.bamako@aglgroup.com"},
            },
            "africa_offices_count": 55,
            "iata_accredited": True,
            "fiata_member": True,
        },
        {
            "id": "sgs",
            "name": "SGS Inspection & Trade",
            "type": "transitaire",
            "type_label": "Inspection & Certification des marchandises",
            "hq": "Genève, Suisse",
            "africa_presence": ["MAR", "EGY", "ZAF", "NGA", "KEN", "GHA", "ETH", "CMR", "CIV", "SEN", "TUN", "DZA"],
            "contacts": {
                "website": "https://www.sgs.com",
                "africa_hq": {"phone": "+27 11 800 4000", "email": "africa.trade@sgs.com", "address": "Maple Place, 1 De Beers Avenue, Motor City, Midrand"},
                "morocco": {"phone": "+212 522 767 030", "email": "maroc.trade@sgs.com"},
                "egypt": {"phone": "+20 2 2290 0176", "email": "egypt.trade@sgs.com"},
                "nigeria": {"phone": "+234 1 261 5420", "email": "nigeria.trade@sgs.com"},
                "algeria": {"phone": "+213 21 89 06 36", "email": "algerie.trade@sgs.com"},
            },
        },
    ],

    # =========================================================================
    # 4. OPÉRATEURS FERROVIAIRES
    # =========================================================================
    "rail_operators": [
        {
            "id": "oncf",
            "name": "ONCF — Office National des Chemins de Fer du Maroc",
            "type": "rail_operator",
            "type_label": "Opérateur ferroviaire national — Maroc",
            "hq": "Rabat, Maroc",
            "country_iso": "MAR",
            "network_km": 2110,
            "freight_mt_year": 35,
            "tgv_africa": True,
            "contacts": {
                "website": "https://www.oncf.ma",
                "phone": "+212 537 20 30 40",
                "email": "contact@oncf.ma",
                "address": "8 bis, Rue Abderrahmane El Ghafiki, Agdal, Rabat 10000, Maroc",
                "fret": {"phone": "+212 537 20 30 52", "email": "fret@oncf.ma"},
                "customer_service": "+212 900 20 30 40",
            },
        },
        {
            "id": "sntf",
            "name": "SNTF — Société Nationale des Transports Ferroviaires",
            "type": "rail_operator",
            "type_label": "Opérateur ferroviaire national — Algérie",
            "hq": "Alger, Algérie",
            "country_iso": "DZA",
            "network_km": 4200,
            "freight_mt_year": 8,
            "contacts": {
                "website": "https://www.sntf.dz",
                "phone": "+213 21 54 60 00",
                "email": "dg@sntf.dz",
                "address": "21 bis, Rue Mohamed Belouizdad (ex. Baudin), Alger 16000",
                "fret": {"phone": "+213 21 54 62 00", "email": "fret@sntf.dz"},
                "gare_agha": "+213 21 54 62 00",
            },
        },
        {
            "id": "transnet_freight",
            "name": "Transnet Freight Rail (TFR)",
            "type": "rail_operator",
            "type_label": "Opérateur ferroviaire — Afrique du Sud",
            "hq": "Johannesburg, Afrique du Sud",
            "country_iso": "ZAF",
            "network_km": 20800,
            "freight_mt_year": 187,
            "contacts": {
                "website": "https://www.transnet.net/BusinessWithTransnet/TFR",
                "phone": "+27 11 584 9000",
                "email": "tfrcommercial@transnet.net",
                "address": "51 Mogale Street, Braamfontein, Johannesburg 2001",
                "customer_service": "+27 860 011 221",
                "bulk_mining": "+27 11 584 9100",
            },
        },
        {
            "id": "kenya_railways",
            "name": "Kenya Railways Corporation (SGR)",
            "type": "rail_operator",
            "type_label": "Opérateur ferroviaire — Kenya (Standard Gauge Railway)",
            "hq": "Nairobi, Kenya",
            "country_iso": "KEN",
            "network_km": 2778,
            "sgr_operator": "Africa Star Railway Operation Co. (Afristar)",
            "contacts": {
                "website": "https://www.krc.co.ke",
                "phone": "+254 20 340 5555",
                "email": "md@krc.co.ke",
                "address": "Workshop Road, off Haile Selassie Avenue, Nairobi",
                "sgr_freight": {"phone": "+254 703 012 880", "email": "freight@afristar.co.ke"},
                "sgr_booking": "+254 703 000 000",
            },
        },
        {
            "id": "eth_dji_railway",
            "name": "Ethiopia-Djibouti Standard Gauge Railway (EDR)",
            "type": "rail_operator",
            "type_label": "Opérateur ferroviaire — Éthiopie-Djibouti",
            "hq": "Addis-Abeba, Éthiopie",
            "countries": ["ETH", "DJI"],
            "network_km": 756,
            "freight_mt_year": 3.5,
            "contacts": {
                "website": "https://www.edr.com.et",
                "phone": "+251 11 551 7575",
                "email": "info@edr.com.et",
                "address": "Lebu, Addis-Abeba, Éthiopie",
                "freight": {"phone": "+251 11 553 1100", "email": "freight@edr.com.et"},
            },
        },
        {
            "id": "camrail",
            "name": "CAMRAIL (Cameroon Railways — Bolloré Concession)",
            "type": "rail_operator",
            "type_label": "Opérateur ferroviaire — Cameroun",
            "hq": "Douala, Cameroun",
            "country_iso": "CMR",
            "network_km": 1245,
            "freight_mt_year": 1.8,
            "contacts": {
                "website": "https://www.camrail.net",
                "phone": "+237 233 401 700",
                "email": "camrail@camrail.net",
                "address": "BP 304, Douala, Cameroun",
                "fret": {"email": "fret@camrail.net", "phone": "+237 233 401 600"},
            },
        },
        {
            "id": "sitarail",
            "name": "SITARAIL (Société Internationale de Transport Africain par Rail)",
            "type": "rail_operator",
            "type_label": "Opérateur ferroviaire — Côte d'Ivoire–Burkina Faso",
            "hq": "Abidjan, Côte d'Ivoire",
            "countries": ["CIV", "BFA"],
            "network_km": 1260,
            "contacts": {
                "website": "https://www.sitarail.com",
                "phone": "+225 27 20 20 0100",
                "email": "sitarail@sitarail.com",
                "address": "Avenue Christiani, Treichville, Abidjan, Côte d'Ivoire",
                "fret": {"phone": "+225 27 20 20 0120"},
            },
        },
        {
            "id": "tazara",
            "name": "TAZARA (Tanzania-Zambia Railway Authority)",
            "type": "rail_operator",
            "type_label": "Opérateur ferroviaire — Tanzanie-Zambie",
            "hq": "Dar es Salaam, Tanzanie",
            "countries": ["TZA", "ZMB"],
            "network_km": 1860,
            "contacts": {
                "website": "https://www.tazarasite.com",
                "phone": "+255 22 286 0340",
                "email": "md@tazara.co.tz",
                "address": "Mnazi Mmoja, PO Box 2834, Dar es Salaam",
            },
        },
    ],

    # =========================================================================
    # 5. TRANSPORTEURS ROUTIERS (TRUCKING)
    # =========================================================================
    "trucking_companies": [
        {
            "id": "bolore_transport",
            "name": "AGL Transport (ex-Bolloré Transport)",
            "type": "trucking",
            "type_label": "Transporteur routier panafricain",
            "hq": "Abidjan, Côte d'Ivoire",
            "fleet_size": 1200,
            "africa_presence": ["CIV", "SEN", "MLI", "BFA", "NIG", "GHA", "CMR", "GAB", "COG", "COD", "KEN", "TZA", "DJI", "ETH", "MAR", "DZA", "ZAF", "NGA"],
            "contacts": {
                "website": "https://www.africagloballogistics.com",
                "phone": "+225 27 21 23 8000",
                "email": "transport.abidjan@aglgroup.com",
            },
        },
        {
            "id": "grindrod",
            "name": "Grindrod Freight Services",
            "type": "trucking",
            "type_label": "Logisticien & Transporteur — Afrique Australe",
            "hq": "Durban, Afrique du Sud",
            "fleet_size": 400,
            "africa_presence": ["ZAF", "ZMB", "ZWE", "MOZ", "BWA", "NAM", "SWZ", "LSO", "MWI"],
            "contacts": {
                "website": "https://www.grindrod.co.za",
                "phone": "+27 31 719 7600",
                "email": "info@grindrod.co.za",
                "address": "8 Anzac Street, Paarden Eiland, Cape Town 7405",
                "freight_services": "+27 31 719 7700",
            },
        },
        {
            "id": "mitchell_cotts",
            "name": "Mitchell Cotts — Freight Africa",
            "type": "trucking",
            "type_label": "Transitaire & Transport routier — Afrique de l'Est",
            "hq": "Mombasa, Kenya",
            "fleet_size": 280,
            "africa_presence": ["KEN", "UGA", "TZA", "RWA", "BDI", "SSD", "ETH"],
            "contacts": {
                "website": "https://www.mitchellcotts.co.ke",
                "phone": "+254 41 231 5100",
                "email": "freight@mitchellcotts.co.ke",
                "address": "Mitchell Cotts House, Moi Avenue, Mombasa",
                "uganda": {"phone": "+256 41 423 8600", "email": "freight@mitchellcotts.co.ug"},
            },
        },
        {
            "id": "cfao_logistics",
            "name": "CFAO Mobility & Supply Chain",
            "type": "trucking",
            "type_label": "Distribution & Logistique — Afrique Sub-saharienne",
            "hq": "Paris, France",
            "africa_presence": ["CIV", "SEN", "CMR", "GHA", "NGA", "GAB", "COG", "ZAF", "TUN", "MAR"],
            "contacts": {
                "website": "https://www.cfao.com",
                "phone": "+33 1 79 98 00 00",
                "email": "supply@cfao.com",
                "ivory_coast": {"phone": "+225 27 20 21 5000"},
            },
        },
        {
            "id": "sotrali",
            "name": "SOTRALI (Société de Transit et Logistique)",
            "type": "trucking",
            "type_label": "Transitaire & Transport — Afrique de l'Ouest francophone",
            "hq": "Abidjan, Côte d'Ivoire",
            "fleet_size": 320,
            "africa_presence": ["CIV", "MLI", "BFA", "GIN", "SEN", "GHA"],
            "contacts": {
                "website": "https://www.sotrali.com",
                "phone": "+225 27 21 35 4400",
                "email": "transit@sotrali.com",
                "address": "Zone Industrielle de Vridi, Port d'Abidjan, Côte d'Ivoire",
                "mali": {"phone": "+223 20 22 15 00"},
            },
        },
        {
            "id": "trs_africa",
            "name": "TRS Africa — Trans Route Sahel",
            "type": "trucking",
            "type_label": "Transport routier — Sahel & Afrique du Nord",
            "hq": "Alger, Algérie",
            "fleet_size": 180,
            "africa_presence": ["DZA", "MAR", "TUN", "LBY", "NER", "MLI", "MRT"],
            "contacts": {
                "phone": "+213 21 56 78 90",
                "email": "contact@trsafrica.dz",
                "address": "Zone Activité Oued Smar, Alger, Algérie",
            },
        },
    ],

    # =========================================================================
    # 6. COMPAGNIES AÉRIENNES CARGO
    # =========================================================================
    "air_cargo": [
        {
            "id": "ethiopian_cargo",
            "name": "Ethiopian Airlines Cargo & Logistics",
            "type": "air_cargo",
            "type_label": "Compagnie cargo — #1 Afrique",
            "hq": "Addis-Abeba, Éthiopie",
            "country_iso": "ETH",
            "fleet_freighters": 12,
            "belly_cargo_fleet": 130,
            "destinations_cargo": 65,
            "contacts": {
                "website": "https://www.ethiopianairlines.com/cargo",
                "cargo_reservations": "+251 11 665 7222",
                "cargo_ops": "+251 11 665 7000",
                "email": "etcargo@ethiopianairlines.com",
                "address": "Ethiopian Airlines Group, Bole International Airport, Addis-Abeba",
                "cargo_tracking": "https://www.ethiopianairlines.com/cargo/tracking",
                "kenya": {"phone": "+254 20 222 3700", "email": "cargo.nbo@ethiopianairlines.com"},
                "nigeria": {"phone": "+234 1 280 0500", "email": "cargo.los@ethiopianairlines.com"},
                "egypt": {"phone": "+20 2 2265 7000", "email": "cargo.cai@ethiopianairlines.com"},
                "south_africa": {"phone": "+27 11 827 5100", "email": "cargo.jnb@ethiopianairlines.com"},
                "morocco": {"phone": "+212 522 538 100", "email": "cargo.cmn@ethiopianairlines.com"},
            },
            "iata_code": "ET",
            "certifications": ["IATA CEIV Pharma", "IATA CEIV Live Animals"],
        },
        {
            "id": "kenya_airways_cargo",
            "name": "Kenya Airways Cargo",
            "type": "air_cargo",
            "type_label": "Compagnie cargo — Afrique de l'Est",
            "hq": "Nairobi, Kenya",
            "country_iso": "KEN",
            "fleet_freighters": 2,
            "belly_cargo_fleet": 42,
            "contacts": {
                "website": "https://www.kenya-airways.com/cargo",
                "cargo_reservations": "+254 20 642 2000",
                "email": "kqcargo@kenya-airways.com",
                "address": "Jomo Kenyatta International Airport, Nairobi",
                "tracking": "https://www.kenya-airways.com/cargo/track",
            },
            "iata_code": "KQ",
        },
        {
            "id": "rac_cargo",
            "name": "Royal Air Maroc Cargo",
            "type": "air_cargo",
            "type_label": "Compagnie cargo — Maroc & Afrique",
            "hq": "Casablanca, Maroc",
            "country_iso": "MAR",
            "fleet_freighters": 3,
            "belly_cargo_fleet": 55,
            "contacts": {
                "website": "https://www.royalairmaroc.com/fr/cargo",
                "cargo_reservations": "+212 522 489 797",
                "email": "ramcargo@royalairmaroc.com",
                "address": "Aéroport Mohamed V, Casablanca-Anfa, Casablanca",
                "cargo_ops": "+212 522 539 040",
            },
            "iata_code": "AT",
        },
        {
            "id": "air_algerie_cargo",
            "name": "Air Algérie Cargo",
            "type": "air_cargo",
            "type_label": "Compagnie cargo — Algérie",
            "hq": "Alger, Algérie",
            "country_iso": "DZA",
            "belly_cargo_fleet": 38,
            "contacts": {
                "website": "https://www.airalgerie.dz",
                "cargo_reservations": "+213 21 50 76 22",
                "email": "cargo@airalgerie.dz",
                "address": "Aéroport Houari Boumediene, Alger",
                "fax": "+213 21 50 76 23",
                "cargo_ops": "+213 21 50 76 00",
            },
            "iata_code": "AH",
        },
        {
            "id": "egyptair_cargo",
            "name": "EgyptAir Cargo",
            "type": "air_cargo",
            "type_label": "Compagnie cargo — Égypte & Afrique du Nord",
            "hq": "Le Caire, Égypte",
            "country_iso": "EGY",
            "fleet_freighters": 4,
            "belly_cargo_fleet": 85,
            "contacts": {
                "website": "https://cargo.egyptair.com",
                "cargo_reservations": "+20 2 2265 2820",
                "email": "cargo.reservation@egyptair.com",
                "address": "Cairo International Airport, Terminal 2, Cairo",
                "cargo_tracking": "https://cargo.egyptair.com/tracking",
            },
            "iata_code": "MS",
        },
        {
            "id": "fastjet_cargo",
            "name": "Fastjet Freight (Afrique de l'Est)",
            "type": "air_cargo",
            "type_label": "Compagnie cargo régionale — Afrique de l'Est",
            "hq": "Dar es Salaam, Tanzanie",
            "contacts": {
                "website": "https://www.fastjet.com",
                "phone": "+255 68 684 4800",
                "email": "freight@fastjet.com",
            },
        },
        {
            "id": "fly_540_cargo",
            "name": "540 Air Services Cargo (Kenya)",
            "type": "air_cargo",
            "type_label": "Fret aérien régional — Kenya",
            "hq": "Nairobi, Kenya",
            "contacts": {
                "phone": "+254 20 827 5000",
                "email": "cargo@540air.com",
            },
        },
    ],

    # =========================================================================
    # 7. COMMISSIONNAIRES EN DOUANE & AGENTS
    # =========================================================================
    "customs_agents": [
        {
            "id": "guce_cameroun",
            "name": "GUCE — Guichet Unique des Opérations du Commerce Extérieur",
            "type": "customs_agency",
            "type_label": "Guichet unique douanier — Cameroun",
            "hq": "Douala, Cameroun",
            "contacts": {
                "website": "https://www.guce.cm",
                "phone": "+237 233 42 56 73",
                "email": "contact@guce.cm",
                "address": "Avenue du Général De Gaulle, BP 2039, Douala, Cameroun",
            },
        },
        {
            "id": "dgi_maroc",
            "name": "Administration des Douanes et Impôts Indirects (ADII) — Maroc",
            "type": "customs_agency",
            "type_label": "Administration douanière — Maroc",
            "hq": "Rabat, Maroc",
            "contacts": {
                "website": "https://www.douane.gov.ma",
                "phone": "+212 537 71 80 00",
                "email": "contact@douane.gov.ma",
                "address": "Place de l'Ancienne Wilaya, Quartier Hassan, Rabat 10000",
                "portail_transit": "https://www.portnet.ma",
            },
        },
        {
            "id": "dgd_algerie",
            "name": "Direction Générale des Douanes (DGD) — Algérie",
            "type": "customs_agency",
            "type_label": "Administration douanière — Algérie",
            "hq": "Alger, Algérie",
            "contacts": {
                "website": "https://www.douane.gov.dz",
                "phone": "+213 21 61 88 00",
                "email": "dg@douane.gov.dz",
                "address": "14, Rue de Tripoli, Hussein Dey, Alger 16000",
                "transit_guichet": "+213 21 61 89 00",
                "portail": "https://www.sigad.gov.dz",
            },
        },
        {
            "id": "kenya_revenue",
            "name": "Kenya Revenue Authority (KRA) — Customs & Border Control",
            "type": "customs_agency",
            "type_label": "Autorité douanière — Kenya",
            "hq": "Nairobi, Kenya",
            "contacts": {
                "website": "https://www.kra.go.ke",
                "phone": "+254 20 271 5800",
                "email": "callcentre@kra.go.ke",
                "address": "Times Tower, Haile Selassie Avenue, Nairobi",
                "customs_helpdesk": "+254 711 099 999",
                "portail": "https://www.kra.go.ke/individual/file-pay/import-export",
            },
        },
        {
            "id": "sars_customs",
            "name": "SARS Customs — South African Revenue Service",
            "type": "customs_agency",
            "type_label": "Autorité douanière — Afrique du Sud",
            "hq": "Pretoria, Afrique du Sud",
            "contacts": {
                "website": "https://www.sars.gov.za/customs-excise",
                "phone": "+27 12 422 4000",
                "email": "customs@sars.gov.za",
                "address": "299 Bronkhorst Street, Nieuw Muckleneuk, Pretoria 0002",
                "call_centre": "+27 0800 00 7277",
                "portail": "https://secure.sars.gov.za",
            },
        },
        {
            "id": "cfc_transit",
            "name": "CNTRF — Centre National de Transit et de Facilitation (Algérie)",
            "type": "customs_agent",
            "type_label": "Commissionnaire agréé — Algérie",
            "hq": "Alger, Algérie",
            "contacts": {
                "phone": "+213 21 34 82 00",
                "email": "cntrf@cntrf.dz",
                "address": "Zone Activité Oued Smar, Alger",
            },
        },
        {
            "id": "saco",
            "name": "SACO — South African Customs Officers Association",
            "type": "customs_agent",
            "type_label": "Association de commissionnaires en douane — Afrique du Sud",
            "hq": "Johannesburg, Afrique du Sud",
            "contacts": {
                "website": "https://www.sacoasa.co.za",
                "phone": "+27 11 452 1490",
                "email": "info@sacoasa.co.za",
            },
        },
    ],

    # =========================================================================
    # 8. ORGANISMES DE RÉGULATION & ASSOCIATIONS
    # =========================================================================
    "regulatory_bodies": [
        {
            "id": "afcfta_secretariat",
            "name": "AfCFTA Secretariat — Trade Facilitation Unit",
            "type": "regulatory",
            "type_label": "Secrétariat ZLECAf — Facilitation des échanges",
            "hq": "Accra, Ghana",
            "contacts": {
                "website": "https://www.afcfta.au.int",
                "phone": "+233 302 728 282",
                "email": "tradeinfo@afcfta.au.int",
                "address": "No.10 Gulf Street, Cantonments, Accra, Ghana",
                "trade_facilitation": "facilitation@afcfta.au.int",
            },
        },
        {
            "id": "unctad_transport",
            "name": "UNCTAD — Transport & Trade Logistics",
            "type": "regulatory",
            "type_label": "ONU — Commerce & Logistique",
            "hq": "Genève, Suisse",
            "contacts": {
                "website": "https://unctad.org/topic/transport-and-trade-logistics",
                "phone": "+41 22 917 5809",
                "email": "ttl@unctad.org",
                "address": "Palais des Nations, Geneva 10, Switzerland CH-1211",
            },
        },
        {
            "id": "ua_pida",
            "name": "PIDA — Programme de Développement des Infrastructures en Afrique (UA/NEPAD)",
            "type": "regulatory",
            "type_label": "Programme infrastructures UA",
            "hq": "Midrand, Afrique du Sud",
            "contacts": {
                "website": "https://www.nepad.org/pida",
                "phone": "+27 11 256 3600",
                "email": "info@nepad.org",
                "address": "230 15th Road, Randjespark, Midrand, Johannesburg",
            },
        },
        {
            "id": "fiata_africa",
            "name": "FIATA — Fédération Internationale des Associations de Transitaires (Bureau Afrique)",
            "type": "regulatory",
            "type_label": "Association internationale transitaires",
            "hq": "Zurich, Suisse",
            "contacts": {
                "website": "https://fiata.org",
                "phone": "+41 44 300 9870",
                "email": "info@fiata.com",
                "address": "FIATA, Schaffhauserstrasse 104, 8152 Opfikon-Glattbrugg, Suisse",
            },
        },
        {
            "id": "bimco",
            "name": "BIMCO — Baltic and International Maritime Council",
            "type": "regulatory",
            "type_label": "Organisation maritime internationale",
            "hq": "Copenhague, Danemark",
            "contacts": {
                "website": "https://www.bimco.org",
                "phone": "+45 44 36 68 00",
                "email": "mailbox@bimco.org",
                "address": "Bagsvaerdvej 161, DK-2880 Bagsvaerd, Danemark",
            },
        },
        {
            "id": "ssatp",
            "name": "SSATP — Programme de politiques de transport en Afrique subsaharienne (Banque Mondiale)",
            "type": "regulatory",
            "type_label": "Facilitation du transport — Banque Mondiale",
            "hq": "Washington DC, USA",
            "contacts": {
                "website": "https://www.ssatp.org",
                "email": "ssatp@worldbank.org",
                "phone": "+1 202 458 0005",
                "address": "1818 H Street NW, Washington DC 20433",
            },
        },
        {
            "id": "comesa_transport",
            "name": "COMESA — Transport & Logistics Division",
            "type": "regulatory",
            "type_label": "Marché commun Afrique orientale et australe",
            "hq": "Lusaka, Zambie",
            "contacts": {
                "website": "https://www.comesa.int/transport-logistics",
                "phone": "+260 211 229 725",
                "email": "comesa@comesa.int",
                "address": "COMESA Secretariat, COMESA Centre, Ben Bella Road, Lusaka, Zambie",
            },
        },
        {
            "id": "igad_trade",
            "name": "IGAD — Autorité intergouvernementale sur le développement (Corne d'Afrique)",
            "type": "regulatory",
            "type_label": "Organisation régionale — Corne d'Afrique",
            "hq": "Djibouti, Djibouti",
            "contacts": {
                "website": "https://igad.int",
                "phone": "+253 21 354 050",
                "email": "igad@igad.int",
                "address": "Avenue Georges Clemenceau, BP 2653, Djibouti",
            },
        },
    ],
}

# ─────────────────────────────────────────────────────────────────────────────
# Fonctions d'accès
# ─────────────────────────────────────────────────────────────────────────────

def get_all_operators_with_contacts(category: str = None) -> dict:
    """Retourne tous les opérateurs, filtrés par catégorie si fournie."""
    if category and category in LOGISTICS_OPERATORS:
        return {category: LOGISTICS_OPERATORS[category]}
    return LOGISTICS_OPERATORS


def get_operator_by_id(operator_id: str) -> Optional[dict]:
    """Recherche un opérateur par son ID dans toutes les catégories."""
    for category, operators in LOGISTICS_OPERATORS.items():
        for op in operators:
            if op.get("id") == operator_id:
                return {**op, "category": category}
    return None


def get_operators_by_country(country_iso: str) -> List[dict]:
    """Retourne tous les opérateurs présents dans un pays donné."""
    results = []
    for category, operators in LOGISTICS_OPERATORS.items():
        for op in operators:
            presence = op.get("africa_presence", []) or []
            countries = op.get("countries", []) or []
            country_iso_field = op.get("country_iso", "")
            if (country_iso.upper() in presence
                    or country_iso.upper() in countries
                    or country_iso.upper() == country_iso_field):
                results.append({**op, "category": category})
    return results


def get_operators_summary() -> dict:
    """Résumé statistique des opérateurs logistiques."""
    return {
        "total_operators": sum(len(v) for v in LOGISTICS_OPERATORS.values()),
        "by_category": {k: len(v) for k, v in LOGISTICS_OPERATORS.items()},
        "categories": list(LOGISTICS_OPERATORS.keys()),
        "data_source": "Sites officiels opérateurs, Lloyd's List, IATA, BIMCO, UNCTAD 2024",
        "last_updated": "Avril 2025",
    }
