"""
SADC Regional Constants
========================
Core constants for the Southern African Development Community (SADC)
regional intelligence and tariff system.

16 SADC member states organised by phase:
  Phase 1 – SACU Customs Union (5)
  Phase 2 – Resource Economies (4)
  Phase 3 – Island Nations (3)
  Phase 4 – Emerging Markets (4)
"""

from datetime import datetime

# ---------------------------------------------------------------------------
# Member-state definitions
# ---------------------------------------------------------------------------

SADC_COUNTRIES = {
    # ---- Phase 1: SACU Customs Union ----
    "ZAF": {
        "country_code": "ZAF",
        "country_name": "South Africa",
        "iso2": "ZA",
        "flag": "🇿🇦",
        "capital": "Pretoria / Cape Town / Bloemfontein",
        "currency": "ZAR",
        "currency_name": "South African Rand",
        "phase": 1,
        "group": "SACU",
        "economy_focus": "diversified_industrial_services",
        "gdp_usd_billion": 380.0,
        "population_million": 60.0,
        "is_sacu": True,
        "is_ldc": False,
        "is_island": False,
        "dual_membership": [],
        "primary_customs_source": "https://www.sars.gov.za",
        "secondary_sources": [
            "https://www.itac.org.za",
            "https://www.dti.gov.za",
        ],
    },
    "BWA": {
        "country_code": "BWA",
        "country_name": "Botswana",
        "iso2": "BW",
        "flag": "🇧🇼",
        "capital": "Gaborone",
        "currency": "BWP",
        "currency_name": "Botswana Pula",
        "phase": 1,
        "group": "SACU",
        "economy_focus": "diamonds_mining_services",
        "gdp_usd_billion": 19.0,
        "population_million": 2.6,
        "is_sacu": True,
        "is_ldc": False,
        "is_island": False,
        "dual_membership": [],
        "primary_customs_source": "https://burs.org.bw",
        "secondary_sources": ["https://www.gov.bw"],
    },
    "NAM": {
        "country_code": "NAM",
        "country_name": "Namibia",
        "iso2": "NA",
        "flag": "🇳🇦",
        "capital": "Windhoek",
        "currency": "NAD",
        "currency_name": "Namibian Dollar",
        "phase": 1,
        "group": "SACU",
        "economy_focus": "mining_logistics_fishing",
        "gdp_usd_billion": 12.0,
        "population_million": 2.6,
        "is_sacu": True,
        "is_ldc": False,
        "is_island": False,
        "dual_membership": [],
        "primary_customs_source": "https://www.namra.org.na",
        "secondary_sources": ["https://mti.gov.na"],
    },
    "LSO": {
        "country_code": "LSO",
        "country_name": "Lesotho",
        "iso2": "LS",
        "flag": "🇱🇸",
        "capital": "Maseru",
        "currency": "LSL",
        "currency_name": "Lesotho Loti",
        "phase": 1,
        "group": "SACU",
        "economy_focus": "textile_manufacturing_water",
        "gdp_usd_billion": 2.5,
        "population_million": 2.2,
        "is_sacu": True,
        "is_ldc": True,
        "is_island": False,
        "dual_membership": [],
        "primary_customs_source": "https://www.lra.org.ls",
        "secondary_sources": ["https://www.gov.ls"],
    },
    "SWZ": {
        "country_code": "SWZ",
        "country_name": "Eswatini",
        "iso2": "SZ",
        "flag": "🇸🇿",
        "capital": "Mbabane / Lobamba",
        "currency": "SZL",
        "currency_name": "Swazi Lilangeni",
        "phase": 1,
        "group": "SACU",
        "economy_focus": "sugar_manufacturing_forestry",
        "gdp_usd_billion": 4.7,
        "population_million": 1.1,
        "is_sacu": True,
        "is_ldc": False,
        "is_island": False,
        "dual_membership": [],
        "primary_customs_source": "https://www.sra.org.sz",
        "secondary_sources": ["https://www.gov.sz"],
    },
    # ---- Phase 2: Resource Economies ----
    "AGO": {
        "country_code": "AGO",
        "country_name": "Angola",
        "iso2": "AO",
        "flag": "🇦🇴",
        "capital": "Luanda",
        "currency": "AOA",
        "currency_name": "Angolan Kwanza",
        "phase": 2,
        "group": "Resource Economies",
        "economy_focus": "oil_diamonds_reconstruction",
        "gdp_usd_billion": 78.0,
        "population_million": 35.0,
        "is_sacu": False,
        "is_ldc": True,
        "is_island": False,
        "dual_membership": [],
        "primary_customs_source": "https://alfandega.gov.ao",
        "secondary_sources": ["https://minfin.gov.ao"],
    },
    "ZMB": {
        "country_code": "ZMB",
        "country_name": "Zambia",
        "iso2": "ZM",
        "flag": "🇿🇲",
        "capital": "Lusaka",
        "currency": "ZMW",
        "currency_name": "Zambian Kwacha",
        "phase": 2,
        "group": "Resource Economies",
        "economy_focus": "copper_agriculture_energy",
        "gdp_usd_billion": 21.0,
        "population_million": 19.5,
        "is_sacu": False,
        "is_ldc": True,
        "is_island": False,
        "dual_membership": ["COMESA"],
        "primary_customs_source": "https://www.zra.org.zm",
        "secondary_sources": ["https://mcti.gov.zm"],
    },
    "ZWE": {
        "country_code": "ZWE",
        "country_name": "Zimbabwe",
        "iso2": "ZW",
        "flag": "🇿🇼",
        "capital": "Harare",
        "currency": "ZWG",
        "currency_name": "Zimbabwe Gold",
        "phase": 2,
        "group": "Resource Economies",
        "economy_focus": "mining_agriculture_manufacturing",
        "gdp_usd_billion": 26.0,
        "population_million": 15.0,
        "is_sacu": False,
        "is_ldc": False,
        "is_island": False,
        "dual_membership": ["COMESA"],
        "primary_customs_source": "https://www.zimra.co.zw",
        "secondary_sources": ["https://www.zimtradeafrica.com"],
    },
    "COD": {
        "country_code": "COD",
        "country_name": "Democratic Republic of the Congo",
        "iso2": "CD",
        "flag": "🇨🇩",
        "capital": "Kinshasa",
        "currency": "CDF",
        "currency_name": "Congolese Franc",
        "phase": 2,
        "group": "Resource Economies",
        "economy_focus": "minerals_agriculture_forestry",
        "gdp_usd_billion": 65.0,
        "population_million": 100.0,
        "is_sacu": False,
        "is_ldc": True,
        "is_island": False,
        "dual_membership": ["EAC", "SADC"],
        "primary_customs_source": "https://www.dgrad.cd",
        "secondary_sources": ["https://www.finances.gouv.cd"],
    },
    # ---- Phase 3: Island Nations ----
    "MUS": {
        "country_code": "MUS",
        "country_name": "Mauritius",
        "iso2": "MU",
        "flag": "🇲🇺",
        "capital": "Port Louis",
        "currency": "MUR",
        "currency_name": "Mauritian Rupee",
        "phase": 3,
        "group": "Island Nations",
        "economy_focus": "services_manufacturing_tourism",
        "gdp_usd_billion": 14.0,
        "population_million": 1.3,
        "is_sacu": False,
        "is_ldc": False,
        "is_island": True,
        "dual_membership": ["COMESA"],
        "primary_customs_source": "https://www.mra.mu",
        "secondary_sources": ["https://edbmauritius.org"],
    },
    "SYC": {
        "country_code": "SYC",
        "country_name": "Seychelles",
        "iso2": "SC",
        "flag": "🇸🇨",
        "capital": "Victoria",
        "currency": "SCR",
        "currency_name": "Seychellois Rupee",
        "phase": 3,
        "group": "Island Nations",
        "economy_focus": "tourism_fisheries_finance",
        "gdp_usd_billion": 2.1,
        "population_million": 0.1,
        "is_sacu": False,
        "is_ldc": False,
        "is_island": True,
        "dual_membership": ["COMESA"],
        "primary_customs_source": "https://src.gov.sc",
        "secondary_sources": ["https://investseychelles.com"],
    },
    "COM": {
        "country_code": "COM",
        "country_name": "Comoros",
        "iso2": "KM",
        "flag": "🇰🇲",
        "capital": "Moroni",
        "currency": "KMF",
        "currency_name": "Comorian Franc",
        "phase": 3,
        "group": "Island Nations",
        "economy_focus": "agriculture_fisheries_tourism",
        "gdp_usd_billion": 1.3,
        "population_million": 0.9,
        "is_sacu": False,
        "is_ldc": True,
        "is_island": True,
        "dual_membership": [],
        "primary_customs_source": "https://dgdcom.km",
        "secondary_sources": [],
    },
    # ---- Phase 4: Emerging Markets ----
    "MOZ": {
        "country_code": "MOZ",
        "country_name": "Mozambique",
        "iso2": "MZ",
        "flag": "🇲🇿",
        "capital": "Maputo",
        "currency": "MZN",
        "currency_name": "Mozambican Metical",
        "phase": 4,
        "group": "Emerging Markets",
        "economy_focus": "energy_agriculture_logistics",
        "gdp_usd_billion": 18.0,
        "population_million": 33.0,
        "is_sacu": False,
        "is_ldc": True,
        "is_island": False,
        "dual_membership": ["COMESA"],
        "primary_customs_source": "https://www.at.gov.mz",
        "secondary_sources": ["https://www.cei.gov.mz"],
    },
    "MDG": {
        "country_code": "MDG",
        "country_name": "Madagascar",
        "iso2": "MG",
        "flag": "🇲🇬",
        "capital": "Antananarivo",
        "currency": "MGA",
        "currency_name": "Malagasy Ariary",
        "phase": 4,
        "group": "Emerging Markets",
        "economy_focus": "vanilla_textiles_mining",
        "gdp_usd_billion": 14.0,
        "population_million": 28.0,
        "is_sacu": False,
        "is_ldc": True,
        "is_island": True,
        "dual_membership": ["COMESA"],
        "primary_customs_source": "https://www.douanes.mg",
        "secondary_sources": ["https://edbm.mg"],
    },
    "MWI": {
        "country_code": "MWI",
        "country_name": "Malawi",
        "iso2": "MW",
        "flag": "🇲🇼",
        "capital": "Lilongwe",
        "currency": "MWK",
        "currency_name": "Malawian Kwacha",
        "phase": 4,
        "group": "Emerging Markets",
        "economy_focus": "tobacco_agriculture_mining",
        "gdp_usd_billion": 12.0,
        "population_million": 20.0,
        "is_sacu": False,
        "is_ldc": True,
        "is_island": False,
        "dual_membership": ["COMESA"],
        "primary_customs_source": "https://www.mra.mw",
        "secondary_sources": ["https://malawi.gov.mw"],
    },
    "TZA": {
        "country_code": "TZA",
        "country_name": "Tanzania",
        "iso2": "TZ",
        "flag": "🇹🇿",
        "capital": "Dodoma",
        "currency": "TZS",
        "currency_name": "Tanzanian Shilling",
        "phase": 4,
        "group": "Emerging Markets",
        "economy_focus": "agriculture_mining_tourism",
        "gdp_usd_billion": 75.0,
        "population_million": 63.0,
        "is_sacu": False,
        "is_ldc": True,
        "is_island": False,
        "dual_membership": ["EAC", "SADC"],
        "primary_customs_source": "https://www.tra.go.tz",
        "secondary_sources": ["https://www.tra.go.tz"],
    },
}

# Convenience groupings
SACU_MEMBERS = [c for c, v in SADC_COUNTRIES.items() if v["is_sacu"]]
LDC_MEMBERS = [c for c, v in SADC_COUNTRIES.items() if v["is_ldc"]]
ISLAND_MEMBERS = [c for c, v in SADC_COUNTRIES.items() if v["is_island"]]
DUAL_EAC_SADC = [c for c, v in SADC_COUNTRIES.items() if "EAC" in v["dual_membership"]]

# ---------------------------------------------------------------------------
# Regional organisation metadata
# ---------------------------------------------------------------------------

SADC_ORG = {
    "full_name": "Southern African Development Community",
    "abbreviation": "SADC",
    "headquarters": "Gaborone, Botswana",
    "founded": 1992,
    "secretariat_url": "https://www.sadc.int",
    "member_count": 16,
    "combined_gdp_usd_billion": 800,
    "combined_population_million": 345,
    "official_languages": ["English", "French", "Portuguese"],
    "treaty": "SADC Treaty (1992)",
}

SACU_ORG = {
    "full_name": "Southern African Customs Union",
    "abbreviation": "SACU",
    "headquarters": "Windhoek, Namibia",
    "founded": 1910,
    "secretariat_url": "https://www.sacu.int",
    "member_count": 5,
    "note": "Oldest functioning customs union in the world",
}

# ---------------------------------------------------------------------------
# Metadata
# ---------------------------------------------------------------------------

SADC_CONSTANTS_VERSION = "1.0.0"
SADC_CONSTANTS_DATE = datetime(2026, 3, 1).date().isoformat()
