SADC_TRADE_STATISTICS = {
    "intra_sadc_trade_share_pct": 19,
    "total_sadc_gdp_usd_billion": 800,
    "total_sadc_trade_usd_billion": 350,
    "largest_economy": "ZAF",
    "largest_trader": "ZAF",
    "top_intra_sadc_trade_routes": [
        {"from": "ZAF", "to": "ZWE", "value_usd_billion": 2.5},
        {"from": "ZAF", "to": "ZMB", "value_usd_billion": 1.8},
        {"from": "ZAF", "to": "MOZ", "value_usd_billion": 1.5},
        {"from": "ZAF", "to": "NAM", "value_usd_billion": 2.0},
        {"from": "ZAF", "to": "BWA", "value_usd_billion": 3.2},
    ],
    "top_export_products": [
        "gold",
        "diamonds",
        "platinum",
        "copper",
        "coal",
        "vehicles_and_parts",
        "machinery",
        "food_and_beverages",
        "tobacco",
        "cut_flowers",
    ],
    "main_external_partners": ["China", "EU", "USA", "India", "UAE"],
}
