"""
Test AI Tabs Integration - Vue d'ensemble, Chaînes de Valeur, Par Produit
Tests the new AI-powered endpoints for the Opportunities sub-tabs
"""
import pytest
import requests
import os
import time

# Get BASE_URL from environment
BASE_URL = os.environ.get('REACT_APP_BACKEND_URL', '').rstrip('/')
if not BASE_URL:
    BASE_URL = "https://commerce-africain.preview.emergentagent.com"

API_URL = f"{BASE_URL}/api"


class TestAISummaryEndpoint:
    """Tests for /api/ai/summary - Vue d'ensemble tab"""
    
    def test_ai_summary_returns_200(self):
        """Test that AI summary endpoint returns 200"""
        response = requests.get(f"{API_URL}/ai/summary?lang=fr", timeout=120)
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        print(f"✓ AI Summary endpoint returned 200")
    
    def test_ai_summary_has_overview_data(self):
        """Test that AI summary contains overview section with required fields"""
        response = requests.get(f"{API_URL}/ai/summary?lang=fr", timeout=120)
        assert response.status_code == 200
        
        data = response.json()
        
        # Check for overview section
        assert "overview" in data, "Response should contain 'overview' section"
        overview = data["overview"]
        
        # Check required fields in overview
        required_fields = [
            "total_african_trade_billion_usd",
            "intra_african_trade_billion_usd",
            "afcfta_countries"
        ]
        
        for field in required_fields:
            assert field in overview, f"Overview should contain '{field}'"
            print(f"✓ Found {field}: {overview[field]}")
        
        # Validate data ranges
        assert overview.get("afcfta_countries", 0) >= 50, "Should have ~54 AfCFTA countries"
        print(f"✓ AI Summary has valid overview data")
    
    def test_ai_summary_has_top_trading_countries(self):
        """Test that AI summary contains top trading countries"""
        response = requests.get(f"{API_URL}/ai/summary?lang=fr", timeout=120)
        assert response.status_code == 200
        
        data = response.json()
        
        assert "top_trading_countries" in data, "Response should contain 'top_trading_countries'"
        countries = data["top_trading_countries"]
        
        assert isinstance(countries, list), "top_trading_countries should be a list"
        assert len(countries) > 0, "Should have at least one trading country"
        
        # Check first country has required fields
        first_country = countries[0]
        assert "name" in first_country, "Country should have 'name'"
        print(f"✓ Found {len(countries)} top trading countries")
        print(f"  First country: {first_country.get('name')}")
    
    def test_ai_summary_has_top_sectors(self):
        """Test that AI summary contains top sectors"""
        response = requests.get(f"{API_URL}/ai/summary?lang=fr", timeout=120)
        assert response.status_code == 200
        
        data = response.json()
        
        assert "top_sectors" in data, "Response should contain 'top_sectors'"
        sectors = data["top_sectors"]
        
        assert isinstance(sectors, list), "top_sectors should be a list"
        assert len(sectors) > 0, "Should have at least one sector"
        
        print(f"✓ Found {len(sectors)} top sectors")
        for sector in sectors[:3]:
            print(f"  - {sector.get('name', 'Unknown')}")
    
    def test_ai_summary_has_generated_by_marker(self):
        """Test that AI summary has AI generation marker"""
        response = requests.get(f"{API_URL}/ai/summary?lang=fr", timeout=120)
        assert response.status_code == 200
        
        data = response.json()
        
        assert "generated_by" in data, "Response should have 'generated_by' marker"
        assert "Gemini" in data["generated_by"], "Should be generated by Gemini AI"
        print(f"✓ AI Summary generated by: {data['generated_by']}")


class TestAIValueChainsEndpoint:
    """Tests for /api/ai/value-chains - Chaînes de Valeur tab"""
    
    def test_value_chains_returns_200(self):
        """Test that value chains endpoint returns 200"""
        response = requests.get(f"{API_URL}/ai/value-chains?lang=fr", timeout=120)
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        print(f"✓ Value Chains endpoint returned 200")
    
    def test_value_chains_has_6_sectors(self):
        """Test that value chains returns 6 main sectors"""
        response = requests.get(f"{API_URL}/ai/value-chains?lang=fr", timeout=120)
        assert response.status_code == 200
        
        data = response.json()
        
        assert "value_chains" in data, "Response should contain 'value_chains'"
        chains = data["value_chains"]
        
        assert isinstance(chains, list), "value_chains should be a list"
        # Should have at least 6 value chains (coffee, cocoa, cotton, petroleum, minerals, automotive)
        assert len(chains) >= 6, f"Should have at least 6 value chains, got {len(chains)}"
        
        print(f"✓ Found {len(chains)} value chains")
        for chain in chains:
            chain_name = chain.get("name", {})
            if isinstance(chain_name, dict):
                name = chain_name.get("fr", chain_name.get("en", "Unknown"))
            else:
                name = chain_name
            print(f"  - {chain.get('icon', '')} {name}")
    
    def test_value_chains_has_required_structure(self):
        """Test that each value chain has required structure"""
        response = requests.get(f"{API_URL}/ai/value-chains?lang=fr", timeout=120)
        assert response.status_code == 200
        
        data = response.json()
        chains = data.get("value_chains", [])
        
        if len(chains) > 0:
            first_chain = chains[0]
            
            # Check required fields
            required_fields = ["id", "name", "hs_code"]
            for field in required_fields:
                assert field in first_chain, f"Value chain should have '{field}'"
            
            # Check for top_producers
            if "top_producers" in first_chain:
                producers = first_chain["top_producers"]
                assert isinstance(producers, list), "top_producers should be a list"
                if len(producers) > 0:
                    assert "country" in producers[0], "Producer should have 'country'"
                    print(f"✓ First chain has {len(producers)} top producers")
    
    def test_value_chains_specific_sector(self):
        """Test value chains for a specific sector (coffee)"""
        response = requests.get(f"{API_URL}/ai/value-chains?sector=coffee&lang=fr", timeout=120)
        assert response.status_code == 200
        
        data = response.json()
        print(f"✓ Coffee sector analysis returned successfully")
        
        if "value_chains" in data:
            chains = data["value_chains"]
            # Should have coffee-related data
            coffee_found = any(
                "coffee" in str(c.get("id", "")).lower() or 
                "café" in str(c.get("name", "")).lower()
                for c in chains
            )
            print(f"  Coffee data found: {coffee_found}")
    
    def test_value_chains_has_ai_marker(self):
        """Test that value chains has AI generation marker"""
        response = requests.get(f"{API_URL}/ai/value-chains?lang=fr", timeout=120)
        assert response.status_code == 200
        
        data = response.json()
        
        assert "generated_by" in data, "Response should have 'generated_by' marker"
        print(f"✓ Value Chains generated by: {data['generated_by']}")


class TestAIProductEndpoint:
    """Tests for /api/ai/product/{hs_code} - Par Produit tab"""
    
    def test_product_coffee_090111(self):
        """Test product analysis for coffee (HS 090111)"""
        response = requests.get(f"{API_URL}/ai/product/090111?lang=fr", timeout=120)
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        
        data = response.json()
        
        # Check product info
        assert "product" in data, "Response should contain 'product' info"
        product = data["product"]
        assert "name" in product, "Product should have 'name'"
        print(f"✓ Product 090111: {product.get('name')}")
    
    def test_product_has_african_trade_data(self):
        """Test that product analysis has African trade data"""
        response = requests.get(f"{API_URL}/ai/product/090111?lang=fr", timeout=120)
        assert response.status_code == 200
        
        data = response.json()
        
        # Check for African trade summary
        if "african_trade_summary" in data:
            summary = data["african_trade_summary"]
            print(f"✓ African trade summary found")
            print(f"  Total exports: ${summary.get('total_african_exports_musd', 0)}M")
            print(f"  Total imports: ${summary.get('total_african_imports_musd', 0)}M")
    
    def test_product_has_exporters_importers(self):
        """Test that product analysis has top exporters and importers"""
        response = requests.get(f"{API_URL}/ai/product/090111?lang=fr", timeout=120)
        assert response.status_code == 200
        
        data = response.json()
        
        # Check for exporters
        if "top_african_exporters" in data:
            exporters = data["top_african_exporters"]
            assert isinstance(exporters, list), "top_african_exporters should be a list"
            print(f"✓ Found {len(exporters)} top African exporters")
            for exp in exporters[:3]:
                print(f"  - {exp.get('country')}: ${exp.get('export_value_musd', 0)}M")
        
        # Check for importers
        if "top_african_importers" in data:
            importers = data["top_african_importers"]
            assert isinstance(importers, list), "top_african_importers should be a list"
            print(f"✓ Found {len(importers)} top African importers")
    
    def test_product_invalid_hs_code(self):
        """Test that invalid HS code returns 400"""
        response = requests.get(f"{API_URL}/ai/product/abc?lang=fr", timeout=30)
        assert response.status_code == 400, f"Expected 400 for invalid HS code, got {response.status_code}"
        print(f"✓ Invalid HS code correctly returns 400")
    
    def test_product_has_ai_marker(self):
        """Test that product analysis has AI generation marker"""
        response = requests.get(f"{API_URL}/ai/product/090111?lang=fr", timeout=120)
        assert response.status_code == 200
        
        data = response.json()
        
        assert "generated_by" in data, "Response should have 'generated_by' marker"
        print(f"✓ Product analysis generated by: {data['generated_by']}")


class TestSubstitutionOpportunities:
    """Tests for /api/substitution/opportunities/import/{country} endpoint"""
    
    def test_substitution_morocco_returns_200(self):
        """Test substitution opportunities for Morocco (MAR)"""
        response = requests.get(f"{API_URL}/substitution/opportunities/import/MAR?lang=fr", timeout=60)
        
        if response.status_code == 404:
            print(f"⚠ Substitution endpoint not found (404)")
            pytest.skip("Substitution endpoint not implemented")
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        print(f"✓ Substitution opportunities for Morocco returned 200")
        
        data = response.json()
        if isinstance(data, list):
            print(f"  Found {len(data)} substitution opportunities")
        elif isinstance(data, dict):
            if "opportunities" in data:
                print(f"  Found {len(data['opportunities'])} substitution opportunities")
            else:
                print(f"  Response keys: {list(data.keys())}")


class TestAIHealthEndpoint:
    """Tests for /api/ai/health endpoint"""
    
    def test_ai_health_returns_operational(self):
        """Test that AI health endpoint returns operational status"""
        response = requests.get(f"{API_URL}/ai/health", timeout=30)
        assert response.status_code == 200, f"Expected 200, got {response.status_code}"
        
        data = response.json()
        
        assert "status" in data, "Response should have 'status'"
        assert data["status"] == "operational", f"Expected 'operational', got {data['status']}"
        assert data.get("api_key_configured") == True, "API key should be configured"
        
        print(f"✓ AI Health: {data['status']}")
        print(f"  Model: {data.get('model')}")
        print(f"  Provider: {data.get('provider')}")


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
